import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const danielUnits: UnitDef[] = [
  {
    slug: "daniel-u1-contexto-e-fidelidade",
    title: "Contexto e fidelidade",
    description: "O exílio na Babilônia, a vida na corte e o próprio livro de Daniel.",
    scene: "palace",
    lessons: [
      {
        slug: "d1-exilio-na-babilonia",
        title: "Longe de casa: o exílio",
        objective: "Entender o contexto histórico do livro de Daniel.",
        references: ["Daniel 1:1-2", "2 Reis 24:10-16", "2 Reis 25:8-11", "Salmos 137:1-4"],
        context: "As histórias de Daniel se passam na Babilônia, depois que o rei Nabucodonosor dominou Judá.",
        blocks: [
          b(
            "contexto",
            "Nabucodonosor e Jerusalém",
            "No início do século VI a.C., o rei babilônico Nabucodonosor cercou Jerusalém e levou parte da população — começando pela nobreza e pelos artesãos — para a Babilônia. Em 586 a.C., a cidade e o templo foram destruídos.",
            "2 Reis 24:10-16; 25:8-11",
          ),
          b(
            "resumo",
            "Objetos do templo",
            "O livro de Daniel começa contando que Nabucodonosor levou para a Babilônia parte dos utensílios do templo de Jerusalém.",
            "Daniel 1:1-2",
          ),
          b(
            "resumo",
            "Junto aos rios da Babilônia",
            "O Salmo 137 expressa a dor do exílio: os exilados se sentavam junto aos rios da Babilônia e choravam lembrando de Sião, sem conseguir cantar em terra estrangeira.",
            "Salmos 137:1-4",
          ),
        ],
        exercises: [
          mc(
            "Qual rei levou os habitantes de Judá para a Babilônia?",
            ["Nabucodonosor", "Ciro", "Faraó", "Senaqueribe"],
            0,
            "Daniel 1:1; 2 Reis 24.",
            "Daniel 1:1",
          ),
          fill(
            "Jerusalém e o templo foram destruídos no ano",
            "a.C.",
            ["586", "722", "70"],
            0,
            "A destruição aconteceu em 586 a.C.",
            "2 Reis 25:8-9",
          ),
          tf(
            "O livro de Daniel começa mencionando utensílios do templo levados para a Babilônia.",
            true,
            "Daniel 1:2.",
            "Daniel 1:2",
          ),
          mc(
            "Qual salmo expressa a tristeza dos exilados junto aos rios da Babilônia?",
            ["Salmo 137", "Salmo 23", "Salmo 1", "Salmo 150"],
            0,
            "Salmos 137:1.",
            "Salmos 137:1",
          ),
          order(
            "Ordene os acontecimentos.",
            ["Nabucodonosor cerca Jerusalém", "Parte do povo é levada à Babilônia", "Jerusalém e o templo são destruídos"],
            "2 Reis 24-25.",
            "2 Reis 24-25",
          ),
        ],
        takeaways: [
          "Nabucodonosor levou parte de Judá para a Babilônia.",
          "Jerusalém e o templo foram destruídos em 586 a.C.",
          "O exílio foi vivido com dor, como mostra o Salmo 137.",
        ],
        reflection: "Como manter quem você é quando está longe de casa?",
      },
      {
        slug: "d1-na-corte-da-babilonia",
        title: "Jovens na corte",
        objective: "Conhecer Daniel e seus amigos e os nomes que receberam na Babilônia.",
        references: ["Daniel 1:3-7"],
        context: "Nabucodonosor queria jovens de famílias nobres de Judá para servir em seu palácio.",
        blocks: [
          b(
            "resumo",
            "Três anos de formação",
            "Os jovens escolhidos deveriam ser saudáveis, inteligentes e bem instruídos. Durante três anos, aprenderiam a língua e a literatura dos caldeus.",
            "Daniel 1:3-5",
          ),
          b(
            "resumo",
            "Novos nomes",
            "Entre eles estavam Daniel, Hananias, Misael e Azarias. O chefe dos oficiais deu-lhes nomes babilônicos: Beltessazar, Sadraque, Mesaque e Abede-Nego.",
            "Daniel 1:6-7",
          ),
          b(
            "explicacao",
            "Nomes que contam histórias",
            "Os nomes hebraicos mencionavam o Deus de Israel — Daniel significa “Deus é meu juiz”. Os novos nomes os ligavam à cultura babilônica. Mudar o nome era também uma forma de integrar os jovens ao império.",
          ),
        ],
        exercises: [
          match(
            "Associe cada nome hebraico ao nome babilônico.",
            [
              ["Daniel", "Beltessazar"],
              ["Hananias", "Sadraque"],
              ["Misael", "Mesaque"],
              ["Azarias", "Abede-Nego"],
            ],
            "Daniel 1:7.",
            "Daniel 1:7",
          ),
          mc(
            "Por quanto tempo os jovens seriam formados?",
            ["Três anos", "Sete anos", "Quarenta dias", "Um ano"],
            0,
            "Daniel 1:5.",
            "Daniel 1:5",
          ),
          fill(
            "O nome Daniel significa “Deus é meu",
            "”.",
            ["juiz", "pastor", "rei"],
            0,
            "Daniel: “Deus é meu juiz”.",
            "Daniel 1:6",
          ),
          tf(
            "Os jovens deveriam aprender a língua e a literatura dos caldeus.",
            true,
            "Daniel 1:4.",
            "Daniel 1:4",
          ),
          mc(
            "Por que mudar o nome dos jovens era significativo?",
            ["Era uma forma de integrá-los à cultura do império", "Era um costume de aniversário", "Porque os nomes eram difíceis", "Para escondê-los do rei"],
            0,
            "Os nomes babilônicos os ligavam à cultura da Babilônia.",
            "Daniel 1:7",
          ),
        ],
        takeaways: [
          "Daniel e seus amigos foram formados na corte por três anos.",
          "Receberam nomes babilônicos.",
          "Daniel significa “Deus é meu juiz”.",
        ],
        reflection: "O que da sua identidade você não abriria mão em um ambiente novo?",
      },
      {
        slug: "d1-a-escolha-do-alimento",
        title: "Uma escolha à mesa",
        objective: "Conhecer a primeira escolha de fidelidade de Daniel.",
        references: ["Daniel 1:8-21"],
        context: "Os jovens deveriam comer da comida e do vinho da mesa do rei.",
        blocks: [
          b(
            "resumo",
            "Uma proposta respeitosa",
            "Daniel decide não se contaminar com a comida do rei e pede permissão ao responsável. Propõe um teste: dez dias comendo legumes e bebendo água.",
            "Daniel 1:8-14",
          ),
          b(
            "resumo",
            "O resultado",
            "Depois de dez dias, os quatro estavam com aparência mais saudável que os outros jovens. Ao fim da formação, o rei os achou dez vezes mais sábios que todos os magos do reino.",
            "Daniel 1:15-20",
          ),
          b(
            "contexto",
            "Por que recusar?",
            "O texto não explica em detalhes o motivo. Leitores sugerem razões como as leis alimentares judaicas ou a ligação da comida do rei com cultos babilônicos. O destaque é a escolha de manter a fidelidade com diálogo e respeito.",
          ),
        ],
        exercises: [
          mc(
            "O que Daniel propôs comer durante o teste?",
            ["Legumes e água", "Carne e vinho", "Pão e mel", "Peixe e leite"],
            0,
            "Daniel 1:12.",
            "Daniel 1:12",
          ),
          fill(
            "O teste durou",
            "dias.",
            ["dez", "três", "quarenta"],
            0,
            "Daniel 1:12-15.",
            "Daniel 1:12-15",
          ),
          tf(
            "Daniel agiu com respeito e pediu permissão ao responsável.",
            true,
            "Daniel 1:8-13.",
            "Daniel 1:8-13",
          ),
          mc(
            "Como o rei avaliou os quatro jovens ao final?",
            ["Dez vezes mais sábios que os magos", "Iguais aos outros", "Fracos e doentes", "Prontos para voltar a Judá"],
            0,
            "Daniel 1:20.",
            "Daniel 1:20",
          ),
          order(
            "Ordene o relato.",
            ["Daniel decide não comer da mesa do rei", "Propõe um teste de dez dias", "Os jovens aparecem mais saudáveis", "O rei os considera mais sábios"],
            "Daniel 1:8-20.",
            "Daniel 1:8-20",
          ),
        ],
        takeaways: [
          "Daniel escolhe não comer da mesa do rei.",
          "Ele propõe um teste com diálogo e respeito.",
          "Os quatro jovens se destacam em saúde e sabedoria.",
        ],
        reflection: "Que pequena escolha diária ajuda você a ser fiel ao que valoriza?",
      },
      {
        slug: "d1-um-livro-duas-partes",
        title: "Um livro, duas partes, duas línguas",
        objective: "Conhecer a organização do livro de Daniel e as diferenças entre tradições.",
        references: ["Daniel 1-6", "Daniel 7-12", "Daniel 2:4"],
        context: "Daniel é um livro surpreendente: tem histórias de corte e visões cheias de símbolos.",
        blocks: [
          b(
            "explicacao",
            "Duas partes",
            "Os capítulos 1 a 6 trazem histórias sobre Daniel e seus amigos na corte. Os capítulos 7 a 12 trazem visões, contadas por Daniel em primeira pessoa, em linguagem apocalíptica — cheia de animais simbólicos e números.",
          ),
          b(
            "contexto",
            "Duas línguas",
            "O livro foi escrito parte em hebraico e parte em aramaico: o trecho de Daniel 2:4 até o fim do capítulo 7 está em aramaico, a língua comum do império.",
            "Daniel 2:4",
          ),
          b(
            "tradicoes",
            "Partes a mais nas Bíblias católicas",
            "As Bíblias católicas (e ortodoxas) incluem acréscimos que vêm da antiga tradução grega: a oração de Azarias e o cântico dos três jovens no capítulo 3, e as histórias de Susana e de Bel e o Dragão (capítulos 13 e 14). Atenção também à numeração: nos capítulos 4 a 6, alguns versículos têm números diferentes em Bíblias que seguem a contagem hebraica (como muitas católicas). Aqui usamos a numeração mais comum nas Bíblias protestantes em português.",
          ),
          b(
            "tradicoes",
            "Quando foi escrito?",
            "Na leitura tradicional, o livro foi escrito por Daniel no século VI a.C. Muitos estudiosos entendem que, em sua forma final, o livro é do século II a.C., quando o povo judeu foi perseguido pelo rei selêucida Antíoco IV, e que as histórias encorajavam a fidelidade nesse tempo.",
          ),
        ],
        exercises: [
          match(
            "Associe cada parte do livro ao seu conteúdo.",
            [
              ["Capítulos 1-6", "Histórias na corte"],
              ["Capítulos 7-12", "Visões simbólicas"],
            ],
            "Daniel tem duas partes bem diferentes.",
            "Daniel 1-12",
          ),
          mc(
            "Em quais línguas o livro de Daniel foi escrito?",
            ["Hebraico e aramaico", "Grego e latim", "Só hebraico", "Só aramaico"],
            0,
            "Daniel 2:4 até o fim do capítulo 7 está em aramaico.",
            "Daniel 2:4",
          ),
          tf(
            "As Bíblias católicas incluem as histórias de Susana e de Bel e o Dragão.",
            true,
            "São os capítulos 13 e 14 nas Bíblias católicas.",
            "Daniel 13-14 (Bíblias católicas)",
          ),
          mc(
            "Qual afirmação sobre a data do livro é mais equilibrada?",
            [
              "A tradição situa no século VI a.C.; muitos estudiosos, a forma final no século II a.C.",
              "Todos concordam que foi escrito no século I",
              "Foi escrito depois do Novo Testamento",
              "Não há nenhum debate sobre isso",
            ],
            0,
            "Existem as duas posições.",
            "Introdução a Daniel",
          ),
          fill(
            "A linguagem cheia de símbolos das visões é chamada de",
            ".",
            ["apocalíptica", "jurídica", "épica"],
            0,
            "Daniel 7-12 é um exemplo de literatura apocalíptica.",
            "Daniel 7-12",
          ),
        ],
        takeaways: [
          "Daniel tem histórias (1-6) e visões (7-12).",
          "Parte do livro está em aramaico.",
          "Tradições diferem quanto aos acréscimos e à data do livro.",
        ],
        reflection: "Histórias de fidelidade podem encorajar em tempos difíceis. Qual história encoraja você?",
      },
      {
        slug: "d1-daniel-nas-tradicoes",
        title: "Daniel: profeta ou sábio?",
        objective: "Entender onde o livro de Daniel aparece nas diferentes Bíblias.",
        references: ["Mateus 24:15", "Daniel 1:17", "Daniel 9:2"],
        context: "Daniel é chamado de muitas formas: profeta, sábio, intérprete de sonhos, visionário.",
        blocks: [
          b(
            "tradicoes",
            "Em lugares diferentes",
            "Nas Bíblias cristãs, Daniel aparece entre os profetas, depois de Ezequiel. Na Bíblia Hebraica, o livro está na terceira parte, os Escritos (Ketuvim), e não entre os Profetas.",
          ),
          b(
            "resumo",
            "Um sábio que interpreta",
            "O livro descreve Daniel como alguém a quem Deus deu conhecimento e entendimento, inclusive para interpretar visões e sonhos.",
            "Daniel 1:17",
          ),
          b(
            "resumo",
            "Leitor dos profetas",
            "Em Daniel 9, ele aparece lendo o livro do profeta Jeremias. E, nos Evangelhos, Jesus menciona “o profeta Daniel” ao falar de acontecimentos futuros.",
            "Daniel 9:2; Mateus 24:15",
          ),
        ],
        exercises: [
          match(
            "Associe cada Bíblia ao lugar onde Daniel aparece.",
            [
              ["Bíblias cristãs", "Entre os profetas"],
              ["Bíblia Hebraica", "Nos Escritos (Ketuvim)"],
            ],
            "A posição do livro varia.",
            "Introdução a Daniel",
          ),
          tf(
            "Em Mateus 24:15, Jesus menciona “o profeta Daniel”.",
            true,
            "Mateus 24:15.",
            "Mateus 24:15",
          ),
          mc(
            "Qual livro Daniel aparece lendo em Daniel 9?",
            ["Jeremias", "Gênesis", "Salmos", "Isaías"],
            0,
            "Daniel 9:2.",
            "Daniel 9:2",
          ),
          fill(
            "Segundo Daniel 1:17, Deus deu a Daniel entendimento para interpretar visões e",
            ".",
            ["sonhos", "leis", "estrelas"],
            0,
            "Daniel 1:17.",
            "Daniel 1:17",
          ),
          mc(
            "Qual é a melhor forma de descrever Daniel no Vereda?",
            ["Um personagem profético, com perfis de sábio e visionário", "Apenas um rei", "Um apóstolo", "Um juiz de Israel"],
            0,
            "O livro o apresenta como sábio, intérprete e visionário.",
            "Daniel 1:17; 7:1",
          ),
        ],
        takeaways: [
          "Nas Bíblias cristãs, Daniel está entre os profetas; na hebraica, nos Escritos.",
          "Daniel é apresentado como sábio e intérprete de sonhos.",
          "Jesus menciona “o profeta Daniel” em Mateus.",
        ],
        reflection: "Você se vê mais como alguém que age, que reflete ou que imagina o futuro?",
      },
    ],
    review: {
      slug: "daniel-u1-revisao",
      title: "Revisão: Contexto e fidelidade",
      intro: "Do exílio à mesa do rei. Vamos relembrar o começo da jornada com Daniel.",
      extra: [
        order(
          "Ordene os acontecimentos.",
          ["Nabucodonosor leva jovens de Judá", "Os jovens recebem nomes babilônicos", "Daniel propõe o teste dos legumes", "O rei os considera mais sábios"],
          "Daniel 1.",
          "Daniel 1",
        ),
        match(
          "Associe cada termo ao seu sentido.",
          [
            ["Exílio", "Viver longe da própria terra à força"],
            ["Aramaico", "Língua de parte do livro"],
            ["Ketuvim", "Escritos, na Bíblia Hebraica"],
          ],
          "Termos da unidade.",
          "Daniel 1-2",
        ),
        tf(
          "Daniel recusou a comida do rei com diálogo e respeito.",
          true,
          "Daniel 1:8-13.",
          "Daniel 1:8-13",
        ),
      ],
      takeaways: [
        "As histórias de Daniel se passam no exílio na Babilônia.",
        "Daniel e seus amigos mantêm sua identidade na corte.",
        "O livro tem duas partes, duas línguas e leituras diferentes entre tradições.",
      ],
    },
  },
  {
    slug: "daniel-u2-sonhos-e-reis",
    title: "Sonhos e reis",
    description: "Sonhos de Nabucodonosor, a fornalha ardente e a escrita na parede.",
    scene: "palace",
    lessons: [
      {
        slug: "d2-sonho-do-rei",
        title: "O sonho que ninguém sabia",
        objective: "Conhecer o desafio do sonho de Nabucodonosor.",
        references: ["Daniel 2:1-30"],
        context: "Nabucodonosor tem um sonho que o perturba e faz um pedido impossível aos sábios da Babilônia.",
        blocks: [
          b(
            "resumo",
            "Um pedido impossível",
            "O rei exige que os sábios contem o sonho que ele teve e também a interpretação. Eles dizem que ninguém na terra poderia fazer isso, e o rei, furioso, manda matar todos os sábios.",
            "Daniel 2:1-13",
          ),
          b(
            "resumo",
            "Oração em grupo",
            "Daniel pede tempo e conta tudo a seus amigos, para que orem juntos. À noite, o mistério é revelado a Daniel numa visão, e ele agradece com um cântico de louvor.",
            "Daniel 2:16-23",
          ),
          b(
            "resumo",
            "“Há um Deus no céu”",
            "Diante do rei, Daniel diz que nenhum sábio poderia revelar o mistério, mas que há um Deus no céu que revela os segredos — e que isso não acontecia por ele ser mais sábio que os outros.",
            "Daniel 2:27-30",
          ),
        ],
        exercises: [
          mc(
            "O que o rei exigiu dos sábios?",
            ["Que contassem o sonho e a interpretação", "Que construíssem um templo", "Que cantassem para ele", "Que previssem a chuva"],
            0,
            "Daniel 2:5-6.",
            "Daniel 2:5-6",
          ),
          tf(
            "Daniel pediu aos amigos que orassem junto com ele.",
            true,
            "Daniel 2:17-18.",
            "Daniel 2:17-18",
          ),
          fill(
            "Daniel diz ao rei que há um Deus no céu que revela os",
            ".",
            ["segredos", "tesouros", "exércitos"],
            0,
            "Daniel 2:28.",
            "Daniel 2:28",
          ),
          mc(
            "Como Daniel recebe a revelação do sonho?",
            ["Numa visão à noite", "Lendo um livro antigo", "Perguntando a um anjo no palácio", "Por uma carta"],
            0,
            "Daniel 2:19.",
            "Daniel 2:19",
          ),
          order(
            "Ordene o relato.",
            ["O rei tem um sonho perturbador", "Os sábios não conseguem responder", "Daniel e os amigos oram", "Daniel vai ao rei"],
            "Daniel 2:1-25.",
            "Daniel 2:1-25",
          ),
        ],
        takeaways: [
          "Nabucodonosor exige que contem seu sonho e o interpretem.",
          "Daniel busca a ajuda dos amigos em oração.",
          "Ele atribui a revelação a Deus, não à própria sabedoria.",
        ],
        reflection: "Diante de um problema difícil, quem você chama para estar junto?",
      },
      {
        slug: "d2-estatua-e-pedra",
        title: "A estátua e a pedra",
        objective: "Conhecer o conteúdo do sonho da estátua.",
        references: ["Daniel 2:31-49"],
        context: "Daniel conta ao rei o que ele sonhou: uma estátua enorme e impressionante.",
        blocks: [
          b(
            "resumo",
            "De ouro a barro",
            "A estátua tinha cabeça de ouro, peito e braços de prata, ventre e coxas de bronze, pernas de ferro e pés de ferro misturado com barro.",
            "Daniel 2:31-33",
          ),
          b(
            "resumo",
            "Uma pedra sem mãos",
            "Uma pedra, cortada sem auxílio de mãos, atinge os pés da estátua e a despedaça. A pedra se torna uma grande montanha que enche a terra.",
            "Daniel 2:34-35",
          ),
          b(
            "interpretacao",
            "Reinos que passam",
            "Daniel explica que a cabeça de ouro é Nabucodonosor e que outros reinos viriam depois; por fim, Deus estabeleceria um reino que nunca seria destruído. Leitores identificam os reinos seguintes de formas diferentes (por exemplo, medos, persas, gregos ou romanos).",
            "Daniel 2:36-45",
          ),
        ],
        exercises: [
          order(
            "Ordene os materiais da estátua, de cima para baixo.",
            ["Ouro", "Prata", "Bronze", "Ferro", "Ferro com barro"],
            "Daniel 2:32-33.",
            "Daniel 2:32-33",
          ),
          mc(
            "O que derruba a estátua?",
            ["Uma pedra cortada sem mãos", "Um terremoto", "Um exército", "Um raio"],
            0,
            "Daniel 2:34.",
            "Daniel 2:34",
          ),
          fill(
            "A cabeça de ouro representava o rei",
            ".",
            ["Nabucodonosor", "Dario", "Ciro"],
            0,
            "Daniel 2:37-38.",
            "Daniel 2:37-38",
          ),
          tf(
            "Todos os leitores identificam os reinos da estátua exatamente da mesma forma.",
            false,
            "Há identificações diferentes para os reinos seguintes.",
            "Daniel 2:39-43",
          ),
          mc(
            "Em que a pedra se transforma?",
            ["Numa grande montanha que enche a terra", "Num rio", "Numa coroa", "Num templo de ouro"],
            0,
            "Daniel 2:35.",
            "Daniel 2:35",
          ),
        ],
        takeaways: [
          "A estátua tem materiais que vão do ouro ao barro.",
          "Uma pedra sem mãos a destrói e vira montanha.",
          "O sonho fala de reinos que passam e de um reino que permanece.",
        ],
        reflection: "O que, na sua vida, parece forte por fora mas tem “pés de barro”?",
      },
      {
        slug: "d2-fornalha-ardente",
        title: "A fornalha ardente",
        objective: "Conhecer a fidelidade de Sadraque, Mesaque e Abede-Nego.",
        references: ["Daniel 3:1-30"],
        context: "Nabucodonosor ergue uma enorme estátua de ouro e ordena que todos se prostrem diante dela.",
        blocks: [
          b(
            "resumo",
            "Quando a música tocar",
            "Ao som dos instrumentos, todos deveriam se prostrar diante da estátua. Quem não o fizesse seria lançado numa fornalha. Os três amigos de Daniel se recusam.",
            "Daniel 3:1-12",
          ),
          b(
            "resumo",
            "“E, se não…”",
            "Diante do rei, eles dizem que o Deus a quem servem pode livrá-los — e, mesmo que não os livre, não adorariam a estátua.",
            "Daniel 3:16-18",
          ),
          b(
            "resumo",
            "Quatro na fornalha",
            "A fornalha é aquecida sete vezes mais, e os três são lançados nela. O rei vê quatro homens andando soltos no fogo, sem se queimar; o quarto parecia um ser divino. Os três saem sem nem cheiro de fumaça.",
            "Daniel 3:19-27",
          ),
        ],
        exercises: [
          match(
            "Quem estava na fornalha? Associe os nomes hebraicos aos babilônicos.",
            [
              ["Hananias", "Sadraque"],
              ["Misael", "Mesaque"],
              ["Azarias", "Abede-Nego"],
            ],
            "Daniel 1:7; 3:12.",
            "Daniel 1:7",
          ),
          fill(
            "Os três disseram que, mesmo que Deus não os livrasse, não adorariam a",
            ".",
            ["estátua", "lua", "fornalha"],
            0,
            "Daniel 3:18.",
            "Daniel 3:18",
          ),
          mc(
            "Quantos homens o rei viu andando na fornalha?",
            ["Quatro", "Três", "Dois", "Sete"],
            0,
            "Daniel 3:25.",
            "Daniel 3:25",
          ),
          tf(
            "Os três saíram da fornalha sem cheiro de fumaça.",
            true,
            "Daniel 3:27.",
            "Daniel 3:27",
          ),
          mc(
            "Quantas vezes mais a fornalha foi aquecida?",
            ["Sete", "Três", "Dez", "Doze"],
            0,
            "Daniel 3:19.",
            "Daniel 3:19",
          ),
        ],
        takeaways: [
          "Os três amigos se recusam a adorar a estátua.",
          "Sua fidelidade não dependia de serem livrados: “e, se não…”.",
          "Na fornalha, o rei vê quatro homens andando no fogo.",
        ],
        reflection: "O que significa ser fiel “mesmo que não” as coisas saiam como você espera?",
      },
      {
        slug: "d2-arvore-do-rei",
        title: "A árvore cortada",
        objective: "Conhecer o segundo sonho de Nabucodonosor e sua lição de humildade.",
        references: ["Daniel 4:1-37"],
        context: "O capítulo 4 é contado em boa parte pelo próprio Nabucodonosor, como uma carta.",
        blocks: [
          b(
            "resumo",
            "Uma árvore enorme",
            "O rei sonha com uma árvore enorme que alcançava o céu e alimentava a todos. Um mensageiro celestial manda cortá-la, deixando só o toco com as raízes.",
            "Daniel 4:10-15",
          ),
          b(
            "resumo",
            "O orgulho do rei",
            "Daniel interpreta: a árvore é o próprio rei. Ele aconselha o rei a praticar a justiça e ter compaixão dos pobres. Tempos depois, o rei se orgulha da Babilônia que construiu e passa a viver afastado das pessoas, como os animais do campo.",
            "Daniel 4:20-33",
          ),
          b(
            "resumo",
            "Olhar para o céu",
            "Depois desse tempo, o rei ergue os olhos ao céu, recupera o entendimento e louva o Altíssimo, reconhecendo que Ele pode humilhar os que andam com orgulho.",
            "Daniel 4:34-37",
          ),
        ],
        exercises: [
          mc(
            "O que a árvore do sonho representava?",
            ["O próprio rei", "O templo", "Daniel", "A cidade de Jerusalém"],
            0,
            "Daniel 4:20-22.",
            "Daniel 4:20-22",
          ),
          fill(
            "Na ordem de cortar a árvore, deveria ficar apenas o",
            "com as raízes.",
            ["toco", "fruto", "galho mais alto"],
            0,
            "Daniel 4:15.",
            "Daniel 4:15",
          ),
          tf(
            "Daniel aconselhou o rei a praticar a justiça e ter compaixão dos pobres.",
            true,
            "Daniel 4:27.",
            "Daniel 4:27",
          ),
          order(
            "Ordene o relato.",
            ["O rei sonha com a árvore", "Daniel interpreta o sonho", "O rei se orgulha da Babilônia", "O rei ergue os olhos ao céu e louva"],
            "Daniel 4.",
            "Daniel 4:10-37",
          ),
          mc(
            "Qual é o tema central do capítulo 4?",
            ["Orgulho e humildade", "Construção de navios", "Uma batalha naval", "A colheita do trigo"],
            0,
            "Daniel 4:37.",
            "Daniel 4:37",
          ),
        ],
        takeaways: [
          "Nabucodonosor sonha com uma árvore cortada.",
          "Daniel o aconselha à justiça e à compaixão.",
          "O rei aprende a humildade e louva o Altíssimo.",
        ],
        reflection: "Em que área da sua vida a humildade faria diferença?",
      },
      {
        slug: "d2-escrita-na-parede",
        title: "A escrita na parede",
        objective: "Conhecer o banquete de Belsazar e a mensagem misteriosa.",
        references: ["Daniel 5:1-31"],
        context: "Anos depois, Belsazar governa a Babilônia e oferece um grande banquete.",
        blocks: [
          b(
            "resumo",
            "Taças do templo",
            "Durante a festa, Belsazar manda trazer as taças de ouro e prata tiradas do templo de Jerusalém, e eles bebem nelas louvando deuses de ouro e prata.",
            "Daniel 5:1-4",
          ),
          b(
            "resumo",
            "Uma mão escreve",
            "De repente, dedos de uma mão aparecem e escrevem na parede. O rei fica apavorado. Ninguém consegue ler, até que a rainha lembra de Daniel.",
            "Daniel 5:5-12",
          ),
          b(
            "resumo",
            "Contado, pesado, dividido",
            "Daniel lê: “Mene, Mene, Tequel, Parsim”. Explica: Deus contou os dias do reino; o rei foi pesado na balança e achado em falta; o reino seria dividido entre medos e persas. Naquela mesma noite, Belsazar morre e Dario, o medo, recebe o reino.",
            "Daniel 5:25-31",
          ),
        ],
        exercises: [
          mc(
            "O que Belsazar usou no banquete?",
            ["Taças tiradas do templo de Jerusalém", "Coroas de flores", "Instrumentos de Davi", "Rolos da Lei"],
            0,
            "Daniel 5:2-3.",
            "Daniel 5:2-3",
          ),
          match(
            "Associe cada palavra à explicação de Daniel.",
            [
              ["Mene", "Contado"],
              ["Tequel", "Pesado"],
              ["Parsim / Peres", "Dividido"],
            ],
            "Daniel 5:26-28.",
            "Daniel 5:26-28",
          ),
          tf(
            "Quem lembrou ao rei que Daniel poderia ler a escrita foi a rainha.",
            true,
            "Daniel 5:10-12.",
            "Daniel 5:10-12",
          ),
          fill(
            "O rei foi pesado na",
            "e achado em falta.",
            ["balança", "fornalha", "cova"],
            0,
            "Daniel 5:27.",
            "Daniel 5:27",
          ),
          mc(
            "Segundo o texto, quem recebe o reino depois de Belsazar?",
            ["Dario, o medo", "Nabucodonosor", "Antíoco", "Herodes"],
            0,
            "Daniel 5:31 (6:1 em algumas Bíblias).",
            "Daniel 5:31",
          ),
        ],
        takeaways: [
          "Belsazar usa as taças do templo numa festa.",
          "Uma mão escreve “Mene, Mene, Tequel, Parsim”.",
          "O reino babilônico chega ao fim naquela noite.",
        ],
        reflection: "Se sua semana fosse “pesada na balança”, o que você gostaria que pesasse mais?",
      },
    ],
    review: {
      slug: "daniel-u2-revisao",
      title: "Revisão: Sonhos e reis",
      intro: "Estátuas, fornalhas, árvores e uma mão misteriosa. Vamos relembrar!",
      extra: [
        order(
          "Ordene os capítulos.",
          ["Sonho da estátua", "Fornalha ardente", "Árvore cortada", "Escrita na parede"],
          "Daniel 2, 3, 4 e 5.",
          "Daniel 2-5",
        ),
        match(
          "Associe cada rei ao acontecimento.",
          [
            ["Nabucodonosor", "Sonho da estátua"],
            ["Belsazar", "Banquete com as taças do templo"],
            ["Dario, o medo", "Recebe o reino"],
          ],
          "Reis de Daniel 2-5.",
          "Daniel 2-5",
        ),
        tf(
          "Daniel atribuiu a Deus a revelação dos sonhos.",
          true,
          "Daniel 2:28-30.",
          "Daniel 2:28-30",
        ),
      ],
      takeaways: [
        "Os sonhos dos reis falam de reinos que passam.",
        "A fidelidade dos três amigos não dependia de serem livrados.",
        "Orgulho e humildade são temas fortes desses capítulos.",
      ],
    },
  },
  {
    slug: "daniel-u3-oracao-e-visoes",
    title: "Oração e visões",
    description: "A cova dos leões, a oração de Daniel e as visões de esperança.",
    scene: "palace",
    lessons: [
      {
        slug: "d3-o-decreto",
        title: "Três vezes ao dia",
        objective: "Conhecer o decreto contra a oração e a rotina de Daniel.",
        references: ["Daniel 6:1-10"],
        context: "No reinado de Dario, Daniel ocupa um alto cargo e se destaca pela integridade.",
        blocks: [
          b(
            "resumo",
            "Nenhuma falha",
            "Outros administradores procuram uma acusação contra Daniel, mas não encontram nenhuma falha, porque ele era fiel. Concluem que só poderiam acusá-lo a partir de sua fé.",
            "Daniel 6:3-5",
          ),
          b(
            "resumo",
            "Um decreto de trinta dias",
            "Eles convencem o rei a assinar um decreto: durante trinta dias, ninguém poderia fazer pedidos a nenhum deus ou pessoa, exceto ao rei. Quem desobedecesse iria para a cova dos leões.",
            "Daniel 6:6-9",
          ),
          b(
            "resumo",
            "Janelas abertas",
            "Mesmo sabendo do decreto, Daniel vai para casa e, com as janelas abertas na direção de Jerusalém, ora e dá graças a Deus três vezes por dia, como sempre fazia.",
            "Daniel 6:10",
          ),
        ],
        exercises: [
          mc(
            "Por que os administradores não encontraram acusação contra Daniel?",
            ["Ele era fiel e não tinha falhas no trabalho", "Ele era parente do rei", "Ele vivia escondido", "Ele não trabalhava"],
            0,
            "Daniel 6:4.",
            "Daniel 6:4",
          ),
          fill(
            "O decreto proibia pedidos a qualquer deus ou pessoa, exceto ao rei, por",
            "dias.",
            ["trinta", "sete", "quarenta"],
            0,
            "Daniel 6:7.",
            "Daniel 6:7",
          ),
          tf(
            "Daniel parou de orar enquanto o decreto estava valendo.",
            false,
            "Ele continuou orando três vezes ao dia, como sempre.",
            "Daniel 6:10",
          ),
          mc(
            "Em que direção ficavam as janelas abertas de Daniel?",
            ["Jerusalém", "O palácio", "O rio Eufrates", "O deserto"],
            0,
            "Daniel 6:10.",
            "Daniel 6:10",
          ),
          mc(
            "Quantas vezes por dia Daniel costumava orar?",
            ["Três", "Uma", "Sete", "Doze"],
            0,
            "Daniel 6:10.",
            "Daniel 6:10",
          ),
        ],
        takeaways: [
          "Daniel era íntegro em seu trabalho.",
          "Um decreto proíbe pedidos a qualquer um, exceto ao rei.",
          "Daniel mantém sua rotina de oração três vezes ao dia.",
        ],
        reflection: "Que rotina simples ajuda você a manter o rumo?",
      },
      {
        slug: "d3-cova-dos-leoes",
        title: "Na cova dos leões",
        objective: "Conhecer o relato de Daniel na cova dos leões.",
        references: ["Daniel 6:11-28"],
        context: "Os adversários de Daniel o encontram orando e o denunciam ao rei.",
        blocks: [
          b(
            "resumo",
            "Um rei angustiado",
            "Dario gosta de Daniel e tenta salvá-lo até o pôr do sol, mas o decreto não podia ser revogado. Daniel é lançado na cova, e o rei diz: “Que o seu Deus, a quem você serve sempre, o livre!”.",
            "Daniel 6:14-16",
          ),
          b(
            "resumo",
            "Uma noite sem dormir",
            "O rei passa a noite sem comer e sem dormir. De madrugada, corre até a cova e chama Daniel, que responde que Deus enviou seu anjo e fechou a boca dos leões.",
            "Daniel 6:18-22",
          ),
          b(
            "resumo",
            "Um novo decreto",
            "Daniel é tirado da cova sem ferimentos. O rei escreve a todos os povos reconhecendo o Deus de Daniel. O texto também narra a punição dos acusadores — um detalhe duro, típico das narrativas antigas.",
            "Daniel 6:23-27",
          ),
        ],
        exercises: [
          tf(
            "O rei Dario tentou salvar Daniel até o pôr do sol.",
            true,
            "Daniel 6:14.",
            "Daniel 6:14",
          ),
          fill(
            "Daniel diz que Deus enviou seu anjo e fechou a boca dos",
            ".",
            ["leões", "soldados", "acusadores"],
            0,
            "Daniel 6:22.",
            "Daniel 6:22",
          ),
          mc(
            "Como o rei passou a noite em que Daniel estava na cova?",
            ["Sem comer e sem dormir", "Numa festa", "Viajando", "Dormindo tranquilo"],
            0,
            "Daniel 6:18.",
            "Daniel 6:18",
          ),
          order(
            "Ordene o relato.",
            ["Daniel é denunciado", "O rei tenta salvá-lo", "Daniel é lançado na cova", "O rei corre até a cova de madrugada", "Daniel sai sem ferimentos"],
            "Daniel 6:11-23.",
            "Daniel 6:11-23",
          ),
          mc(
            "Por que o rei não podia simplesmente cancelar o decreto?",
            ["As leis dos medos e persas não podiam ser revogadas", "Daniel pediu para ir à cova", "O decreto era de Nabucodonosor", "Os leões eram do templo"],
            0,
            "Daniel 6:8, 15.",
            "Daniel 6:15",
          ),
        ],
        takeaways: [
          "Daniel é lançado na cova por ter orado.",
          "O rei passa a noite angustiado e corre até a cova.",
          "Daniel sai sem ferimentos, e o rei reconhece o Deus de Daniel.",
        ],
        reflection: "Quem foram as pessoas que torceram por você em uma noite difícil?",
      },
      {
        slug: "d3-quatro-animais",
        title: "Quatro animais e um filho de homem",
        objective: "Conhecer a visão de Daniel 7 e seus símbolos.",
        references: ["Daniel 7:1-14", "Marcos 14:61-62"],
        context: "Com o capítulo 7, o livro passa das histórias às visões. É Daniel quem sonha agora.",
        blocks: [
          b(
            "resumo",
            "Do mar agitado",
            "Daniel vê quatro animais saindo de um mar agitado: um leão com asas de águia, um urso, um leopardo com quatro asas e quatro cabeças, e um quarto animal terrível, com dentes de ferro e dez chifres.",
            "Daniel 7:2-8",
          ),
          b(
            "resumo",
            "O Ancião de Dias",
            "Tronos são colocados e um Ancião de Dias se assenta, com roupas brancas como a neve. Os animais perdem o poder.",
            "Daniel 7:9-12",
          ),
          b(
            "resumo",
            "Como um filho de homem",
            "Vem com as nuvens do céu alguém “como um filho de homem”, que recebe um reino que não será destruído.",
            "Daniel 7:13-14",
          ),
          b(
            "interpretacao",
            "Como ler os símbolos",
            "O próprio texto diz que os animais são reinos (7:17). Leitores identificam esses reinos de formas diferentes. Nos Evangelhos, Jesus usa a expressão “Filho do Homem” para se referir a si mesmo, ecoando Daniel 7 — e a tradição cristã lê o texto à luz disso.",
            "Daniel 7:17; Marcos 14:62",
          ),
        ],
        exercises: [
          match(
            "Associe cada animal à sua descrição.",
            [
              ["Primeiro", "Leão com asas de águia"],
              ["Segundo", "Urso"],
              ["Terceiro", "Leopardo com quatro asas"],
              ["Quarto", "Terrível, com dez chifres"],
            ],
            "Daniel 7:4-7.",
            "Daniel 7:4-7",
          ),
          mc(
            "De onde os animais saem na visão?",
            ["De um mar agitado", "De uma caverna", "Do deserto", "De um palácio"],
            0,
            "Daniel 7:2-3.",
            "Daniel 7:2-3",
          ),
          fill(
            "Na visão, alguém “como um filho de homem” vem com as",
            "do céu.",
            ["nuvens", "estrelas", "águias"],
            0,
            "Daniel 7:13.",
            "Daniel 7:13",
          ),
          tf(
            "O próprio texto de Daniel 7 diz que os animais representam reinos.",
            true,
            "Daniel 7:17.",
            "Daniel 7:17",
          ),
          mc(
            "Que expressão de Daniel 7 Jesus usa nos Evangelhos?",
            ["Filho do Homem", "Ancião de Dias", "Leão de Judá", "Estrela da manhã"],
            0,
            "Marcos 14:62.",
            "Marcos 14:62",
          ),
        ],
        takeaways: [
          "Daniel vê quatro animais que representam reinos.",
          "O Ancião de Dias julga e os animais perdem poder.",
          "Alguém “como um filho de homem” recebe um reino eterno.",
        ],
        reflection: "Em tempos confusos, o que ajuda você a lembrar que nem todo poder dura para sempre?",
      },
      {
        slug: "d3-oracao-de-daniel",
        title: "Uma oração de confissão",
        objective: "Conhecer a oração de Daniel em nome do povo.",
        references: ["Daniel 9:1-19", "Jeremias 29:10"],
        context: "Lendo o profeta Jeremias, Daniel entende que o exílio duraria setenta anos.",
        blocks: [
          b(
            "resumo",
            "Lendo Jeremias",
            "Daniel lê nos livros que, segundo a palavra dada a Jeremias, a desolação de Jerusalém duraria setenta anos.",
            "Daniel 9:2; Jeremias 29:10",
          ),
          b(
            "resumo",
            "Nós erramos",
            "Com jejum, pano de saco e cinza, Daniel ora reconhecendo os erros do povo — e fala em “nós”, incluindo a si mesmo.",
            "Daniel 9:3-11",
          ),
          b(
            "resumo",
            "Pela misericórdia",
            "Daniel pede que Deus ouça, não por causa da justiça do povo, mas por causa de sua grande misericórdia.",
            "Daniel 9:18-19",
          ),
        ],
        exercises: [
          mc(
            "Qual profeta Daniel estava lendo?",
            ["Jeremias", "Isaías", "Elias", "Ezequiel"],
            0,
            "Daniel 9:2.",
            "Daniel 9:2",
          ),
          fill(
            "Segundo Jeremias, a desolação de Jerusalém duraria",
            "anos.",
            ["setenta", "quarenta", "sete"],
            0,
            "Daniel 9:2; Jeremias 29:10.",
            "Daniel 9:2",
          ),
          tf(
            "Na oração, Daniel fala dos erros do povo incluindo a si mesmo (“nós”).",
            true,
            "Daniel 9:5.",
            "Daniel 9:5",
          ),
          mc(
            "Em que Daniel baseia seu pedido?",
            ["Na grande misericórdia de Deus", "Na justiça do povo", "Na força do rei", "Na beleza do templo"],
            0,
            "Daniel 9:18.",
            "Daniel 9:18",
          ),
          match(
            "Associe cada sinal à sua prática.",
            [
              ["Jejum", "Abster-se de comida"],
              ["Pano de saco e cinza", "Sinal de luto e arrependimento"],
            ],
            "Práticas antigas de oração intensa.",
            "Daniel 9:3",
          ),
        ],
        takeaways: [
          "Daniel lê Jeremias e entende o tempo do exílio.",
          "Ele confessa os erros do povo, incluindo a si mesmo.",
          "Seu pedido se apoia na misericórdia de Deus.",
        ],
        reflection: "Pedir perdão “em nome de todos” é difícil. Por que pode ser importante?",
      },
      {
        slug: "d3-esperanca-no-fim",
        title: "Brilhar como as estrelas",
        objective: "Conhecer a esperança final do livro de Daniel.",
        references: ["Daniel 12:1-4", "Daniel 12:13"],
        context: "O último capítulo do livro (na contagem protestante e hebraica) fala de um tempo de angústia — e de esperança.",
        blocks: [
          b(
            "resumo",
            "Miguel se levanta",
            "Haveria um tempo de grande angústia, mas o povo seria protegido; Miguel, apresentado como grande príncipe, se levantaria.",
            "Daniel 12:1",
          ),
          b(
            "resumo",
            "Despertar",
            "Muitos dos que dormem no pó da terra despertariam. Os sábios brilhariam como o firmamento, e os que conduzem muitos à justiça, como as estrelas, para sempre.",
            "Daniel 12:2-3",
          ),
          b(
            "contexto",
            "Um texto importante",
            "Daniel 12:2 é considerado um dos textos mais claros do Antigo Testamento sobre a ressurreição dos mortos.",
          ),
          b(
            "resumo",
            "“Siga o seu caminho”",
            "O livro termina com uma palavra pessoal a Daniel: que seguisse seu caminho até o fim, pois descansaria e se levantaria para receber sua herança.",
            "Daniel 12:13",
          ),
        ],
        exercises: [
          fill(
            "Os que conduzem muitos à justiça brilharão como as",
            ".",
            ["estrelas", "lâmpadas", "fogueiras"],
            0,
            "Daniel 12:3.",
            "Daniel 12:3",
          ),
          mc(
            "Quem é apresentado como grande príncipe em Daniel 12:1?",
            ["Miguel", "Gabriel", "Dario", "Ciro"],
            0,
            "Daniel 12:1.",
            "Daniel 12:1",
          ),
          tf(
            "Daniel 12:2 fala de muitos que dormem no pó despertando.",
            true,
            "É um texto importante sobre a ressurreição.",
            "Daniel 12:2",
          ),
          mc(
            "Com que palavra o livro termina para Daniel?",
            ["Que siga seu caminho até o fim", "Que construa um templo", "Que volte à corte", "Que escreva outro livro"],
            0,
            "Daniel 12:13.",
            "Daniel 12:13",
          ),
          order(
            "Ordene os acontecimentos de Daniel 6 a 12.",
            ["Cova dos leões", "Visão dos quatro animais", "Oração de confissão", "Esperança de despertar"],
            "Daniel 6, 7, 9 e 12.",
            "Daniel 6-12",
          ),
        ],
        takeaways: [
          "Daniel 12 fala de angústia, proteção e esperança.",
          "O texto anuncia o despertar dos que dormem no pó.",
          "O livro termina com: “siga o seu caminho”.",
        ],
        reflection: "Que caminho você quer seguir com fidelidade “até o fim”?",
      },
    ],
    review: {
      slug: "daniel-u3-revisao",
      title: "Revisão: Oração e visões",
      intro: "Da cova dos leões às estrelas. Vamos relembrar a última unidade com Daniel.",
      extra: [
        match(
          "Associe cada capítulo ao tema.",
          [
            ["Daniel 6", "Cova dos leões"],
            ["Daniel 7", "Quatro animais e o filho de homem"],
            ["Daniel 9", "Oração de confissão"],
            ["Daniel 12", "Brilhar como as estrelas"],
          ],
          "Capítulos desta unidade.",
          "Daniel 6-12",
        ),
        mc(
          "Qual hábito colocou Daniel em risco no capítulo 6?",
          ["Orar três vezes ao dia", "Comer legumes", "Interpretar sonhos", "Ler Jeremias"],
          0,
          "Daniel 6:10.",
          "Daniel 6:10",
        ),
        tf(
          "As visões de Daniel usam linguagem simbólica e têm leituras diferentes.",
          true,
          "Daniel 7:17 explica alguns símbolos; outros têm interpretações variadas.",
          "Daniel 7-12",
        ),
      ],
      takeaways: [
        "A oração constante marca a vida de Daniel.",
        "As visões falam de reinos que passam e de um reino eterno.",
        "O livro termina com esperança e um convite a seguir o caminho.",
      ],
    },
  },
];
