import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const eliasUnits: UnitDef[] = [
  {
    slug: "elias-u1-missao-e-seca",
    title: "Missão em tempo de seca",
    description: "Elias enfrenta o rei Acabe, é cuidado no deserto e desafia os profetas de Baal.",
    scene: "mountain",
    lessons: [
      {
        slug: "e1-quem-foi-elias",
        title: "Quem foi Elias?",
        objective: "Conhecer o contexto em que Elias atuou.",
        references: ["1 Reis 16:29-33", "1 Reis 17:1"],
        context:
          "Elias viveu no reino do norte (Israel), no século IX antes de Cristo. Não há um livro com seu nome: sua história está nos livros de 1 e 2 Reis.",
        blocks: [
          b(
            "contexto",
            "O rei Acabe e Jezabel",
            "Acabe reinava em Samaria e se casou com Jezabel, filha do rei de Sidom. O texto diz que ele passou a servir a Baal, construiu um templo e um altar para ele em Samaria.",
            "1 Reis 16:29-33",
          ),
          b(
            "contexto",
            "Quem era Baal?",
            "Baal era um deus cultuado pelos povos de Canaã e da Fenícia, associado à tempestade e à chuva — e, por isso, à fertilidade das colheitas.",
          ),
          b(
            "resumo",
            "Um anúncio inesperado",
            "Elias, o tesbita, de Gileade, aparece de repente diante de Acabe e anuncia que não haveria orvalho nem chuva nos anos seguintes, a não ser por sua palavra.",
            "1 Reis 17:1",
          ),
          b(
            "explicacao",
            "Um nome que é uma mensagem",
            "O nome Elias (em hebraico, Eliyahu) significa “meu Deus é o Senhor”. Num tempo em que muitos seguiam Baal, o próprio nome do profeta resumia sua missão.",
          ),
        ],
        exercises: [
          mc(
            "Em quais livros está a história de Elias?",
            ["1 e 2 Reis", "Livro de Elias", "Isaías", "Atos"],
            0,
            "Elias não tem livro próprio; aparece em 1 e 2 Reis.",
            "1 Reis 17 - 2 Reis 2",
          ),
          match(
            "Associe cada nome à sua descrição.",
            [
              ["Acabe", "Rei de Israel em Samaria"],
              ["Jezabel", "Esposa de Acabe, filha do rei de Sidom"],
              ["Baal", "Deus cananeu ligado à chuva"],
            ],
            "Personagens do contexto de Elias.",
            "1 Reis 16:29-33",
          ),
          fill(
            "O nome Elias significa “meu Deus é o",
            "”.",
            ["Senhor", "rei", "fogo"],
            0,
            "Eliyahu: “meu Deus é o Senhor”.",
            "1 Reis 17:1",
          ),
          tf(
            "Elias anunciou a Acabe que não haveria chuva nem orvalho.",
            true,
            "1 Reis 17:1.",
            "1 Reis 17:1",
          ),
          mc(
            "Por que o anúncio da seca desafiava o culto a Baal?",
            ["Baal era associado à chuva", "Baal era deus do mar", "Baal era deus da guerra apenas", "Baal era um rei"],
            0,
            "Uma seca questionava o poder atribuído a Baal sobre a chuva.",
            "1 Reis 17:1",
          ),
        ],
        takeaways: [
          "Elias atuou no reino do norte, no tempo de Acabe e Jezabel.",
          "Baal era um deus associado à chuva e à fertilidade.",
          "O nome Elias significa “meu Deus é o Senhor”.",
        ],
        reflection: "Se seu nome resumisse uma missão, qual seria?",
      },
      {
        slug: "e1-corvos-de-querite",
        title: "Os corvos de Querite",
        objective: "Conhecer como Elias foi sustentado durante a seca.",
        references: ["1 Reis 17:2-7"],
        context: "Depois do anúncio, Elias recebe a orientação de se esconder.",
        blocks: [
          b(
            "resumo",
            "Junto ao ribeiro",
            "Deus manda Elias se esconder junto ao ribeiro de Querite, a leste do Jordão. Ele beberia do ribeiro, e corvos levariam comida para ele.",
            "1 Reis 17:2-4",
          ),
          b(
            "resumo",
            "Pão e carne",
            "Os corvos levavam pão e carne de manhã e à tarde, e Elias bebia do ribeiro.",
            "1 Reis 17:6",
          ),
          b(
            "resumo",
            "O ribeiro seca",
            "Depois de algum tempo, o ribeiro secou, porque não chovia na terra. Era hora de mudar de lugar.",
            "1 Reis 17:7",
          ),
        ],
        exercises: [
          fill(
            "Elias se escondeu junto ao ribeiro de",
            ".",
            ["Querite", "Jaboque", "Cedrom"],
            0,
            "1 Reis 17:3.",
            "1 Reis 17:3",
          ),
          mc(
            "Quem levava comida para Elias no ribeiro?",
            ["Corvos", "Pombas", "Anjos", "Pastores"],
            0,
            "1 Reis 17:6.",
            "1 Reis 17:6",
          ),
          tf(
            "Os corvos levavam pão e carne de manhã e à tarde.",
            true,
            "1 Reis 17:6.",
            "1 Reis 17:6",
          ),
          mc(
            "Por que Elias teve de deixar o ribeiro?",
            ["O ribeiro secou", "Acabe o encontrou", "Os corvos foram embora", "Ele ficou doente"],
            0,
            "Sem chuva, o ribeiro secou.",
            "1 Reis 17:7",
          ),
          order(
            "Ordene os acontecimentos.",
            ["Elias anuncia a seca", "Esconde-se junto ao ribeiro", "É alimentado pelos corvos", "O ribeiro seca"],
            "1 Reis 17:1-7.",
            "1 Reis 17:1-7",
          ),
        ],
        takeaways: [
          "Elias se esconde junto ao ribeiro de Querite.",
          "É alimentado por corvos, de manhã e à tarde.",
          "Quando o ribeiro seca, uma nova etapa começa.",
        ],
        reflection: "Às vezes o “ribeiro” seca e é hora de mudar. Como você lida com mudanças assim?",
      },
      {
        slug: "e1-viuva-de-sarepta",
        title: "A viúva de Sarepta",
        objective: "Conhecer o encontro de Elias com uma viúva estrangeira.",
        references: ["1 Reis 17:8-24", "Lucas 4:25-26"],
        context: "Elias é enviado a Sarepta, cidade próxima a Sidom — terra de Jezabel e fora de Israel.",
        blocks: [
          b(
            "resumo",
            "Um punhado de farinha",
            "Elias pede água e pão a uma viúva. Ela responde que só tinha um punhado de farinha e um pouco de azeite, para uma última refeição com o filho. Elias pede que ela prepare primeiro um pão para ele e anuncia que a farinha e o azeite não acabariam até voltar a chover.",
            "1 Reis 17:10-14",
          ),
          b(
            "resumo",
            "Não acabou",
            "Ela faz o que Elias pediu, e a farinha e o azeite não acabaram, como tinha sido dito.",
            "1 Reis 17:15-16",
          ),
          b(
            "resumo",
            "O filho volta à vida",
            "Mais tarde, o filho da viúva adoece e morre. Elias o leva ao quarto de cima, clama a Deus, e o menino volta a viver. A mulher reconhece Elias como homem de Deus.",
            "1 Reis 17:17-24",
          ),
          b(
            "contexto",
            "Lembrada por Jesus",
            "No Evangelho de Lucas, Jesus lembra que Elias foi enviado a uma viúva de Sarepta, fora de Israel — um sinal de cuidado que ultrapassava fronteiras.",
            "Lucas 4:25-26",
          ),
        ],
        exercises: [
          mc(
            "Perto de qual cidade ficava Sarepta?",
            ["Sidom", "Jerusalém", "Nínive", "Belém"],
            0,
            "Sarepta pertencia a Sidom.",
            "1 Reis 17:9",
          ),
          fill(
            "A viúva tinha apenas um punhado de farinha e um pouco de",
            ".",
            ["azeite", "mel", "leite"],
            0,
            "1 Reis 17:12.",
            "1 Reis 17:12",
          ),
          tf(
            "A farinha e o azeite da viúva não acabaram durante a seca.",
            true,
            "1 Reis 17:16.",
            "1 Reis 17:16",
          ),
          mc(
            "Em qual Evangelho Jesus menciona a viúva de Sarepta?",
            ["Lucas", "Marcos", "João", "Mateus"],
            0,
            "Lucas 4:25-26.",
            "Lucas 4:25-26",
          ),
          order(
            "Ordene o relato.",
            ["Elias pede pão à viúva", "A farinha e o azeite não acabam", "O filho da viúva morre", "Elias ora e o menino volta a viver"],
            "1 Reis 17:10-23.",
            "1 Reis 17:10-23",
          ),
        ],
        takeaways: [
          "Elias é acolhido por uma viúva estrangeira em Sarepta.",
          "A farinha e o azeite não acabam durante a seca.",
          "O filho da viúva volta à vida após a oração de Elias.",
        ],
        reflection: "A viúva partilhou o pouco que tinha. O que isso inspira em você?",
      },
      {
        slug: "e1-monte-carmelo",
        title: "O desafio no monte Carmelo",
        objective: "Conhecer o confronto entre Elias e os profetas de Baal.",
        references: ["1 Reis 18:17-40"],
        context: "No terceiro ano da seca, Elias se apresenta a Acabe e propõe um desafio público no monte Carmelo.",
        blocks: [
          b(
            "resumo",
            "Até quando?",
            "Diante do povo, Elias pergunta: até quando vocês vão hesitar entre duas opiniões? Se o Senhor é Deus, sigam-no; se é Baal, sigam a Baal. O povo fica em silêncio.",
            "1 Reis 18:21",
          ),
          b(
            "resumo",
            "Dois altares",
            "Os 450 profetas de Baal preparam um sacrifício e clamam o dia inteiro, sem resposta. Elias reconstrói o altar do Senhor com doze pedras, uma para cada tribo, e manda encharcar tudo de água três vezes.",
            "1 Reis 18:22-35",
          ),
          b(
            "resumo",
            "O fogo",
            "Elias ora, e cai fogo que consome o sacrifício, a lenha, as pedras e a água. O povo se prostra e diz: “O Senhor é Deus!”. O relato termina com a morte dos profetas de Baal — uma parte violenta do texto que leitores hoje interpretam à luz de seu contexto antigo.",
            "1 Reis 18:36-40",
          ),
        ],
        exercises: [
          mc(
            "Quantos profetas de Baal estavam no Carmelo?",
            ["450", "12", "7000", "40"],
            0,
            "1 Reis 18:22.",
            "1 Reis 18:22",
          ),
          fill(
            "Elias perguntou ao povo até quando hesitariam entre duas",
            ".",
            ["opiniões", "cidades", "montanhas"],
            0,
            "1 Reis 18:21.",
            "1 Reis 18:21",
          ),
          mc(
            "Quantas pedras Elias usou no altar?",
            ["Doze, uma para cada tribo", "Sete", "Três", "Quarenta"],
            0,
            "1 Reis 18:31.",
            "1 Reis 18:31",
          ),
          tf(
            "Elias mandou derramar água sobre o altar antes de orar.",
            true,
            "A água foi derramada três vezes.",
            "1 Reis 18:33-35",
          ),
          order(
            "Ordene o desafio.",
            ["Elias desafia o povo a decidir", "Os profetas de Baal clamam sem resposta", "Elias reconstrói o altar e o encharca", "Cai fogo do céu"],
            "1 Reis 18:21-38.",
            "1 Reis 18:21-38",
          ),
        ],
        takeaways: [
          "No Carmelo, Elias pede que o povo decida a quem seguir.",
          "Os profetas de Baal não recebem resposta; o altar de Elias é consumido pelo fogo.",
          "O relato tem partes violentas que pedem leitura atenta ao contexto.",
        ],
        reflection: "Em que área da vida você sente que está “hesitando entre duas opiniões”?",
      },
      {
        slug: "e1-a-chuva-volta",
        title: "A chuva volta",
        objective: "Conhecer o fim da seca e a perseverança de Elias na oração.",
        references: ["1 Reis 18:41-46", "Tiago 5:17-18"],
        context: "Depois do Carmelo, Elias anuncia a Acabe que vem chuva — mas o céu ainda está limpo.",
        blocks: [
          b(
            "resumo",
            "Sete vezes",
            "Elias sobe ao alto do Carmelo, se curva até o chão com o rosto entre os joelhos e pede ao servo que olhe para o mar. Seis vezes o servo diz que não há nada. Na sétima, ele vê uma nuvem pequena como a mão de um homem.",
            "1 Reis 18:42-44",
          ),
          b(
            "resumo",
            "Correndo à frente",
            "O céu escurece e cai uma grande chuva. Elias corre à frente da carruagem de Acabe até a entrada de Jezreel.",
            "1 Reis 18:45-46",
          ),
          b(
            "resumo",
            "Um homem como nós",
            "A carta de Tiago lembra Elias como alguém “semelhante a nós”, cuja oração foi ouvida — sobre a falta de chuva e sobre a chuva que voltou.",
            "Tiago 5:17-18",
          ),
        ],
        exercises: [
          mc(
            "Quantas vezes o servo foi olhar para o mar?",
            ["Sete", "Três", "Doze", "Uma"],
            0,
            "Na sétima vez, ele viu uma pequena nuvem.",
            "1 Reis 18:43-44",
          ),
          fill(
            "A nuvem era pequena como a",
            "de um homem.",
            ["mão", "cabeça", "sandália"],
            0,
            "1 Reis 18:44.",
            "1 Reis 18:44",
          ),
          tf(
            "Elias correu à frente da carruagem de Acabe até Jezreel.",
            true,
            "1 Reis 18:46.",
            "1 Reis 18:46",
          ),
          mc(
            "Qual carta do Novo Testamento chama Elias de “semelhante a nós”?",
            ["Tiago", "Romanos", "Hebreus", "1 Pedro"],
            0,
            "Tiago 5:17.",
            "Tiago 5:17",
          ),
          match(
            "Associe cada elemento ao que representa no relato.",
            [
              ["Pequena nuvem", "Sinal de que a chuva viria"],
              ["Sete vezes", "Perseverança na espera"],
              ["Jezreel", "Destino da corrida de Elias"],
            ],
            "Detalhes do fim da seca.",
            "1 Reis 18:43-46",
          ),
        ],
        takeaways: [
          "Elias ora e espera até ver uma pequena nuvem.",
          "A chuva volta depois de anos de seca.",
          "Tiago lembra Elias como alguém “semelhante a nós”.",
        ],
        reflection: "O que você tem esperado, olhando “sete vezes” para o horizonte?",
      },
    ],
    review: {
      slug: "elias-u1-revisao",
      title: "Revisão: Missão em tempo de seca",
      intro: "Do anúncio da seca à chuva no Carmelo. Vamos relembrar!",
      extra: [
        order(
          "Ordene a jornada de Elias nesta unidade.",
          ["Anúncio a Acabe", "Ribeiro de Querite", "Viúva de Sarepta", "Monte Carmelo", "Volta da chuva"],
          "1 Reis 17-18.",
          "1 Reis 17-18",
        ),
        match(
          "Associe cada lugar ao que aconteceu.",
          [
            ["Querite", "Corvos traziam comida"],
            ["Sarepta", "Farinha e azeite não acabaram"],
            ["Carmelo", "Fogo sobre o altar"],
          ],
          "Lugares de 1 Reis 17-18.",
          "1 Reis 17-18",
        ),
        tf(
          "Elias foi enviado a uma viúva estrangeira durante a seca.",
          true,
          "Sarepta ficava perto de Sidom, fora de Israel.",
          "1 Reis 17:9",
        ),
      ],
      takeaways: [
        "Elias anuncia a seca num tempo de culto a Baal.",
        "É sustentado no deserto e em Sarepta.",
        "No Carmelo e na volta da chuva, a confiança e a oração estão no centro.",
      ],
    },
  },
  {
    slug: "elias-u2-crise-e-recomeco",
    title: "Crise e recomeço",
    description: "Cansaço, fuga, um murmúrio suave e a coragem de denunciar injustiças.",
    scene: "desert",
    lessons: [
      {
        slug: "e2-fuga-para-o-deserto",
        title: "Cansado no deserto",
        objective: "Conhecer a crise de Elias depois do Carmelo.",
        references: ["1 Reis 19:1-8"],
        context: "Depois do Carmelo, era de esperar que Elias estivesse confiante. Mas o texto mostra o contrário.",
        blocks: [
          b(
            "resumo",
            "Medo e fuga",
            "Jezabel ameaça matar Elias. Ele foge para Berseba, no sul, e segue sozinho para o deserto.",
            "1 Reis 19:1-4",
          ),
          b(
            "resumo",
            "“Basta”",
            "Sentado debaixo de um arbusto, Elias diz que já basta e pede para morrer. Depois, adormece.",
            "1 Reis 19:4-5",
          ),
          b(
            "resumo",
            "Pão, água e descanso",
            "Um anjo o toca e diz: “Levante-se e coma”. Ao lado há pão e uma jarra de água. Elias come, dorme de novo, e o anjo volta a alimentá-lo, porque o caminho seria longo. Com essa força, ele anda quarenta dias e quarenta noites até o Horebe.",
            "1 Reis 19:5-8",
          ),
          b(
            "explicacao",
            "Cuidado antes de qualquer cobrança",
            "No relato, a primeira resposta ao esgotamento de Elias é comida, água e sono — não uma bronca. Se você estiver se sentindo assim, conversar com alguém de confiança ou com um profissional de saúde também é cuidado.",
          ),
        ],
        exercises: [
          mc(
            "Quem ameaçou Elias depois do Carmelo?",
            ["Jezabel", "Acabe", "Obadias", "Eliseu"],
            0,
            "1 Reis 19:2.",
            "1 Reis 19:2",
          ),
          tf(
            "Elias se sentiu confiante e animado logo depois do Carmelo.",
            false,
            "Ele teve medo, fugiu e pediu para morrer.",
            "1 Reis 19:3-4",
          ),
          fill(
            "O anjo disse a Elias: “Levante-se e",
            "”.",
            ["coma", "lute", "corra"],
            0,
            "1 Reis 19:5.",
            "1 Reis 19:5",
          ),
          mc(
            "Quanto tempo Elias caminhou até o Horebe?",
            ["Quarenta dias e quarenta noites", "Três dias", "Sete anos", "Um mês"],
            0,
            "1 Reis 19:8.",
            "1 Reis 19:8",
          ),
          order(
            "Ordene o relato.",
            ["Jezabel ameaça Elias", "Elias foge para o deserto", "Pede para morrer e adormece", "O anjo o alimenta", "Ele caminha até o Horebe"],
            "1 Reis 19:1-8.",
            "1 Reis 19:1-8",
          ),
        ],
        takeaways: [
          "Depois de uma grande vitória, Elias vive medo e esgotamento.",
          "O cuidado chega como pão, água e descanso.",
          "Fortalecido, ele caminha até o Horebe.",
        ],
        reflection: "Do que você precisa quando está esgotado: descanso, comida, conversa?",
      },
      {
        slug: "e2-murmurio-suave",
        title: "Um murmúrio suave",
        objective: "Conhecer o encontro de Elias com Deus no monte Horebe.",
        references: ["1 Reis 19:9-18"],
        context: "No Horebe — o mesmo monte do Sinai, ligado a Moisés —, Elias entra numa caverna.",
        blocks: [
          b(
            "resumo",
            "“Que fazes aqui?”",
            "Deus pergunta: “Que fazes aqui, Elias?”. Ele responde que tem sido zeloso, mas que o povo abandonou a aliança e que só ele restou.",
            "1 Reis 19:9-10",
          ),
          b(
            "resumo",
            "Vento, terremoto, fogo",
            "Passa um vento fortíssimo, mas Deus não estava no vento. Depois, um terremoto, mas Deus não estava no terremoto. Depois, fogo, mas Deus não estava no fogo. Por fim, vem um murmúrio suave — e Elias cobre o rosto com o manto.",
            "1 Reis 19:11-13",
          ),
          b(
            "resumo",
            "Você não está sozinho",
            "Deus envia Elias de volta com novas tarefas, incluindo ungir Eliseu como profeta, e diz que ainda havia sete mil em Israel que não tinham se dobrado a Baal.",
            "1 Reis 19:15-18",
          ),
          b(
            "explicacao",
            "Traduções diferentes",
            "A expressão hebraica é difícil de traduzir. Bíblias em português trazem “cicio tranquilo e suave”, “murmúrio de uma brisa suave” ou “som de silêncio”.",
          ),
        ],
        exercises: [
          fill(
            "Deus pergunta: “Que fazes",
            ", Elias?”",
            ["aqui", "agora", "lá fora"],
            0,
            "1 Reis 19:9.",
            "1 Reis 19:9",
          ),
          order(
            "Ordene o que passou diante da caverna.",
            ["Vento forte", "Terremoto", "Fogo", "Murmúrio suave"],
            "1 Reis 19:11-12.",
            "1 Reis 19:11-12",
          ),
          tf(
            "Segundo o texto, Deus estava no vento, no terremoto e no fogo.",
            false,
            "O texto repete que Deus não estava neles.",
            "1 Reis 19:11-12",
          ),
          mc(
            "Quantos em Israel não tinham se dobrado a Baal, segundo Deus?",
            ["Sete mil", "Doze", "Quatrocentos e cinquenta", "Só Elias"],
            0,
            "1 Reis 19:18.",
            "1 Reis 19:18",
          ),
          mc(
            "O monte Horebe também é ligado a qual personagem?",
            ["Moisés", "Davi", "Daniel", "Paulo"],
            0,
            "Horebe é outro nome do Sinai, onde Moisés recebeu a lei.",
            "Êxodo 3:1; 1 Reis 19:8",
          ),
        ],
        takeaways: [
          "No Horebe, Deus pergunta a Elias: “Que fazes aqui?”.",
          "Deus não está no vento, no terremoto ou no fogo, mas num murmúrio suave.",
          "Elias descobre que não está sozinho e recebe novas tarefas.",
        ],
        reflection: "Onde você costuma encontrar silêncio no seu dia?",
      },
      {
        slug: "e2-vinha-de-nabote",
        title: "A vinha de Nabote",
        objective: "Conhecer como Elias denunciou uma injustiça do rei.",
        references: ["1 Reis 21:1-29"],
        context: "Os profetas não falavam só de culto: também denunciavam abusos de poder.",
        blocks: [
          b(
            "resumo",
            "“Herança de meus pais”",
            "Acabe quer a vinha de Nabote, vizinha ao palácio. Nabote se recusa a vendê-la, porque era herança de seus antepassados. Acabe fica emburrado.",
            "1 Reis 21:1-4",
          ),
          b(
            "resumo",
            "Um julgamento falso",
            "Jezabel escreve cartas em nome do rei, arranja testemunhas falsas, e Nabote é acusado injustamente e morto. Acabe toma posse da vinha.",
            "1 Reis 21:5-16",
          ),
          b(
            "resumo",
            "O profeta aparece",
            "Elias vai até Acabe na vinha e denuncia o crime. Acabe se humilha diante da denúncia, e o texto registra isso.",
            "1 Reis 21:17-29",
          ),
        ],
        exercises: [
          mc(
            "Por que Nabote não quis vender a vinha?",
            ["Era herança de seus antepassados", "Ela não valia nada", "Já tinha vendido a outro", "Queria um preço alto"],
            0,
            "1 Reis 21:3.",
            "1 Reis 21:3",
          ),
          match(
            "Associe cada pessoa ao que fez.",
            [
              ["Acabe", "Desejou a vinha"],
              ["Jezabel", "Arranjou testemunhas falsas"],
              ["Elias", "Denunciou o crime"],
            ],
            "1 Reis 21.",
            "1 Reis 21",
          ),
          tf(
            "Nabote recebeu um julgamento justo.",
            false,
            "Ele foi acusado por testemunhas falsas.",
            "1 Reis 21:10-13",
          ),
          fill(
            "Jezabel escreveu cartas em nome do",
            ".",
            ["rei", "profeta", "sacerdote"],
            0,
            "1 Reis 21:8.",
            "1 Reis 21:8",
          ),
          mc(
            "Qual é um tema central desta história?",
            ["Abuso de poder e justiça", "Construção do templo", "Viagens missionárias", "Criação do mundo"],
            0,
            "O relato denuncia o abuso de poder do rei.",
            "1 Reis 21",
          ),
        ],
        takeaways: [
          "Acabe deseja a vinha de Nabote, que se recusa a vendê-la.",
          "Jezabel arma um julgamento falso.",
          "Elias denuncia o abuso de poder.",
        ],
        reflection: "Que injustiças “pequenas” ao seu redor pedem que alguém fale?",
      },
      {
        slug: "e2-acazias",
        title: "Elias e o rei Acazias",
        objective: "Conhecer o último confronto de Elias com um rei.",
        references: ["2 Reis 1:1-17"],
        context: "Acazias, filho de Acabe, se fere ao cair de uma janela do andar de cima em Samaria.",
        blocks: [
          b(
            "resumo",
            "Consultar outro deus",
            "Ferido, Acazias manda mensageiros consultar Baal-Zebube, deus da cidade filisteia de Ecrom, para saber se ficaria curado.",
            "2 Reis 1:2",
          ),
          b(
            "resumo",
            "“Não há Deus em Israel?”",
            "Elias vai ao encontro dos mensageiros e pergunta se não havia Deus em Israel para que fossem consultar o deus de Ecrom. Os mensageiros voltam e descrevem um homem vestido de pelos, com um cinto de couro. O rei reconhece: é Elias.",
            "2 Reis 1:3-8",
          ),
          b(
            "contexto",
            "Um visual marcante",
            "A roupa de pelos e o cinto de couro ficaram ligados à imagem do profeta. Séculos depois, João Batista é descrito de modo parecido — e os Evangelhos o relacionam a Elias.",
            "2 Reis 1:8; Marcos 1:6",
          ),
        ],
        exercises: [
          mc(
            "Quem Acazias mandou consultar?",
            ["Baal-Zebube, deus de Ecrom", "O profeta Elias", "Os sacerdotes de Jerusalém", "Os magos do Egito"],
            0,
            "2 Reis 1:2.",
            "2 Reis 1:2",
          ),
          fill(
            "Elias pergunta: “Não há",
            "em Israel?”",
            ["Deus", "rei", "água"],
            0,
            "2 Reis 1:3.",
            "2 Reis 1:3",
          ),
          tf(
            "Os mensageiros descreveram Elias como um homem vestido de pelos, com cinto de couro.",
            true,
            "2 Reis 1:8.",
            "2 Reis 1:8",
          ),
          mc(
            "Quem, nos Evangelhos, é descrito com roupa e cinto parecidos com os de Elias?",
            ["João Batista", "Pedro", "Judas", "Pilatos"],
            0,
            "Marcos 1:6.",
            "Marcos 1:6",
          ),
          match(
            "Associe cada nome.",
            [
              ["Acazias", "Rei, filho de Acabe"],
              ["Ecrom", "Cidade filisteia"],
              ["Samaria", "Capital onde o rei caiu"],
            ],
            "2 Reis 1.",
            "2 Reis 1:1-2",
          ),
        ],
        takeaways: [
          "Acazias busca ajuda no deus de Ecrom.",
          "Elias pergunta se não havia Deus em Israel.",
          "A imagem de Elias, com pelos e cinto de couro, lembra João Batista.",
        ],
        reflection: "Onde você costuma buscar respostas quando está com medo?",
      },
      {
        slug: "e2-elias-lembrado",
        title: "Elias lembrado depois",
        objective: "Ver como Elias é lembrado em Malaquias, nos Evangelhos e na tradição judaica.",
        references: ["Malaquias 4:5-6", "Mateus 17:1-13", "Marcos 9:2-8", "Lucas 1:17"],
        context: "Elias se tornou uma figura de esperança muito depois de sua época.",
        blocks: [
          b(
            "resumo",
            "Em Malaquias",
            "O último livro dos profetas no Antigo Testamento cristão anuncia que Elias seria enviado antes do “grande dia do Senhor”, para reconciliar pais e filhos.",
            "Malaquias 4:5-6",
          ),
          b(
            "tradicoes",
            "A numeração muda",
            "Esse trecho é Malaquias 4:5-6 em muitas Bíblias protestantes e Malaquias 3:23-24 em Bíblias católicas e na Bíblia Hebraica. O texto é o mesmo; muda só a divisão dos capítulos.",
          ),
          b(
            "resumo",
            "Nos Evangelhos",
            "Na transfiguração, Moisés e Elias aparecem conversando com Jesus. Os Evangelhos também relacionam João Batista a Elias: Lucas diz que João viria “no espírito e poder de Elias”.",
            "Marcos 9:4; Lucas 1:17; Mateus 17:10-13",
          ),
          b(
            "contexto",
            "Na tradição judaica",
            "Na ceia judaica de Páscoa, muitas famílias reservam uma taça para Elias e abrem a porta para ele, como sinal de esperança.",
          ),
        ],
        exercises: [
          mc(
            "Quem aparece com Jesus na transfiguração?",
            ["Moisés e Elias", "Abraão e Davi", "Isaías e Daniel", "Pedro e Paulo"],
            0,
            "Marcos 9:4.",
            "Marcos 9:4",
          ),
          tf(
            "O anúncio sobre Elias em Malaquias tem números diferentes em Bíblias católicas e protestantes.",
            true,
            "Malaquias 4:5-6 (protestantes) ou 3:23-24 (católicas e Bíblia Hebraica).",
            "Malaquias 4:5-6 / 3:23-24",
          ),
          fill(
            "Lucas diz que João Batista viria no espírito e poder de",
            ".",
            ["Elias", "Moisés", "Davi"],
            0,
            "Lucas 1:17.",
            "Lucas 1:17",
          ),
          mc(
            "Que gesto de esperança é feito para Elias em muitas ceias judaicas de Páscoa?",
            ["Reservar uma taça e abrir a porta", "Acender uma fogueira no monte", "Jejuar quarenta dias", "Construir um altar de pedras"],
            0,
            "A taça de Elias é uma tradição da ceia pascal judaica.",
            "Tradição judaica",
          ),
          match(
            "Associe cada texto ao que diz sobre Elias.",
            [
              ["Malaquias", "Elias seria enviado antes do grande dia"],
              ["Marcos 9", "Aparece na transfiguração"],
              ["Tiago 5", "Homem semelhante a nós"],
            ],
            "Elias em diferentes textos.",
            "Malaquias 4:5; Marcos 9:4; Tiago 5:17",
          ),
        ],
        takeaways: [
          "Malaquias anuncia o envio de Elias.",
          "Os Evangelhos ligam Elias à transfiguração e a João Batista.",
          "Na tradição judaica, Elias é símbolo de esperança.",
        ],
        reflection: "Que pessoa do passado inspira esperança em você?",
      },
    ],
    review: {
      slug: "elias-u2-revisao",
      title: "Revisão: Crise e recomeço",
      intro: "Cansaço, silêncio e coragem. Vamos relembrar esta unidade.",
      extra: [
        order(
          "Ordene os acontecimentos.",
          ["Fuga para o deserto", "Encontro no Horebe", "Vinha de Nabote", "Mensageiros de Acazias"],
          "1 Reis 19; 21; 2 Reis 1.",
          "1 Reis 19 - 2 Reis 1",
        ),
        match(
          "Associe cada lugar ao acontecimento.",
          [
            ["Berseba e o deserto", "Elias pede para morrer"],
            ["Horebe", "Murmúrio suave"],
            ["Jezreel", "Vinha de Nabote"],
          ],
          "Lugares da unidade.",
          "1 Reis 19; 21",
        ),
        tf(
          "A primeira resposta ao esgotamento de Elias foi comida, água e descanso.",
          true,
          "1 Reis 19:5-8.",
          "1 Reis 19:5-8",
        ),
      ],
      takeaways: [
        "Elias vive medo e cansaço, e é cuidado.",
        "No Horebe, Deus fala num murmúrio suave.",
        "Elias denuncia injustiças e é lembrado como sinal de esperança.",
      ],
    },
  },
  {
    slug: "elias-u3-elias-e-eliseu",
    title: "Elias e Eliseu",
    description: "O chamado de Eliseu, a despedida de Elias e a continuação da missão.",
    scene: "river",
    lessons: [
      {
        slug: "e3-chamado-de-eliseu",
        title: "O manto sobre Eliseu",
        objective: "Conhecer como Eliseu foi chamado para seguir Elias.",
        references: ["1 Reis 19:19-21"],
        context: "No Horebe, Elias recebeu a orientação de ungir Eliseu. Ele o encontra trabalhando no campo.",
        blocks: [
          b(
            "resumo",
            "Doze juntas de bois",
            "Eliseu estava arando com doze juntas de bois. Elias passa por ele e lança seu manto sobre ele — um gesto de chamado.",
            "1 Reis 19:19",
          ),
          b(
            "resumo",
            "Despedida e festa",
            "Eliseu pede para se despedir dos pais. Depois, oferece os bois, usa a madeira do arado para cozinhar a carne e a reparte com o povo. Então segue Elias e passa a servi-lo.",
            "1 Reis 19:20-21",
          ),
          b(
            "explicacao",
            "O manto",
            "O manto é um objeto importante nessa história: aparece no chamado, na travessia do Jordão e na despedida de Elias.",
            "1 Reis 19:19; 2 Reis 2:8, 13",
          ),
        ],
        exercises: [
          mc(
            "O que Eliseu estava fazendo quando foi chamado?",
            ["Arando a terra com bois", "Pescando", "Pastoreando ovelhas", "Construindo um altar"],
            0,
            "1 Reis 19:19.",
            "1 Reis 19:19",
          ),
          fill(
            "Elias lançou seu",
            "sobre Eliseu.",
            ["manto", "cajado", "anel"],
            0,
            "1 Reis 19:19.",
            "1 Reis 19:19",
          ),
          tf(
            "Antes de seguir Elias, Eliseu pediu para se despedir dos pais.",
            true,
            "1 Reis 19:20.",
            "1 Reis 19:20",
          ),
          order(
            "Ordene o chamado de Eliseu.",
            ["Eliseu ara com os bois", "Elias lança o manto", "Eliseu se despede dos pais", "Reparte a carne com o povo", "Segue Elias"],
            "1 Reis 19:19-21.",
            "1 Reis 19:19-21",
          ),
          mc(
            "O que Eliseu fez com a madeira do arado?",
            ["Usou para cozinhar a carne dos bois", "Fez um barco", "Construiu uma casa", "Guardou como lembrança"],
            0,
            "1 Reis 19:21.",
            "1 Reis 19:21",
          ),
        ],
        takeaways: [
          "Eliseu é chamado enquanto trabalhava no campo.",
          "O manto lançado sobre ele é sinal do chamado.",
          "Eliseu se despede, partilha uma refeição e segue Elias.",
        ],
        reflection: "Eliseu fez uma festa ao começar algo novo. Como você marca seus começos?",
      },
      {
        slug: "e3-caminhada-final",
        title: "“Não te deixarei”",
        objective: "Acompanhar a última caminhada de Elias com Eliseu.",
        references: ["2 Reis 2:1-10"],
        context: "Chega o dia em que Elias seria levado. Ele e Eliseu fazem uma caminhada por vários lugares.",
        blocks: [
          b(
            "resumo",
            "De Gilgal ao Jordão",
            "Elias pede que Eliseu fique para trás, mas Eliseu responde três vezes que não o deixaria. Eles passam por Betel e Jericó até chegar ao rio Jordão. Grupos de discípulos dos profetas os acompanham de longe.",
            "2 Reis 2:1-7",
          ),
          b(
            "resumo",
            "O manto no rio",
            "Elias enrola o manto e bate nas águas do Jordão, que se dividem. Os dois atravessam em terra seca.",
            "2 Reis 2:8",
          ),
          b(
            "resumo",
            "Porção dobrada",
            "Elias pergunta o que Eliseu queria antes da despedida. Eliseu pede uma porção dobrada do espírito de Elias — no costume da época, a porção dobrada era a herança do filho mais velho.",
            "2 Reis 2:9-10",
          ),
        ],
        exercises: [
          mc(
            "Quantas vezes Eliseu diz que não deixaria Elias?",
            ["Três", "Uma", "Sete", "Doze"],
            0,
            "Em Gilgal, Betel e Jericó.",
            "2 Reis 2:2, 4, 6",
          ),
          order(
            "Ordene os lugares da caminhada.",
            ["Gilgal", "Betel", "Jericó", "Rio Jordão"],
            "2 Reis 2:1-7.",
            "2 Reis 2:1-7",
          ),
          fill(
            "Eliseu pediu uma porção",
            "do espírito de Elias.",
            ["dobrada", "pequena", "secreta"],
            0,
            "2 Reis 2:9.",
            "2 Reis 2:9",
          ),
          tf(
            "Elias dividiu as águas do Jordão batendo nelas com o manto.",
            true,
            "2 Reis 2:8.",
            "2 Reis 2:8",
          ),
          mc(
            "Que outro personagem também atravessou águas em terra seca, em Êxodo?",
            ["Moisés, com o povo, no mar", "Davi, no Nilo", "Pedro, no lago", "Jonas, no Mediterrâneo"],
            0,
            "Êxodo 14 narra a travessia do mar.",
            "Êxodo 14:22; 2 Reis 2:8",
          ),
        ],
        takeaways: [
          "Eliseu insiste em acompanhar Elias até o fim.",
          "Elias divide as águas do Jordão com o manto.",
          "Eliseu pede uma porção dobrada do espírito de Elias.",
        ],
        reflection: "Quem você quer acompanhar de perto, mesmo quando é difícil?",
      },
      {
        slug: "e3-carro-de-fogo",
        title: "O carro de fogo",
        objective: "Conhecer o relato da partida de Elias.",
        references: ["2 Reis 2:11-14"],
        context: "Este é um dos relatos mais famosos sobre Elias.",
        blocks: [
          b(
            "resumo",
            "Num redemoinho",
            "Enquanto conversavam, surge um carro de fogo com cavalos de fogo, que separa os dois. Elias sobe ao céu num redemoinho.",
            "2 Reis 2:11",
          ),
          b(
            "resumo",
            "“Meu pai, meu pai!”",
            "Eliseu vê e grita: “Meu pai, meu pai! Carros de Israel e seus cavaleiros!”. Depois, rasga suas roupas em sinal de luto.",
            "2 Reis 2:12",
          ),
          b(
            "resumo",
            "“Onde está o Deus de Elias?”",
            "Eliseu pega o manto que tinha caído de Elias, volta ao Jordão, bate nas águas e pergunta: “Onde está o Senhor, o Deus de Elias?”. As águas se dividem, e ele atravessa.",
            "2 Reis 2:13-14",
          ),
        ],
        exercises: [
          mc(
            "Como Elias sobe ao céu?",
            ["Num redemoinho", "Numa escada", "Num barco", "Numa nuvem de gafanhotos"],
            0,
            "2 Reis 2:11. O carro de fogo os separa, e Elias sobe num redemoinho.",
            "2 Reis 2:11",
          ),
          fill(
            "Eliseu gritou: “Meu pai, meu",
            "!”",
            ["pai", "rei", "mestre"],
            0,
            "2 Reis 2:12.",
            "2 Reis 2:12",
          ),
          tf(
            "Eliseu pegou o manto de Elias e dividiu as águas do Jordão.",
            true,
            "2 Reis 2:13-14.",
            "2 Reis 2:13-14",
          ),
          mc(
            "O que Eliseu fez com as próprias roupas ao ver Elias partir?",
            ["Rasgou em sinal de luto", "Deu aos pobres", "Lavou no rio", "Queimou no altar"],
            0,
            "2 Reis 2:12.",
            "2 Reis 2:12",
          ),
          order(
            "Ordene o relato.",
            ["Aparece um carro de fogo", "Elias sobe num redemoinho", "Eliseu rasga as roupas", "Eliseu divide as águas com o manto"],
            "2 Reis 2:11-14.",
            "2 Reis 2:11-14",
          ),
        ],
        takeaways: [
          "Um carro de fogo separa os dois, e Elias sobe num redemoinho.",
          "Eliseu chora a partida do mestre.",
          "Com o manto de Elias, Eliseu divide o Jordão.",
        ],
        reflection: "O que você gostaria de herdar de alguém que admira?",
      },
      {
        slug: "e3-eliseu-continua",
        title: "Eliseu continua a missão",
        objective: "Conhecer os primeiros sinais de Eliseu depois de Elias.",
        references: ["2 Reis 2:15-22", "2 Reis 4:1-7"],
        context: "Agora sem Elias, Eliseu começa sua própria atuação como profeta.",
        blocks: [
          b(
            "resumo",
            "Reconhecido",
            "Os discípulos dos profetas em Jericó dizem que o espírito de Elias repousa sobre Eliseu. Mesmo assim, insistem em procurar Elias por três dias, sem encontrá-lo.",
            "2 Reis 2:15-18",
          ),
          b(
            "resumo",
            "Águas curadas",
            "Em Jericó, a água era ruim. Eliseu pede uma vasilha nova com sal, lança o sal na fonte, e a água fica boa.",
            "2 Reis 2:19-22",
          ),
          b(
            "resumo",
            "O azeite da viúva",
            "Uma viúva endividada pede ajuda: os credores queriam levar seus filhos como escravos. Eliseu pede que ela junte vasilhas emprestadas. O pouco azeite que ela tinha enche todas, e ela paga a dívida.",
            "2 Reis 4:1-7",
          ),
        ],
        exercises: [
          mc(
            "O que os discípulos dos profetas reconhecem em Eliseu?",
            ["Que o espírito de Elias repousava sobre ele", "Que ele seria rei", "Que era sacerdote", "Que vinha do Egito"],
            0,
            "2 Reis 2:15.",
            "2 Reis 2:15",
          ),
          fill(
            "Eliseu curou a água de Jericó lançando",
            "na fonte.",
            ["sal", "farinha", "óleo"],
            0,
            "2 Reis 2:20-21.",
            "2 Reis 2:20-21",
          ),
          tf(
            "O azeite da viúva encheu todas as vasilhas que ela juntou.",
            true,
            "2 Reis 4:6.",
            "2 Reis 4:6",
          ),
          match(
            "Associe cada sinal ao problema resolvido.",
            [
              ["Sal na fonte", "Água ruim em Jericó"],
              ["Azeite nas vasilhas", "Dívida da viúva"],
            ],
            "2 Reis 2; 4.",
            "2 Reis 2:19-22; 4:1-7",
          ),
          mc(
            "De qual profeta anterior este relato do azeite lembra uma história parecida?",
            ["Elias, com a viúva de Sarepta", "Moisés, com o maná", "Isaías, no templo", "Jonas, em Nínive"],
            0,
            "Elias também ajudou uma viúva com azeite que não acabava.",
            "1 Reis 17:14-16; 2 Reis 4:1-7",
          ),
        ],
        takeaways: [
          "Eliseu é reconhecido como sucessor de Elias.",
          "Ele cura a água de Jericó.",
          "O azeite da viúva enche as vasilhas e paga a dívida.",
        ],
        reflection: "Eliseu continuou o que outro começou. Que projeto bom você poderia continuar?",
      },
      {
        slug: "e3-naama",
        title: "Naamã no rio Jordão",
        objective: "Conhecer a cura de Naamã, um comandante estrangeiro.",
        references: ["2 Reis 5:1-19", "Lucas 4:27"],
        context: "Naamã era comandante do exército da Síria (Arã), respeitado, mas doente de lepra — termo que, na Bíblia, abrange várias doenças de pele.",
        blocks: [
          b(
            "resumo",
            "Uma menina corajosa",
            "Uma menina israelita, levada como prisioneira, servia à esposa de Naamã. Ela diz que um profeta em Samaria poderia curá-lo.",
            "2 Reis 5:2-3",
          ),
          b(
            "resumo",
            "Sete vezes no Jordão",
            "Eliseu nem sai para recebê-lo: manda dizer que ele se lave sete vezes no Jordão. Naamã fica irritado — os rios de Damasco não seriam melhores? Seus servos o convencem a tentar algo simples.",
            "2 Reis 5:9-13",
          ),
          b(
            "resumo",
            "Como a pele de uma criança",
            "Naamã mergulha sete vezes, e sua pele fica como a de uma criança. Jesus lembra essa história em Nazaré.",
            "2 Reis 5:14; Lucas 4:27",
          ),
        ],
        exercises: [
          mc(
            "Quem sugeriu que Naamã procurasse o profeta?",
            ["Uma menina israelita que servia em sua casa", "O rei de Israel", "Elias", "Um sacerdote"],
            0,
            "2 Reis 5:2-3.",
            "2 Reis 5:2-3",
          ),
          fill(
            "Eliseu mandou Naamã se lavar sete vezes no rio",
            ".",
            ["Jordão", "Nilo", "Eufrates"],
            0,
            "2 Reis 5:10.",
            "2 Reis 5:10",
          ),
          tf(
            "Naamã aceitou a orientação de imediato, sem reclamar.",
            false,
            "Ele ficou irritado; os servos o convenceram.",
            "2 Reis 5:11-13",
          ),
          mc(
            "Naamã era comandante de qual exército?",
            ["Da Síria (Arã)", "Do Egito", "De Israel", "Da Babilônia"],
            0,
            "2 Reis 5:1.",
            "2 Reis 5:1",
          ),
          order(
            "Ordene a história de Naamã.",
            ["A menina fala do profeta", "Naamã vai até Eliseu", "Fica irritado com a orientação", "Mergulha sete vezes e é curado"],
            "2 Reis 5:2-14.",
            "2 Reis 5:2-14",
          ),
        ],
        takeaways: [
          "Uma menina estrangeira indica o caminho da cura.",
          "Naamã resiste a uma orientação simples.",
          "Curado no Jordão, Naamã é lembrado por Jesus em Lucas 4.",
        ],
        reflection: "Às vezes a resposta é mais simples do que esperamos. Já aconteceu com você?",
      },
    ],
    review: {
      slug: "elias-u3-revisao",
      title: "Revisão: Elias e Eliseu",
      intro: "Do manto lançado no campo ao manto que divide o Jordão. Vamos relembrar!",
      extra: [
        order(
          "Ordene a relação entre Elias e Eliseu.",
          ["Elias lança o manto sobre Eliseu", "Caminhada até o Jordão", "Carro de fogo", "Eliseu divide o Jordão sozinho"],
          "1 Reis 19 e 2 Reis 2.",
          "1 Reis 19:19 - 2 Reis 2:14",
        ),
        match(
          "Associe cada pessoa ao acontecimento.",
          [
            ["Eliseu", "Pediu porção dobrada"],
            ["Naamã", "Mergulhou sete vezes"],
            ["Elias", "Subiu num redemoinho"],
          ],
          "Personagens desta unidade.",
          "2 Reis 2; 5",
        ),
        tf(
          "O manto de Elias aparece no chamado de Eliseu e na travessia do Jordão.",
          true,
          "1 Reis 19:19; 2 Reis 2:8, 13-14.",
          "1 Reis 19:19; 2 Reis 2",
        ),
      ],
      takeaways: [
        "Eliseu é chamado, acompanha Elias e herda seu manto.",
        "A partida de Elias é marcada pelo carro de fogo.",
        "Eliseu continua a missão com sinais de cuidado.",
      ],
    },
  },
];
