import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

/**
 * Jornada com Isaías. A primeira lição é compartilhada com a jornada geral
 * (g05-os-profetas). Temas com leituras divergentes (Emanuel, Servo) são
 * apresentados com as diferentes tradições, sem questões de resposta única
 * sobre a interpretação.
 */
export const isaiasUnits: UnitDef[] = [
  {
    slug: "isaias-u1-contexto",
    title: "Isaías e seu tempo",
    description: "Quem foi Isaías, quando viveu e como o livro se organiza.",
    scene: "city",
    lessons: [
      "g05-os-profetas",
      {
        slug: "i1-isaias-e-seu-tempo",
        title: "Isaías e seu tempo",
        objective: "Situar o profeta Isaías na história de Judá.",
        references: ["Isaías 1:1", "2 Reis 15-20"],
        context:
          "O livro começa apresentando “a visão de Isaías, filho de Amoz”, sobre Judá e Jerusalém. Isaías atuou na segunda metade do século VIII antes de Cristo.",
        blocks: [
          b(
            "resumo",
            "Quatro reis",
            "O primeiro versículo diz que Isaías profetizou nos dias de Uzias, Jotão, Acaz e Ezequias, reis de Judá.",
            "Isaías 1:1",
          ),
          b(
            "contexto",
            "Um império em expansão",
            "Nessa época, a Assíria era a grande potência da região. O reino do norte, Israel, caiu diante dela em 722 a.C. Judá, ao sul, viveu sob forte pressão assíria.",
            "2 Reis 17:5-6",
          ),
          b(
            "contexto",
            "Um profeta da cidade",
            "Diferente de profetas do campo, Isaías parece circular perto da corte de Jerusalém: ele fala diretamente com reis como Acaz e Ezequias.",
            "Isaías 7:3; 37:21",
          ),
          b(
            "explicacao",
            "O nome",
            "Isaías (em hebraico, Yeshayahu) significa “o Senhor salva”.",
          ),
        ],
        exercises: [
          mc(
            "De quem Isaías era filho, segundo o primeiro versículo do livro?",
            ["Amoz", "Davi", "Jessé", "Zacarias"],
            0,
            "Isaías 1:1.",
            "Isaías 1:1",
          ),
          order(
            "Ordene os reis de Judá citados em Isaías 1:1.",
            ["Uzias", "Jotão", "Acaz", "Ezequias"],
            "Essa é a sequência do versículo e da história.",
            "Isaías 1:1",
          ),
          fill(
            "A grande potência da época de Isaías era a",
            ".",
            ["Assíria", "Grécia", "Roma"],
            0,
            "A Assíria dominava a região no século VIII a.C.",
            "2 Reis 17",
          ),
          tf(
            "O nome Isaías significa “o Senhor salva”.",
            true,
            "Yeshayahu: “o Senhor salva”.",
            "Isaías 1:1",
          ),
          mc(
            "Em que cidade Isaías atuava principalmente?",
            ["Jerusalém", "Samaria", "Babilônia", "Nínive"],
            0,
            "O livro trata de Judá e Jerusalém.",
            "Isaías 1:1",
          ),
        ],
        takeaways: [
          "Isaías, filho de Amoz, atuou em Judá no século VIII a.C.",
          "Seu tempo foi marcado pela pressão do império assírio.",
          "Ele falou diretamente a reis de Jerusalém.",
        ],
        reflection: "Que voz você gostaria de ouvir em tempos de crise no seu país?",
      },
      {
        slug: "i1-um-livro-tres-partes",
        title: "Um livro em três partes",
        objective: "Conhecer a organização do livro de Isaías e o debate sobre sua formação.",
        references: ["Isaías 1-39", "Isaías 40-55", "Isaías 56-66", "Isaías 44:28-45:1"],
        context: "Isaías tem 66 capítulos. Ao ler com atenção, percebem-se mudanças de época e de tom ao longo do livro.",
        blocks: [
          b(
            "explicacao",
            "Três blocos",
            "Os capítulos 1 a 39 se passam principalmente no tempo da Assíria. Os capítulos 40 a 55 falam ao povo exilado na Babilônia e mencionam Ciro, rei persa do século VI a.C. Os capítulos 56 a 66 parecem se dirigir à comunidade que voltou do exílio.",
            "Isaías 40:1-2; 44:28; 45:1",
          ),
          b(
            "tradicoes",
            "Duas leituras sobre a autoria",
            "Na leitura tradicional, todo o livro vem do profeta Isaías, que teria anunciado acontecimentos futuros. Muitos estudiosos entendem que o livro reúne mensagens de Isaías e de profetas posteriores, ligados à sua tradição, por isso falam em “Primeiro”, “Segundo” e “Terceiro Isaías”.",
          ),
          b(
            "explicacao",
            "Um livro unido",
            "Mesmo quem divide o livro em partes reconhece temas que o atravessam: o “Santo de Israel”, a justiça, a esperança para Jerusalém e a abertura às nações.",
            "Isaías 1:4; 41:14; 60:3",
          ),
        ],
        exercises: [
          mc(
            "Quantos capítulos tem o livro de Isaías?",
            ["66", "39", "150", "27"],
            0,
            "Isaías tem 66 capítulos.",
            "Isaías 1-66",
          ),
          match(
            "Associe cada bloco ao contexto que ele reflete.",
            [
              ["Capítulos 1-39", "Tempo da Assíria"],
              ["Capítulos 40-55", "Exílio na Babilônia"],
              ["Capítulos 56-66", "Retorno do exílio"],
            ],
            "Essa divisão é muito usada em estudos do livro.",
            "Isaías 1-66",
          ),
          fill(
            "Os capítulos 44 e 45 mencionam pelo nome o rei persa",
            ".",
            ["Ciro", "Nabucodonosor", "Senaqueribe"],
            0,
            "Isaías 44:28; 45:1.",
            "Isaías 44:28; 45:1",
          ),
          mc(
            "Qual afirmação descreve melhor o debate sobre a autoria de Isaías?",
            [
              "Há a leitura tradicional de um único autor e a leitura de vários autores ligados à tradição de Isaías",
              "Todos concordam que o livro foi escrito no século I",
              "Ninguém associa o livro ao profeta Isaías",
              "O livro foi escrito por Moisés",
            ],
            0,
            "As duas posições existem e são defendidas com argumentos.",
            "Introdução a Isaías",
          ),
          tf(
            "A expressão “Santo de Israel” aparece em várias partes do livro.",
            true,
            "É um tema que atravessa o livro todo.",
            "Isaías 1:4; 41:14",
          ),
        ],
        takeaways: [
          "Isaías tem 66 capítulos que refletem épocas diferentes.",
          "Há a leitura tradicional de um autor e a acadêmica de vários autores.",
          "Temas comuns unem o livro.",
        ],
        reflection: "Como você reage quando descobre que um texto tem uma história de formação complexa?",
      },
      {
        slug: "i1-acaz-e-emanuel",
        title: "Acaz e o sinal de Emanuel",
        objective: "Conhecer o encontro de Isaías com o rei Acaz e as leituras do sinal de Emanuel.",
        references: ["Isaías 7:1-16", "Mateus 1:22-23"],
        context:
          "Por volta de 735 a.C., os reis de Arã (Síria) e de Israel se uniram contra Judá. O rei Acaz e o povo tremiam “como as árvores com o vento”.",
        blocks: [
          b(
            "resumo",
            "Não tenha medo",
            "Isaías vai ao encontro de Acaz com seu filho e diz que ele não deveria ter medo daqueles dois reis. E alerta: se vocês não confiarem, não permanecerão firmes.",
            "Isaías 7:2-9",
          ),
          b(
            "resumo",
            "Um sinal",
            "Acaz se recusa a pedir um sinal. Isaías anuncia um: uma jovem conceberia e daria à luz um filho chamado Emanuel, que quer dizer “Deus conosco”; antes que o menino crescesse, a ameaça dos dois reis passaria.",
            "Isaías 7:10-16",
          ),
          b(
            "tradicoes",
            "Leituras diferentes",
            "A palavra hebraica (almah) significa “jovem”; a antiga tradução grega usou um termo traduzido como “virgem”. O Evangelho de Mateus lê esse texto como anúncio do nascimento de Jesus. Na tradição judaica e em muitos estudos históricos, o sinal se refere a um nascimento no próprio tempo de Acaz. Muitos cristãos veem as duas leituras como complementares.",
            "Mateus 1:23",
          ),
        ],
        exercises: [
          mc(
            "O que significa o nome Emanuel?",
            ["Deus conosco", "O Senhor salva", "Príncipe da paz", "Um resto voltará"],
            0,
            "Emanuel: “Deus conosco”.",
            "Isaías 7:14; Mateus 1:23",
          ),
          match(
            "Associe cada rei ao seu papel na crise.",
            [
              ["Acaz", "Rei de Judá ameaçado"],
              ["Rezim", "Rei de Arã (Síria)"],
              ["Peca", "Rei de Israel"],
            ],
            "Isaías 7:1.",
            "Isaías 7:1",
          ),
          tf(
            "Mateus relaciona o sinal de Emanuel ao nascimento de Jesus.",
            true,
            "Mateus 1:22-23.",
            "Mateus 1:22-23",
          ),
          fill(
            "Isaías alerta: se vocês não",
            ", não permanecerão firmes.",
            ["confiarem", "lutarem", "fugirem"],
            0,
            "Isaías 7:9.",
            "Isaías 7:9",
          ),
          mc(
            "Qual afirmação descreve as leituras de Isaías 7:14?",
            [
              "Há leituras ligadas ao tempo de Acaz e a leitura de Mateus sobre Jesus",
              "Só existe uma interpretação possível",
              "O texto fala da criação do mundo",
              "O texto não fala de nenhum nascimento",
            ],
            0,
            "Tradições leem o sinal de formas diferentes, e muitos cristãos as veem como complementares.",
            "Isaías 7:14; Mateus 1:23",
          ),
        ],
        takeaways: [
          "Diante de uma ameaça, Isaías chama Acaz à confiança.",
          "O sinal de Emanuel significa “Deus conosco”.",
          "O texto tem leituras históricas e a leitura cristã de Mateus.",
        ],
        reflection: "O que muda quando você lembra que não está sozinho num momento de medo?",
      },
      {
        slug: "i1-ezequias-e-a-assiria",
        title: "Ezequias diante da Assíria",
        objective: "Conhecer a crise do cerco assírio a Jerusalém.",
        references: ["Isaías 36:1-37:38", "2 Reis 18-19"],
        context: "Em 701 a.C., o rei assírio Senaqueribe invade Judá e ameaça Jerusalém. O mesmo relato aparece em 2 Reis.",
        blocks: [
          b(
            "resumo",
            "Palavras de intimidação",
            "Um oficial assírio discursa diante das muralhas, zombando da confiança de Jerusalém e dizendo que nenhum deus tinha salvado outras cidades.",
            "Isaías 36:4-20",
          ),
          b(
            "resumo",
            "Uma carta diante de Deus",
            "O rei Ezequias recebe uma carta ameaçadora, sobe ao templo, abre a carta diante do Senhor e ora. Isaías envia uma mensagem de que a cidade não seria tomada.",
            "Isaías 37:14-35",
          ),
          b(
            "resumo",
            "A retirada",
            "O texto narra que o acampamento assírio foi atingido e que Senaqueribe voltou para Nínive. Registros assírios também mencionam essa campanha contra Judá — e não registram a tomada de Jerusalém.",
            "Isaías 37:36-37",
          ),
        ],
        exercises: [
          mc(
            "Quem era o rei assírio que ameaçou Jerusalém?",
            ["Senaqueribe", "Nabucodonosor", "Ciro", "Faraó"],
            0,
            "Isaías 36:1.",
            "Isaías 36:1",
          ),
          tf(
            "Ezequias abriu a carta ameaçadora diante do Senhor, no templo, e orou.",
            true,
            "Isaías 37:14-15.",
            "Isaías 37:14-20",
          ),
          fill(
            "Depois da crise, Senaqueribe voltou para",
            ".",
            ["Nínive", "Babilônia", "Damasco"],
            0,
            "Isaías 37:37.",
            "Isaías 37:37",
          ),
          mc(
            "Em qual outro livro o mesmo relato aparece?",
            ["2 Reis", "Gênesis", "Rute", "Atos"],
            0,
            "2 Reis 18-19 traz um relato paralelo.",
            "2 Reis 18-19",
          ),
          order(
            "Ordene a crise.",
            ["A Assíria invade Judá", "Um oficial zomba diante das muralhas", "Ezequias ora no templo", "Senaqueribe volta para Nínive"],
            "Isaías 36-37.",
            "Isaías 36-37",
          ),
        ],
        takeaways: [
          "Senaqueribe ameaça Jerusalém em 701 a.C.",
          "Ezequias leva a carta ameaçadora ao templo e ora.",
          "O relato aparece também em 2 Reis.",
        ],
        reflection: "Que “carta difícil” você gostaria de colocar diante de Deus?",
      },
    ],
    review: {
      slug: "isaias-u1-revisao",
      title: "Revisão: Isaías e seu tempo",
      intro: "Reis, impérios e um livro em três partes. Vamos relembrar!",
      extra: [
        match(
          "Associe cada rei ao encontro com Isaías.",
          [
            ["Acaz", "Sinal de Emanuel"],
            ["Ezequias", "Cerco assírio"],
          ],
          "Isaías 7; 36-37.",
          "Isaías 7; 36-37",
        ),
        order(
          "Ordene os impérios conforme aparecem no livro.",
          ["Assíria", "Babilônia", "Pérsia (Ciro)"],
          "Os blocos do livro acompanham essa sucessão.",
          "Isaías 36; 39; 45",
        ),
        tf(
          "Existe mais de uma leitura sobre a autoria do livro de Isaías.",
          true,
          "Há a leitura tradicional e a leitura acadêmica de vários autores.",
          "Introdução a Isaías",
        ),
      ],
      takeaways: [
        "Isaías atuou em Jerusalém sob a pressão da Assíria.",
        "O livro tem três grandes blocos e um debate sobre autoria.",
        "Emanuel e o cerco assírio mostram o chamado à confiança.",
      ],
    },
  },
  {
    slug: "isaias-u2-chamado-e-mensagem",
    title: "Chamado e mensagem",
    description: "A visão no templo, a missão de Isaías e seu chamado à justiça.",
    scene: "temple",
    lessons: [
      {
        slug: "i2-visao-no-templo",
        title: "A visão no templo",
        objective: "Conhecer a visão de Isaías no templo.",
        references: ["Isaías 6:1-7"],
        context: "Isaías 6 conta uma experiência marcante do profeta, “no ano em que morreu o rei Uzias”.",
        blocks: [
          b(
            "resumo",
            "Santo, santo, santo",
            "Isaías vê o Senhor num trono alto, e serafins — seres com seis asas — proclamam: “Santo, santo, santo é o Senhor dos Exércitos; toda a terra está cheia da sua glória”.",
            "Isaías 6:1-3",
          ),
          b(
            "resumo",
            "“Ai de mim!”",
            "O templo se enche de fumaça. Isaías se sente pequeno e impuro diante daquela santidade e diz que é um homem de lábios impuros.",
            "Isaías 6:4-5",
          ),
          b(
            "resumo",
            "A brasa",
            "Um serafim pega uma brasa do altar e toca os lábios de Isaías, dizendo que sua culpa foi tirada.",
            "Isaías 6:6-7",
          ),
          b(
            "contexto",
            "Um eco na liturgia",
            "O “Santo, santo, santo” é cantado até hoje em muitas celebrações cristãs (o “Sanctus”) e em orações judaicas (a “Kedushá”).",
          ),
        ],
        exercises: [
          fill(
            "A visão aconteceu no ano em que morreu o rei",
            ".",
            ["Uzias", "Davi", "Acaz"],
            0,
            "Isaías 6:1.",
            "Isaías 6:1",
          ),
          mc(
            "Quantas asas tinham os serafins?",
            ["Seis", "Duas", "Quatro", "Doze"],
            0,
            "Isaías 6:2.",
            "Isaías 6:2",
          ),
          tf(
            "Diante da visão, Isaías se sentiu pequeno e disse ter lábios impuros.",
            true,
            "Isaías 6:5.",
            "Isaías 6:5",
          ),
          mc(
            "Com o que o serafim tocou os lábios de Isaías?",
            ["Uma brasa do altar", "Uma gota de óleo", "Uma folha", "Um pedaço de pão"],
            0,
            "Isaías 6:6-7.",
            "Isaías 6:6-7",
          ),
          order(
            "Ordene a visão.",
            ["Isaías vê o trono", "Os serafins proclamam “Santo”", "Isaías diz “Ai de mim”", "A brasa toca seus lábios"],
            "Isaías 6:1-7.",
            "Isaías 6:1-7",
          ),
        ],
        takeaways: [
          "Isaías vê o Senhor no templo no ano da morte de Uzias.",
          "Os serafins proclamam “Santo, santo, santo”.",
          "A brasa nos lábios simboliza a purificação do profeta.",
        ],
        reflection: "Já se sentiu pequeno diante de algo muito grande? Como foi?",
      },
      {
        slug: "i2-eis-me-aqui",
        title: "“Eis-me aqui, envia-me”",
        objective: "Conhecer a resposta de Isaías ao chamado e a dureza da missão.",
        references: ["Isaías 6:8-13", "Mateus 13:14-15"],
        context: "Depois de purificado, Isaías ouve uma pergunta.",
        blocks: [
          b(
            "resumo",
            "A pergunta e a resposta",
            "O Senhor pergunta: “A quem enviarei? Quem irá por nós?”. Isaías responde: “Eis-me aqui; envia-me”.",
            "Isaías 6:8",
          ),
          b(
            "resumo",
            "Uma missão difícil",
            "A missão não seria fácil: o povo ouviria sem entender e veria sem perceber. Isaías pergunta: “Até quando?”. A resposta fala de destruição — mas termina com a imagem de um toco do qual brota uma semente santa.",
            "Isaías 6:9-13",
          ),
          b(
            "contexto",
            "Citado nos Evangelhos",
            "Jesus usa esse trecho de Isaías para falar de quem ouve suas parábolas sem compreender.",
            "Mateus 13:14-15",
          ),
        ],
        exercises: [
          fill(
            "Isaías responde: “Eis-me aqui;",
            "”.",
            ["envia-me", "espera-me", "esquece-me"],
            0,
            "Isaías 6:8.",
            "Isaías 6:8",
          ),
          tf(
            "A missão de Isaías é apresentada como fácil e cheia de sucesso imediato.",
            false,
            "O texto fala de um povo que ouviria sem entender.",
            "Isaías 6:9-10",
          ),
          mc(
            "Qual pergunta Isaías faz sobre a missão?",
            ["“Até quando?”", "“Por que eu?”", "“Onde fica?”", "“Quanto vou ganhar?”"],
            0,
            "Isaías 6:11.",
            "Isaías 6:11",
          ),
          mc(
            "Com que imagem de esperança Isaías 6 termina?",
            ["Um toco do qual brota uma semente santa", "Um rio de mel", "Uma estrela", "Uma arca"],
            0,
            "Isaías 6:13.",
            "Isaías 6:13",
          ),
          mc(
            "Em que contexto Jesus cita Isaías 6?",
            ["Ao falar de quem ouve as parábolas sem compreender", "Na última ceia", "Na tentação", "No batismo"],
            0,
            "Mateus 13:14-15.",
            "Mateus 13:13-15",
          ),
        ],
        takeaways: [
          "Isaías se oferece: “Eis-me aqui; envia-me”.",
          "A missão seria difícil, diante de um povo que não ouviria.",
          "Mesmo assim, o capítulo termina com uma semente de esperança.",
        ],
        reflection: "A que tarefa difícil você já disse “eis-me aqui”?",
      },
      {
        slug: "i2-cantico-da-vinha",
        title: "O cântico da vinha",
        objective: "Conhecer a parábola poética da vinha em Isaías 5.",
        references: ["Isaías 5:1-7", "Marcos 12:1-12"],
        context: "Isaías usa uma canção de amor sobre uma vinha para fazer uma denúncia.",
        blocks: [
          b(
            "resumo",
            "Uma vinha bem cuidada",
            "O dono prepara o terreno, tira as pedras, planta as melhores videiras, constrói uma torre e um lagar. Esperava uvas boas, mas a vinha deu uvas azedas.",
            "Isaías 5:1-2",
          ),
          b(
            "resumo",
            "A explicação",
            "A vinha é a casa de Israel e o povo de Judá. Deus esperava justiça, e encontrou derramamento de sangue; esperava retidão, e ouviu gritos de aflição.",
            "Isaías 5:7",
          ),
          b(
            "explicacao",
            "Um jogo de palavras",
            "Em hebraico, o verso final tem um jogo de sons entre “justiça” (mishpat) e “derramamento de sangue” (mispah), e entre “retidão” (tsedaqah) e “grito” (tse’aqah). A forma poética reforça a denúncia.",
          ),
        ],
        exercises: [
          mc(
            "Que tipo de uvas a vinha produziu?",
            ["Azedas", "Doces", "Douradas", "Nenhuma"],
            0,
            "Isaías 5:2.",
            "Isaías 5:2",
          ),
          fill(
            "Deus esperava",
            ", mas encontrou derramamento de sangue.",
            ["justiça", "riqueza", "festa"],
            0,
            "Isaías 5:7.",
            "Isaías 5:7",
          ),
          tf(
            "No cântico, a vinha representa o povo de Israel e Judá.",
            true,
            "O próprio texto explica a imagem em Isaías 5:7.",
            "Isaías 5:7",
          ),
          match(
            "Associe o que o dono fez na vinha.",
            [
              ["Tirou", "as pedras"],
              ["Plantou", "as melhores videiras"],
              ["Construiu", "uma torre e um lagar"],
            ],
            "Isaías 5:2.",
            "Isaías 5:2",
          ),
          mc(
            "Qual parábola de Jesus também usa a imagem de uma vinha?",
            ["A dos lavradores maus, em Marcos 12", "A do filho pródigo", "A do bom samaritano", "A do semeador"],
            0,
            "Marcos 12:1-12 ecoa Isaías 5.",
            "Marcos 12:1",
          ),
        ],
        takeaways: [
          "Isaías usa uma canção sobre uma vinha para denunciar injustiças.",
          "A vinha representa o povo; as uvas azedas, a falta de justiça.",
          "Jesus retoma a imagem da vinha numa parábola.",
        ],
        reflection: "Que “frutos” você gostaria que sua vida produzisse?",
      },
      {
        slug: "i2-justica-para-os-vulneraveis",
        title: "Aprendam a fazer o bem",
        objective: "Conhecer o chamado de Isaías à justiça social.",
        references: ["Isaías 1:10-17", "Isaías 58:6-10"],
        context: "Isaías critica um culto cheio de rituais e vazio de justiça.",
        blocks: [
          b(
            "resumo",
            "Rituais sem justiça",
            "O profeta diz que Deus não se agrada de sacrifícios e festas quando as mãos estão cheias de injustiça.",
            "Isaías 1:11-15",
          ),
          b(
            "resumo",
            "O que fazer",
            "Isaías chama: lavem-se, deixem de fazer o mal, aprendam a fazer o bem, busquem a justiça, defendam o oprimido, o órfão e a viúva.",
            "Isaías 1:16-17",
          ),
          b(
            "resumo",
            "O jejum que agrada",
            "Mais adiante, o livro diz que o verdadeiro jejum é soltar as correntes da injustiça, repartir o pão com quem tem fome, acolher quem não tem casa e vestir quem não tem roupa.",
            "Isaías 58:6-7",
          ),
        ],
        exercises: [
          fill(
            "Isaías chama: aprendam a fazer o",
            ".",
            ["bem", "templo", "sacrifício"],
            0,
            "Isaías 1:17.",
            "Isaías 1:17",
          ),
          match(
            "Associe cada texto à sua mensagem.",
            [
              ["Isaías 1:17", "Defender o órfão e a viúva"],
              ["Isaías 58:7", "Repartir o pão com quem tem fome"],
            ],
            "Dois textos sobre justiça e cuidado.",
            "Isaías 1:17; 58:7",
          ),
          tf(
            "Isaías critica rituais religiosos feitos sem justiça.",
            true,
            "Isaías 1:11-15.",
            "Isaías 1:11-15",
          ),
          mc(
            "Segundo Isaías 58, qual é o jejum que agrada?",
            ["Soltar as correntes da injustiça e repartir o pão", "Não comer por um mês", "Usar roupas especiais", "Ficar em silêncio"],
            0,
            "Isaías 58:6-7.",
            "Isaías 58:6-7",
          ),
          mc(
            "Quem Isaías menciona como pessoas a serem defendidas?",
            ["O oprimido, o órfão e a viúva", "Os reis e os sacerdotes", "Os comerciantes", "Os soldados"],
            0,
            "Isaías 1:17.",
            "Isaías 1:17",
          ),
        ],
        takeaways: [
          "Isaías critica um culto separado da justiça.",
          "Ele chama a defender o oprimido, o órfão e a viúva.",
          "O jejum que agrada é a partilha e a libertação.",
        ],
        reflection: "Como fé e justiça se encontram no seu dia a dia?",
      },
      {
        slug: "i2-nomes-simbolicos",
        title: "Filhos com nomes de mensagem",
        objective: "Conhecer os sinais que Isaías deu por meio dos nomes de seus filhos.",
        references: ["Isaías 7:3", "Isaías 8:1-4", "Isaías 8:18"],
        context: "Profetas às vezes comunicavam suas mensagens com gestos e sinais. Isaías fez isso até com os nomes dos filhos.",
        blocks: [
          b(
            "resumo",
            "Sear-Jasube",
            "O filho que acompanha Isaías no encontro com Acaz se chama Sear-Jasube, que significa “um resto voltará” — mensagem de alerta e de esperança.",
            "Isaías 7:3",
          ),
          b(
            "resumo",
            "Maer-Salal-Has-Baz",
            "Outro filho recebe um nome longo que significa algo como “rápido-saque, depressa-pilhagem”, anunciando que Damasco e Samaria logo seriam saqueadas pela Assíria.",
            "Isaías 8:1-4",
          ),
          b(
            "resumo",
            "Sinais vivos",
            "Isaías diz que ele e os filhos que Deus lhe deu são sinais em Israel.",
            "Isaías 8:18",
          ),
        ],
        exercises: [
          mc(
            "O que significa Sear-Jasube?",
            ["Um resto voltará", "Deus conosco", "O Senhor salva", "Casa de Deus"],
            0,
            "Isaías 7:3.",
            "Isaías 7:3",
          ),
          match(
            "Associe cada nome ao seu significado.",
            [
              ["Sear-Jasube", "Um resto voltará"],
              ["Maer-Salal-Has-Baz", "Rápido-saque, depressa-pilhagem"],
              ["Isaías", "O Senhor salva"],
            ],
            "Nomes que comunicam mensagens.",
            "Isaías 7:3; 8:1-4",
          ),
          tf(
            "Isaías diz que ele e seus filhos são sinais em Israel.",
            true,
            "Isaías 8:18.",
            "Isaías 8:18",
          ),
          fill(
            "O nome Maer-Salal-Has-Baz anunciava o saque de Damasco e",
            ".",
            ["Samaria", "Jerusalém", "Babilônia"],
            0,
            "Isaías 8:4.",
            "Isaías 8:4",
          ),
          mc(
            "Por que os profetas usavam sinais como esses?",
            ["Para comunicar a mensagem de forma visível e memorável", "Para esconder a mensagem", "Para agradar ao rei", "Por acaso"],
            0,
            "Gestos e nomes tornavam a mensagem concreta.",
            "Isaías 8:18",
          ),
        ],
        takeaways: [
          "Os filhos de Isaías tinham nomes com mensagens.",
          "“Um resto voltará” une alerta e esperança.",
          "Profetas usavam sinais visíveis para comunicar.",
        ],
        reflection: "Se sua vida fosse um “sinal” para alguém, que mensagem ela passaria?",
      },
    ],
    review: {
      slug: "isaias-u2-revisao",
      title: "Revisão: Chamado e mensagem",
      intro: "Do templo às ruas de Jerusalém. Vamos relembrar a missão de Isaías.",
      extra: [
        match(
          "Associe cada imagem à sua mensagem.",
          [
            ["Brasa nos lábios", "Purificação do profeta"],
            ["Uvas azedas", "Falta de justiça"],
            ["Toco que brota", "Esperança após a crise"],
          ],
          "Imagens fortes de Isaías.",
          "Isaías 5:2; 6:7, 13",
        ),
        fill(
          "No chamado, Isaías responde: “Eis-me",
          "”.",
          ["aqui", "longe", "pronto amanhã"],
          0,
          "Isaías 6:8.",
          "Isaías 6:8",
        ),
        tf(
          "Para Isaías, culto e justiça devem caminhar juntos.",
          true,
          "Isaías 1:11-17.",
          "Isaías 1:11-17",
        ),
      ],
      takeaways: [
        "Isaías é chamado numa visão no templo.",
        "Sua mensagem denuncia injustiças com poesia e sinais.",
        "Ele chama à justiça e mantém viva a esperança.",
      ],
    },
  },
  {
    slug: "isaias-u3-temas",
    title: "Grandes temas de Isaías",
    description: "Paz entre as nações, um rei justo, consolo no exílio, o Servo e a nova criação.",
    scene: "garden",
    lessons: [
      {
        slug: "i3-espadas-em-arados",
        title: "Espadas em arados",
        objective: "Conhecer a visão de paz de Isaías 2.",
        references: ["Isaías 2:2-4", "Miqueias 4:1-3"],
        context: "Num tempo de guerras, Isaías anuncia uma visão de paz entre os povos.",
        blocks: [
          b(
            "resumo",
            "Todos sobem ao monte",
            "Nos últimos dias, muitos povos subiriam ao monte do Senhor para aprender seus caminhos.",
            "Isaías 2:2-3",
          ),
          b(
            "resumo",
            "Ferramentas de cultivo",
            "As nações transformariam suas espadas em arados e suas lanças em foices; não aprenderiam mais a guerra.",
            "Isaías 2:4",
          ),
          b(
            "contexto",
            "Uma visão que ecoa",
            "Uma passagem quase igual aparece no profeta Miqueias. A frase sobre espadas e arados inspira até hoje campanhas e monumentos pela paz.",
            "Miqueias 4:3",
          ),
        ],
        exercises: [
          fill(
            "As nações transformariam suas espadas em",
            ".",
            ["arados", "coroas", "escudos"],
            0,
            "Isaías 2:4.",
            "Isaías 2:4",
          ),
          match(
            "Associe cada arma à ferramenta.",
            [
              ["Espadas", "Arados"],
              ["Lanças", "Foices"],
            ],
            "Isaías 2:4.",
            "Isaías 2:4",
          ),
          tf(
            "Uma passagem muito parecida aparece no livro de Miqueias.",
            true,
            "Miqueias 4:1-3.",
            "Miqueias 4:1-3",
          ),
          mc(
            "Para onde os povos sobem na visão?",
            ["Ao monte do Senhor", "Ao mar", "Ao deserto", "À Babilônia"],
            0,
            "Isaías 2:2-3.",
            "Isaías 2:3",
          ),
          mc(
            "Qual é o tema central de Isaías 2:2-4?",
            ["Paz entre as nações", "Construção de muralhas", "Uma colheita de trigo", "A criação do mundo"],
            0,
            "A visão fala de povos que deixam a guerra.",
            "Isaías 2:4",
          ),
        ],
        takeaways: [
          "Isaías anuncia povos aprendendo os caminhos de Deus.",
          "Armas viram ferramentas: espadas em arados.",
          "A visão aparece também em Miqueias.",
        ],
        reflection: "Que “espada” você gostaria de transformar em “arado” na sua vida?",
      },
      {
        slug: "i3-rebento-de-jesse",
        title: "Um rei justo e um mundo em paz",
        objective: "Conhecer as profecias do menino-rei e do rebento de Jessé.",
        references: ["Isaías 9:2-7", "Isaías 11:1-9"],
        context: "Isaías anuncia um descendente de Davi que governaria com justiça.",
        blocks: [
          b(
            "resumo",
            "Um menino nos nasceu",
            "Isaías fala de um povo que andava em trevas e viu uma grande luz, e de um menino que nasceria, chamado Maravilhoso Conselheiro, Deus Forte, Pai Eterno, Príncipe da Paz.",
            "Isaías 9:2, 6",
          ),
          b(
            "resumo",
            "O rebento",
            "Do tronco de Jessé (pai de Davi) brotaria um rebento, sobre o qual repousaria o espírito de sabedoria. Ele julgaria os pobres com justiça. O lobo moraria com o cordeiro, e uma criança pequena os guiaria.",
            "Isaías 11:1-6",
          ),
          b(
            "tradicoes",
            "Leituras e numeração",
            "A tradição cristã lê esses textos como anúncios de Jesus, e eles são muito usados no Natal. Na tradição judaica, são lidos como esperança de um rei da linhagem de Davi. Atenção à numeração: Isaías 9:6 nas Bíblias protestantes corresponde a 9:5 em muitas Bíblias católicas e na Bíblia Hebraica.",
          ),
        ],
        exercises: [
          mc(
            "De quem o “tronco de Jessé” lembra a linhagem?",
            ["Do rei Davi, filho de Jessé", "De Moisés", "De Abraão", "De Elias"],
            0,
            "Jessé era pai de Davi.",
            "Isaías 11:1; 1 Samuel 16:1",
          ),
          match(
            "Associe os animais que vivem juntos em Isaías 11.",
            [
              ["Lobo", "Cordeiro"],
              ["Leopardo", "Cabrito"],
            ],
            "Imagens de paz na criação.",
            "Isaías 11:6",
          ),
          fill(
            "Um dos títulos do menino em Isaías 9 é “Príncipe da",
            "”.",
            ["Paz", "Guerra", "Terra"],
            0,
            "Isaías 9:6 (9:5 em algumas Bíblias).",
            "Isaías 9:6",
          ),
          tf(
            "Isaías 9:6 tem o mesmo número em todas as Bíblias.",
            false,
            "Em muitas Bíblias católicas e na Bíblia Hebraica, é Isaías 9:5.",
            "Isaías 9:5-6",
          ),
          mc(
            "Segundo Isaías 11, como o rebento julgaria os pobres?",
            ["Com justiça", "Com rigor sem misericórdia", "Pela aparência", "Pelo que ouvisse dizer"],
            0,
            "Isaías 11:3-4 diz que ele não julgaria pela aparência, mas com justiça.",
            "Isaías 11:3-4",
          ),
        ],
        takeaways: [
          "Isaías anuncia um menino chamado Príncipe da Paz.",
          "Do tronco de Jessé viria um rei justo.",
          "Cristãos e judeus leem esses textos com esperanças próprias.",
        ],
        reflection: "Que imagem de paz de Isaías 11 você gostaria de ver acontecer?",
      },
      {
        slug: "i3-consolai",
        title: "Consolem o meu povo",
        objective: "Conhecer a mensagem de consolo de Isaías 40.",
        references: ["Isaías 40:1-11", "Isaías 40:28-31", "Marcos 1:2-3"],
        context: "O capítulo 40 abre a parte do livro que fala ao povo exilado na Babilônia.",
        blocks: [
          b(
            "resumo",
            "Falem ao coração",
            "O capítulo começa: “Consolem, consolem o meu povo”, e pede que se fale ao coração de Jerusalém.",
            "Isaías 40:1-2",
          ),
          b(
            "resumo",
            "Um caminho no deserto",
            "Uma voz clama para preparar no deserto o caminho do Senhor. Os Evangelhos aplicam essa passagem a João Batista.",
            "Isaías 40:3; Marcos 1:2-3",
          ),
          b(
            "resumo",
            "A flor e a palavra",
            "A erva seca e a flor cai, mas a palavra de Deus permanece para sempre. E quem espera no Senhor renova as forças, como águias.",
            "Isaías 40:8, 31",
          ),
        ],
        exercises: [
          fill(
            "Isaías 40 começa: “Consolem, consolem o meu",
            "”.",
            ["povo", "rei", "templo"],
            0,
            "Isaías 40:1.",
            "Isaías 40:1",
          ),
          mc(
            "A quem os Evangelhos aplicam a “voz que clama no deserto”?",
            ["João Batista", "Pedro", "Paulo", "Isaías"],
            0,
            "Marcos 1:2-4.",
            "Marcos 1:2-4",
          ),
          tf(
            "Isaías 40 diz que a palavra de Deus permanece para sempre.",
            true,
            "Isaías 40:8.",
            "Isaías 40:8",
          ),
          match(
            "Associe cada imagem ao que ela comunica.",
            [
              ["Flor que cai", "O que é passageiro"],
              ["Águias", "Forças renovadas"],
              ["Caminho no deserto", "Preparar a vinda do Senhor"],
            ],
            "Imagens de Isaías 40.",
            "Isaías 40:3, 8, 31",
          ),
          mc(
            "A quem Isaías 40 se dirige principalmente?",
            ["Ao povo exilado", "Aos egípcios", "Ao rei Acaz", "Aos assírios"],
            0,
            "O capítulo abre a mensagem de consolo para o exílio.",
            "Isaías 40:1-2",
          ),
        ],
        takeaways: [
          "Isaías 40 traz consolo ao povo exilado.",
          "A voz no deserto é aplicada a João Batista nos Evangelhos.",
          "Quem espera no Senhor renova as forças.",
        ],
        reflection: "Que palavra de consolo você gostaria de dizer a alguém hoje?",
      },
      {
        slug: "i3-servo-sofredor",
        title: "O Servo Sofredor",
        objective: "Conhecer o cântico do Servo em Isaías 53 e suas leituras.",
        references: ["Isaías 52:13-53:12", "Isaías 49:3", "Atos 8:30-35"],
        context: "Isaías 40-55 tem quatro poemas sobre um “Servo do Senhor”. O mais conhecido é o quarto, em Isaías 52:13-53:12.",
        blocks: [
          b(
            "resumo",
            "Desprezado e ferido",
            "O Servo é descrito como alguém desprezado, que conheceu o sofrimento. Ele carrega as dores dos outros; foi ferido por causa das culpas deles, e por suas feridas eles são curados.",
            "Isaías 53:3-5",
          ),
          b(
            "resumo",
            "Como um cordeiro",
            "Ele é comparado a um cordeiro levado ao matadouro, que não abre a boca.",
            "Isaías 53:7",
          ),
          b(
            "tradicoes",
            "Quem é o Servo?",
            "Os cristãos leem o texto como anúncio do sofrimento de Jesus — em Atos, Filipe explica esse trecho ao oficial etíope falando de Jesus. Na tradição judaica, o Servo é frequentemente entendido como o povo de Israel, que o próprio livro chama de “meu servo” (Isaías 49:3). Há ainda outras leituras.",
            "Atos 8:32-35; Isaías 49:3",
          ),
        ],
        exercises: [
          fill(
            "O Servo é comparado a um",
            "levado ao matadouro.",
            ["cordeiro", "leão", "pastor"],
            0,
            "Isaías 53:7.",
            "Isaías 53:7",
          ),
          tf(
            "Em Atos, Filipe explica Isaías 53 ao oficial etíope falando de Jesus.",
            true,
            "Atos 8:32-35.",
            "Atos 8:32-35",
          ),
          mc(
            "Qual afirmação descreve as leituras sobre o Servo?",
            [
              "Cristãos o leem como Jesus; na tradição judaica, é frequentemente o povo de Israel",
              "Todos concordam que é o rei Ezequias",
              "Ninguém nunca interpretou o texto",
              "É um texto sobre a criação",
            ],
            0,
            "Há leituras diferentes, cada uma com sua tradição.",
            "Isaías 49:3; Atos 8:35",
          ),
          mc(
            "Onde está o quarto cântico do Servo?",
            ["Isaías 52:13-53:12", "Isaías 1:1-9", "Isaías 6:1-8", "Isaías 65:17-25"],
            0,
            "É o trecho mais conhecido sobre o Servo.",
            "Isaías 52:13-53:12",
          ),
          fill(
            "O texto diz que por suas",
            "os outros são curados.",
            ["feridas", "palavras", "riquezas"],
            0,
            "Isaías 53:5.",
            "Isaías 53:5",
          ),
        ],
        takeaways: [
          "Isaías 53 descreve um Servo que sofre pelos outros.",
          "Cristãos leem o texto como anúncio de Jesus.",
          "Na tradição judaica, o Servo é frequentemente o povo de Israel.",
        ],
        reflection: "O que significa carregar a dor de alguém?",
      },
      {
        slug: "i3-novos-ceus",
        title: "Novos céus e nova terra",
        objective: "Conhecer a esperança final de Isaías e como Jesus usou o livro.",
        references: ["Isaías 61:1-2", "Lucas 4:16-21", "Isaías 65:17-25"],
        context: "A última parte do livro se dirige à comunidade que voltou do exílio e abre horizontes de esperança.",
        blocks: [
          b(
            "resumo",
            "Boas notícias aos pobres",
            "Isaías 61 começa com alguém ungido para levar boas notícias aos pobres, cuidar dos de coração quebrantado e anunciar liberdade aos cativos.",
            "Isaías 61:1-2",
          ),
          b(
            "resumo",
            "Na sinagoga de Nazaré",
            "Lucas conta que Jesus leu esse trecho de Isaías na sinagoga de Nazaré e disse: “Hoje se cumpriu esta Escritura que vocês acabaram de ouvir”.",
            "Lucas 4:16-21",
          ),
          b(
            "resumo",
            "Uma nova criação",
            "Isaías 65 fala de novos céus e nova terra, onde não haveria choro, as pessoas morariam nas casas que construíssem, e o lobo e o cordeiro pastariam juntos.",
            "Isaías 65:17-25",
          ),
        ],
        exercises: [
          mc(
            "Em que lugar Jesus leu Isaías 61, segundo Lucas?",
            ["Na sinagoga de Nazaré", "No templo de Jerusalém", "À beira do lago", "No monte das Oliveiras"],
            0,
            "Lucas 4:16-21.",
            "Lucas 4:16",
          ),
          fill(
            "Isaías 61 fala de levar boas notícias aos",
            ".",
            ["pobres", "reis", "soldados"],
            0,
            "Isaías 61:1.",
            "Isaías 61:1",
          ),
          tf(
            "Isaías 65 fala de novos céus e nova terra.",
            true,
            "Isaías 65:17.",
            "Isaías 65:17",
          ),
          match(
            "Associe cada texto ao tema.",
            [
              ["Isaías 61", "Liberdade aos cativos"],
              ["Isaías 65", "Nova criação"],
              ["Lucas 4", "Jesus lê Isaías em Nazaré"],
            ],
            "Textos desta lição.",
            "Isaías 61; 65; Lucas 4",
          ),
          order(
            "Ordene os grandes temas de Isaías como aparecem no livro.",
            ["Espadas em arados", "O rebento de Jessé", "Consolo para o exílio", "O Servo Sofredor", "Novos céus e nova terra"],
            "Isaías 2; 11; 40; 53; 65.",
            "Isaías 2-65",
          ),
        ],
        takeaways: [
          "Isaías 61 anuncia boas notícias aos pobres.",
          "Jesus lê esse texto em Nazaré, segundo Lucas.",
          "O livro termina com a esperança de uma nova criação.",
        ],
        reflection: "Que “boa notícia” você gostaria de levar a alguém nesta semana?",
      },
    ],
    review: {
      slug: "isaias-u3-revisao",
      title: "Revisão: Grandes temas de Isaías",
      intro: "Paz, justiça, consolo e esperança. Vamos relembrar os temas de Isaías.",
      extra: [
        match(
          "Associe cada imagem ao capítulo.",
          [
            ["Espadas em arados", "Isaías 2"],
            ["Lobo com o cordeiro", "Isaías 11"],
            ["Voz no deserto", "Isaías 40"],
            ["Cordeiro levado ao matadouro", "Isaías 53"],
          ],
          "Imagens marcantes de Isaías.",
          "Isaías 2; 11; 40; 53",
        ),
        mc(
          "Qual destes textos de Isaías Jesus lê em Nazaré?",
          ["Isaías 61", "Isaías 6", "Isaías 36", "Isaías 1"],
          0,
          "Lucas 4:17-19.",
          "Lucas 4:17-19",
        ),
        tf(
          "Textos como Isaías 9, 11 e 53 têm leituras diferentes em tradições cristãs e judaicas.",
          true,
          "Cada tradição lê esses textos com sua própria esperança.",
          "Isaías 9; 11; 53",
        ),
      ],
      takeaways: [
        "Isaías sonha com paz entre as nações e um rei justo.",
        "O livro consola o povo no exílio e fala do Servo.",
        "A esperança final é uma nova criação.",
      ],
    },
  },
];
