import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

/**
 * Jornada com João, o apóstolo (filho de Zebedeu) — não confundir com João
 * Batista. As lições separam o que os textos dizem sobre ele do que a
 * tradição associa a ele (como o “discípulo amado” e a autoria do Evangelho).
 */
export const joaoUnits: UnitDef[] = [
  {
    slug: "joao-u1-chamado",
    title: "O chamado de João",
    description: "Quem foi João, filho de Zebedeu, e como viveu perto de Jesus.",
    scene: "sea",
    lessons: [
      "g06-primeiros-discipulos",
      {
        slug: "j1-quem-e-joao",
        title: "Quem é João, o apóstolo?",
        objective: "Identificar João, filho de Zebedeu, e diferenciá-lo de outros Joões.",
        references: ["Marcos 1:19-20", "Marcos 3:17", "Mateus 4:21-22", "Marcos 1:4"],
        context:
          "Há vários Joões no Novo Testamento. Esta jornada acompanha João, filho de Zebedeu, um dos Doze apóstolos.",
        blocks: [
          b(
            "resumo",
            "Uma família de pescadores",
            "João e seu irmão Tiago eram filhos de Zebedeu. Trabalhavam como pescadores no mar da Galileia, num negócio que tinha até empregados.",
            "Marcos 1:19-20",
          ),
          b(
            "explicacao",
            "Não é João Batista",
            "João Batista era o pregador do deserto que batizou Jesus. O apóstolo João era um pescador chamado por Jesus. Há ainda João Marcos, ligado ao Evangelho de Marcos, e o autor do Apocalipse, que se apresenta como João.",
            "Marcos 1:4; Atos 12:12; Apocalipse 1:9",
          ),
          b(
            "resumo",
            "Um apelido forte",
            "Na lista dos Doze, Marcos conta que Jesus chamou Tiago e João de “Boanerges”, que quer dizer “filhos do trovão”.",
            "Marcos 3:17",
          ),
        ],
        exercises: [
          mc(
            "Quem era o pai de João, o apóstolo?",
            ["Zebedeu", "Zacarias", "Jonas", "José"],
            0,
            "Marcos 1:19.",
            "Marcos 1:19",
          ),
          match(
            "Associe cada João à sua descrição.",
            [
              ["João Batista", "Batizava no rio Jordão"],
              ["João, filho de Zebedeu", "Pescador e apóstolo"],
              ["João Marcos", "Ligado ao Evangelho de Marcos"],
            ],
            "Diferentes Joões do Novo Testamento.",
            "Marcos 1:4, 19; Atos 12:12",
          ),
          fill(
            "Jesus chamou Tiago e João de Boanerges, que quer dizer “filhos do",
            "”.",
            ["trovão", "mar", "fogo"],
            0,
            "Marcos 3:17.",
            "Marcos 3:17",
          ),
          tf(
            "João, o apóstolo, foi quem batizou Jesus no Jordão.",
            false,
            "Quem batizou Jesus foi João Batista.",
            "Marcos 1:9",
          ),
          mc(
            "Quem era o irmão de João?",
            ["Tiago", "Pedro", "André", "Mateus"],
            0,
            "Marcos 1:19.",
            "Marcos 1:19",
          ),
        ],
        takeaways: [
          "João era filho de Zebedeu e irmão de Tiago.",
          "Ele não é João Batista.",
          "Jesus chamou os irmãos de “filhos do trovão”.",
        ],
        reflection: "Que apelido carinhoso (ou bem-humorado) já disseram sobre você?",
      },
      {
        slug: "j1-filhos-do-trovao",
        title: "Os filhos do trovão",
        objective: "Conhecer episódios que mostram o temperamento de João e o ensino de Jesus sobre servir.",
        references: ["Lucas 9:51-56", "Marcos 9:38-40", "Marcos 10:35-45"],
        context: "Os Evangelhos não idealizam João: mostram um jovem intenso, que aprende com Jesus.",
        blocks: [
          b(
            "resumo",
            "Fogo do céu?",
            "Quando uma aldeia samaritana não recebe Jesus, Tiago e João perguntam se deveriam pedir fogo do céu. Jesus os repreende, e eles seguem para outra aldeia.",
            "Lucas 9:52-56",
          ),
          b(
            "resumo",
            "“Ele não é dos nossos”",
            "João conta que tentaram impedir um homem que expulsava demônios em nome de Jesus, porque ele não andava com o grupo. Jesus diz para não impedir: quem não é contra nós, é por nós.",
            "Marcos 9:38-40",
          ),
          b(
            "resumo",
            "Um pedido de lugar de honra",
            "Tiago e João pedem para sentar à direita e à esquerda de Jesus em sua glória. Jesus ensina que, entre eles, quem quiser ser grande deve ser servo de todos.",
            "Marcos 10:35-45",
          ),
        ],
        exercises: [
          mc(
            "O que Tiago e João quiseram pedir contra a aldeia samaritana?",
            ["Fogo do céu", "Chuva", "Uma praga de gafanhotos", "Um terremoto"],
            0,
            "Lucas 9:54.",
            "Lucas 9:54",
          ),
          tf(
            "Jesus aprovou a ideia de mandar fogo sobre a aldeia.",
            false,
            "Jesus os repreendeu.",
            "Lucas 9:55",
          ),
          fill(
            "Jesus ensina que quem quiser ser grande deve ser",
            "de todos.",
            ["servo", "rei", "chefe"],
            0,
            "Marcos 10:43-44.",
            "Marcos 10:43-44",
          ),
          match(
            "Associe cada episódio à lição de Jesus.",
            [
              ["Aldeia samaritana", "Não responder à rejeição com violência"],
              ["Homem que expulsava demônios", "Não impedir quem faz o bem"],
              ["Pedido de honra", "Grandeza é servir"],
            ],
            "Lições dadas aos “filhos do trovão”.",
            "Lucas 9; Marcos 9-10",
          ),
          mc(
            "O que Tiago e João pediram em Marcos 10?",
            ["Sentar à direita e à esquerda de Jesus em sua glória", "Voltar a pescar", "Ir para Roma", "Construir uma tenda"],
            0,
            "Marcos 10:37.",
            "Marcos 10:37",
          ),
        ],
        takeaways: [
          "João mostra um temperamento intenso nos Evangelhos.",
          "Jesus o corrige diante da violência e da exclusão.",
          "A grandeza, para Jesus, está em servir.",
        ],
        reflection: "Em que situação você precisa trocar o “trovão” pelo serviço?",
      },
      {
        slug: "j1-circulo-proximo",
        title: "Pedro, Tiago e João",
        objective: "Conhecer os momentos em que João esteve no círculo mais próximo de Jesus.",
        references: ["Marcos 5:37-43", "Marcos 9:2", "Marcos 14:33", "Gálatas 2:9"],
        context: "Entre os Doze, três discípulos aparecem com Jesus em momentos especiais: Pedro, Tiago e João.",
        blocks: [
          b(
            "resumo",
            "Na casa de Jairo",
            "Quando Jesus vai à casa de Jairo, cuja filha tinha morrido, ele só permite que Pedro, Tiago e João o acompanhem. Ali, toma a menina pela mão e diz: “Talitá cumi”, e ela se levanta.",
            "Marcos 5:37-42",
          ),
          b(
            "resumo",
            "No monte e no jardim",
            "Os três sobem com Jesus ao monte da transfiguração e também são levados mais perto dele no Getsêmani.",
            "Marcos 9:2; 14:33",
          ),
          b(
            "resumo",
            "Uma coluna da comunidade",
            "Anos depois, Paulo menciona Tiago (irmão de Jesus), Cefas (Pedro) e João como “colunas” da comunidade de Jerusalém.",
            "Gálatas 2:9",
          ),
        ],
        exercises: [
          mc(
            "Quais discípulos entraram com Jesus na casa de Jairo?",
            ["Pedro, Tiago e João", "André, Filipe e Tomé", "Mateus e Judas", "Todos os Doze"],
            0,
            "Marcos 5:37.",
            "Marcos 5:37",
          ),
          fill(
            "Na casa de Jairo, Jesus diz: “Talitá",
            "”.",
            ["cumi", "efatá", "maranata"],
            0,
            "Marcos 5:41 — “Menina, levante-se”.",
            "Marcos 5:41",
          ),
          match(
            "Associe cada momento ao lugar.",
            [
              ["Filha de Jairo", "Casa de Jairo"],
              ["Transfiguração", "Monte alto"],
              ["Oração angustiada", "Getsêmani"],
            ],
            "Momentos do círculo próximo.",
            "Marcos 5; 9; 14",
          ),
          tf(
            "Paulo chama João de uma das “colunas” da comunidade de Jerusalém.",
            true,
            "Gálatas 2:9.",
            "Gálatas 2:9",
          ),
          order(
            "Ordene esses momentos como aparecem em Marcos.",
            ["Casa de Jairo", "Transfiguração", "Getsêmani"],
            "Marcos 5, 9 e 14.",
            "Marcos 5-14",
          ),
        ],
        takeaways: [
          "João fazia parte do círculo mais próximo de Jesus.",
          "Esteve na casa de Jairo, na transfiguração e no Getsêmani.",
          "Paulo o chama de “coluna” da comunidade.",
        ],
        reflection: "Quem faz parte do seu “círculo próximo”? O que vocês vivem juntos?",
      },
      {
        slug: "j1-discipulo-amado",
        title: "O “discípulo amado”",
        objective: "Entender quem é o “discípulo amado” e por que a tradição o identifica com João.",
        references: ["João 13:23-25", "João 19:26-27", "João 20:2-8", "João 21:7, 20-24"],
        context: "O Evangelho de João fala várias vezes de um “discípulo a quem Jesus amava”, sem dizer seu nome.",
        blocks: [
          b(
            "resumo",
            "Onde ele aparece",
            "Esse discípulo está ao lado de Jesus na última ceia, aos pés da cruz, corre ao túmulo vazio e reconhece Jesus à beira do lago.",
            "João 13:23; 19:26; 20:2; 21:7",
          ),
          b(
            "tradicoes",
            "A identificação tradicional",
            "Desde o século II, a tradição cristã identifica o discípulo amado com João, filho de Zebedeu — que, curiosamente, nunca é citado pelo nome no Evangelho de João. Alguns estudiosos propõem outras identificações ou veem nele também uma figura simbólica do discípulo fiel.",
          ),
          b(
            "resumo",
            "Uma testemunha",
            "O final do Evangelho diz que esse discípulo é quem dá testemunho dessas coisas e as escreveu, e que “sabemos que o seu testemunho é verdadeiro” — uma voz no plural, provavelmente da comunidade ligada a ele.",
            "João 21:24",
          ),
        ],
        exercises: [
          mc(
            "O Evangelho de João diz o nome do “discípulo amado”?",
            ["Não, ele não é nomeado", "Sim, é Pedro", "Sim, é Tomé", "Sim, é Judas"],
            0,
            "O texto nunca diz seu nome.",
            "João 13:23",
          ),
          tf(
            "A identificação do discípulo amado com João é uma tradição antiga, mas não está escrita explicitamente no Evangelho.",
            true,
            "É uma tradição desde o século II; o texto não nomeia o discípulo.",
            "João 21:20-24",
          ),
          match(
            "Associe cada cena ao capítulo de João.",
            [
              ["Última ceia", "João 13"],
              ["Aos pés da cruz", "João 19"],
              ["Correndo ao túmulo", "João 20"],
              ["À beira do lago", "João 21"],
            ],
            "Onde o discípulo amado aparece.",
            "João 13-21",
          ),
          fill(
            "O final do Evangelho diz que esse discípulo dá",
            "dessas coisas.",
            ["testemunho", "ordens", "esmolas"],
            0,
            "João 21:24.",
            "João 21:24",
          ),
          mc(
            "Qual frase é mais precisa?",
            [
              "A tradição identifica o discípulo amado com João; há estudiosos que propõem outras leituras",
              "O texto prova que é João",
              "Ninguém nunca associou o discípulo amado a João",
              "O discípulo amado é João Batista",
            ],
            0,
            "Há tradição e debate.",
            "João 13:23; 21:24",
          ),
        ],
        takeaways: [
          "O “discípulo amado” aparece em cenas decisivas do Evangelho de João.",
          "A tradição o identifica com João, mas o texto não o nomeia.",
          "O Evangelho o apresenta como testemunha.",
        ],
        reflection: "Ser lembrado como “alguém amado” — o que isso desperta em você?",
      },
    ],
    review: {
      slug: "joao-u1-revisao",
      title: "Revisão: O chamado de João",
      intro: "Pescador, filho do trovão, discípulo próximo. Vamos relembrar quem é João.",
      extra: [
        match(
          "Associe cada informação sobre João à sua fonte.",
          [
            ["Filho de Zebedeu", "Marcos 1"],
            ["Boanerges", "Marcos 3"],
            ["“Coluna” da comunidade", "Gálatas 2"],
          ],
          "O que os textos dizem sobre João.",
          "Marcos 1:19; 3:17; Gálatas 2:9",
        ),
        tf(
          "O apóstolo João e João Batista são pessoas diferentes.",
          true,
          "João Batista batizava no Jordão; João, filho de Zebedeu, era pescador e apóstolo.",
          "Marcos 1:4, 19",
        ),
        mc(
          "Qual é a diferença entre um fato do texto e uma tradição sobre João?",
          [
            "“Filho de Zebedeu” está no texto; “discípulo amado = João” é tradição",
            "Não há diferença",
            "Tudo sobre João é tradição",
            "Tudo sobre João está explícito no texto",
          ],
          0,
          "É importante distinguir o que o texto diz do que a tradição interpreta.",
          "Marcos 1:19; João 21:24",
        ),
      ],
      takeaways: [
        "João, filho de Zebedeu, foi chamado como pescador.",
        "Os Evangelhos mostram seu temperamento e seu aprendizado.",
        "O texto e a tradição dizem coisas diferentes sobre ele — vale distinguir.",
      ],
    },
  },
  {
    slug: "joao-u2-nos-evangelhos",
    title: "João nos relatos",
    description: "Da preparação da Páscoa ao túmulo vazio e aos primeiros dias da igreja.",
    scene: "city",
    lessons: [
      {
        slug: "j2-preparando-a-pascoa",
        title: "Preparando a Páscoa",
        objective: "Conhecer a missão dada a Pedro e João antes da última ceia.",
        references: ["Lucas 22:7-13", "João 13:21-26"],
        context: "Chega o dia da festa em que se sacrificava o cordeiro pascal.",
        blocks: [
          b(
            "resumo",
            "Uma missão a dois",
            "Lucas conta que Jesus enviou Pedro e João para preparar a Páscoa. Eles perguntam onde, e Jesus diz que encontrariam um homem carregando um cântaro de água, que os levaria a uma casa com uma sala grande no andar de cima.",
            "Lucas 22:8-12",
          ),
          b(
            "resumo",
            "Tudo como foi dito",
            "Eles vão, encontram tudo como Jesus tinha dito e preparam a Páscoa.",
            "Lucas 22:13",
          ),
          b(
            "resumo",
            "Na mesa",
            "Durante a ceia, em João, o discípulo amado está reclinado ao lado de Jesus. Pedro faz sinal para que ele pergunte quem iria trair Jesus.",
            "João 13:23-25",
          ),
        ],
        exercises: [
          mc(
            "Segundo Lucas, quem Jesus enviou para preparar a Páscoa?",
            ["Pedro e João", "Tiago e André", "Judas e Tomé", "Filipe e Mateus"],
            0,
            "Lucas 22:8.",
            "Lucas 22:8",
          ),
          fill(
            "Eles encontrariam um homem carregando um",
            "de água.",
            ["cântaro", "barco", "balde de ouro"],
            0,
            "Lucas 22:10.",
            "Lucas 22:10",
          ),
          tf(
            "A sala preparada ficava no andar de cima de uma casa.",
            true,
            "Lucas 22:12.",
            "Lucas 22:12",
          ),
          mc(
            "Na ceia, quem pede ao discípulo amado que pergunte quem trairia Jesus?",
            ["Pedro", "Judas", "Tomé", "Tiago"],
            0,
            "João 13:24.",
            "João 13:24",
          ),
          order(
            "Ordene os acontecimentos.",
            ["Jesus envia Pedro e João", "Encontram o homem com o cântaro", "Preparam a Páscoa", "Ceia com os discípulos"],
            "Lucas 22:8-14.",
            "Lucas 22:8-14",
          ),
        ],
        takeaways: [
          "Pedro e João são enviados para preparar a Páscoa.",
          "Encontram tudo como Jesus disse.",
          "Na ceia, o discípulo amado está ao lado de Jesus.",
        ],
        reflection: "Preparar algo para os outros também é uma forma de cuidado. O que você gosta de preparar?",
      },
      {
        slug: "j2-ao-pe-da-cruz",
        title: "Ao pé da cruz",
        objective: "Conhecer a cena do discípulo amado e de Maria junto à cruz.",
        references: ["João 19:25-27", "Marcos 15:40-41"],
        context: "Enquanto muitos tinham fugido, algumas pessoas permaneceram perto da cruz.",
        blocks: [
          b(
            "resumo",
            "Quem estava lá",
            "O Evangelho de João menciona, junto à cruz, a mãe de Jesus, a irmã dela, Maria, mulher de Clopas, e Maria Madalena — e também o discípulo amado.",
            "João 19:25-26",
          ),
          b(
            "resumo",
            "“Eis a tua mãe”",
            "Jesus diz à sua mãe: “Mulher, eis o teu filho”, e ao discípulo: “Eis a tua mãe”. A partir daquela hora, o discípulo a recebeu em sua casa.",
            "João 19:26-27",
          ),
          b(
            "tradicoes",
            "Leituras da cena",
            "A cena é lida como gesto de cuidado de Jesus com sua mãe. Algumas tradições, especialmente a católica e a ortodoxa, também veem nela um sentido simbólico: Maria como mãe dos discípulos. Como o discípulo não é nomeado, sua identificação com João vem da tradição.",
          ),
        ],
        exercises: [
          mc(
            "Segundo João 19, quem estava junto à cruz?",
            ["A mãe de Jesus, outras mulheres e o discípulo amado", "Todos os Doze", "Pilatos e Herodes", "Ninguém"],
            0,
            "João 19:25-26.",
            "João 19:25-26",
          ),
          fill(
            "Jesus diz ao discípulo: “Eis a tua",
            "”.",
            ["mãe", "casa", "missão"],
            0,
            "João 19:27.",
            "João 19:27",
          ),
          tf(
            "O discípulo recebeu a mãe de Jesus em sua casa.",
            true,
            "João 19:27.",
            "João 19:27",
          ),
          mc(
            "Qual mulher que estava junto à cruz depois encontrou o túmulo vazio?",
            ["Maria Madalena", "Marta", "Lídia", "Rode"],
            0,
            "João 19:25; 20:1.",
            "João 20:1",
          ),
          mc(
            "Qual afirmação é mais precisa sobre o discípulo junto à cruz?",
            [
              "O texto o chama de discípulo amado; a identificação com João vem da tradição",
              "O texto diz claramente que era Pedro",
              "O texto diz que era João Batista",
              "Não havia nenhum discípulo",
            ],
            0,
            "O texto não nomeia o discípulo.",
            "João 19:26",
          ),
        ],
        takeaways: [
          "Algumas mulheres e o discípulo amado ficam junto à cruz.",
          "Jesus confia sua mãe ao discípulo, e o discípulo a ele.",
          "A cena tem leituras de cuidado e de sentido simbólico.",
        ],
        reflection: "Ficar perto em um momento difícil é um presente. Quem esteve perto de você?",
      },
      {
        slug: "j2-correndo-ao-tumulo",
        title: "Correndo até o túmulo",
        objective: "Conhecer a corrida de Pedro e do outro discípulo ao túmulo vazio.",
        references: ["João 20:1-10"],
        context: "Maria Madalena encontra a pedra retirada do túmulo e corre para avisar Pedro e o discípulo amado.",
        blocks: [
          b(
            "resumo",
            "Uma corrida",
            "Pedro e o outro discípulo correm juntos, mas o outro corre mais depressa e chega primeiro. Ele se inclina, vê as faixas de linho, mas não entra.",
            "João 20:3-5",
          ),
          b(
            "resumo",
            "Pedro entra",
            "Pedro chega e entra no túmulo. Vê as faixas de linho e o pano que tinha estado sobre a cabeça de Jesus, dobrado num lugar à parte.",
            "João 20:6-7",
          ),
          b(
            "resumo",
            "“Viu e creu”",
            "Então o outro discípulo também entra, “viu e creu”. O texto observa que eles ainda não tinham compreendido a Escritura sobre a ressurreição.",
            "João 20:8-9",
          ),
        ],
        exercises: [
          mc(
            "Quem chegou primeiro ao túmulo?",
            ["O outro discípulo", "Pedro", "Maria Madalena com os dois", "Tomé"],
            0,
            "João 20:4.",
            "João 20:4",
          ),
          tf(
            "O outro discípulo entrou no túmulo antes de Pedro.",
            false,
            "Ele chegou primeiro, mas Pedro entrou antes.",
            "João 20:5-8",
          ),
          fill(
            "Ao entrar, o outro discípulo “viu e",
            "”.",
            ["creu", "fugiu", "chorou"],
            0,
            "João 20:8.",
            "João 20:8",
          ),
          order(
            "Ordene o relato.",
            ["Maria Madalena avisa os discípulos", "Os dois correm ao túmulo", "Pedro entra e vê as faixas", "O outro discípulo entra e crê"],
            "João 20:1-8.",
            "João 20:1-8",
          ),
          mc(
            "O que estava dobrado num lugar à parte no túmulo?",
            ["O pano que estava sobre a cabeça de Jesus", "As sandálias", "Um rolo das Escrituras", "Uma coroa"],
            0,
            "João 20:7.",
            "João 20:7",
          ),
        ],
        takeaways: [
          "Pedro e o discípulo amado correm ao túmulo.",
          "O outro discípulo chega primeiro, mas Pedro entra antes.",
          "Ao ver o túmulo vazio, o discípulo “viu e creu”.",
        ],
        reflection: "Que notícia faria você sair correndo?",
      },
      "p2-restauracao",
      "p3-porta-formosa",
    ],
    review: {
      slug: "joao-u2-revisao",
      title: "Revisão: João nos relatos",
      intro: "Da sala no andar de cima à Porta Formosa. Vamos relembrar.",
      extra: [
        order(
          "Ordene os acontecimentos.",
          ["Preparação da Páscoa", "Ao pé da cruz", "Corrida ao túmulo", "Encontro à beira do lago", "Cura na Porta Formosa"],
          "Lucas 22; João 19-21; Atos 3.",
          "Lucas 22 - Atos 3",
        ),
        match(
          "Associe cada cena ao que o texto diz explicitamente.",
          [
            ["Preparação da Páscoa", "Lucas nomeia Pedro e João"],
            ["Porta Formosa", "Atos nomeia Pedro e João"],
            ["Ao pé da cruz", "O texto fala do discípulo amado, sem nome"],
          ],
          "Distinguir o que o texto diz do que a tradição interpreta.",
          "Lucas 22:8; Atos 3:1; João 19:26",
        ),
        tf(
          "Pedro e João aparecem juntos em vários relatos.",
          true,
          "Lucas 22 e Atos 3-4, por exemplo.",
          "Lucas 22:8; Atos 3:1",
        ),
      ],
      takeaways: [
        "João aparece com Pedro na preparação da Páscoa e em Atos.",
        "O discípulo amado está na cruz, no túmulo e no lago.",
        "Vale distinguir os relatos que nomeiam João das identificações tradicionais.",
      ],
    },
  },
  {
    slug: "joao-u3-evangelho",
    title: "Introdução ao Evangelho de João",
    description: "Autoria, prólogo, sinais, as declarações “Eu sou” e encontros marcantes.",
    scene: "village",
    lessons: [
      {
        slug: "j3-quem-escreveu",
        title: "Quem escreveu o quarto Evangelho?",
        objective: "Conhecer a tradição e o debate sobre a autoria do Evangelho de João.",
        references: ["João 21:24-25", "Apocalipse 1:9", "1 João 1:1-4"],
        context: "Como os outros Evangelhos, o Evangelho de João não traz o nome do autor no próprio texto.",
        blocks: [
          b(
            "tradicoes",
            "A tradição",
            "No século II, Irineu de Lião escreveu que João, o discípulo do Senhor, publicou o Evangelho quando vivia em Éfeso. Essa atribuição ao apóstolo João tornou-se a tradição da Igreja.",
          ),
          b(
            "tradicoes",
            "O debate",
            "Muitos estudiosos entendem que o Evangelho, na forma final, foi escrito por volta do fim do século I, a partir do testemunho do discípulo amado e com participação de uma comunidade ligada a ele — como sugere o “nós” de João 21:24.",
            "João 21:24",
          ),
          b(
            "explicacao",
            "Outros textos com o nome de João",
            "Três cartas (1, 2 e 3 João) e o Apocalipse também são associados a João. O autor do Apocalipse se apresenta como João, na ilha de Patmos. Se todos esses textos vêm da mesma pessoa é uma pergunta discutida desde a Antiguidade.",
            "Apocalipse 1:9",
          ),
        ],
        exercises: [
          tf(
            "O Evangelho de João traz o nome do autor no próprio texto.",
            false,
            "O texto não se nomeia; a atribuição vem da tradição.",
            "João 21:24",
          ),
          mc(
            "Qual autor do século II atribuiu o Evangelho a João, em Éfeso?",
            ["Irineu de Lião", "Agostinho", "Martinho Lutero", "Jerônimo"],
            0,
            "Irineu escreveu por volta de 180 d.C.",
            "Tradição cristã",
          ),
          fill(
            "O autor do Apocalipse diz que estava na ilha de",
            ".",
            ["Patmos", "Chipre", "Malta"],
            0,
            "Apocalipse 1:9.",
            "Apocalipse 1:9",
          ),
          mc(
            "Qual afirmação descreve melhor a questão da autoria?",
            [
              "A tradição atribui ao apóstolo João; muitos estudiosos falam de um testemunho com participação de uma comunidade",
              "Todos concordam que foi escrito por Paulo",
              "Não existe nenhuma tradição sobre isso",
              "O próprio texto diz “eu, João, filho de Zebedeu”",
            ],
            0,
            "Há tradição e debate acadêmico.",
            "João 21:24",
          ),
          match(
            "Associe cada texto à sua relação com o nome João.",
            [
              ["Evangelho de João", "Atribuído pela tradição"],
              ["Apocalipse", "O autor se apresenta como João"],
              ["1 João", "Carta tradicionalmente associada a João"],
            ],
            "Textos joaninos.",
            "Apocalipse 1:9; 1 João 1:1",
          ),
        ],
        takeaways: [
          "O Evangelho de João não nomeia seu autor.",
          "A tradição o atribui ao apóstolo João; há debate entre estudiosos.",
          "Cartas e Apocalipse também são associados a João.",
        ],
        reflection: "Saber como um texto chegou até nós muda a forma como você o lê?",
      },
      {
        slug: "j3-no-principio-era-o-verbo",
        title: "No princípio era o Verbo",
        objective: "Conhecer o prólogo do Evangelho de João.",
        references: ["João 1:1-18", "Gênesis 1:1"],
        context: "O Evangelho de João não começa com o nascimento de Jesus, mas com um poema.",
        blocks: [
          b(
            "resumo",
            "Um começo que lembra Gênesis",
            "“No princípio era o Verbo” — a abertura ecoa “No princípio” de Gênesis. O texto diz que o Verbo estava com Deus, que tudo foi feito por meio dele, e que nele estava a vida, a luz das pessoas.",
            "João 1:1-4; Gênesis 1:1",
          ),
          b(
            "explicacao",
            "Verbo, Palavra, Logos",
            "“Verbo” traduz o grego Logos, que também pode ser traduzido como “Palavra”. Por isso algumas Bíblias trazem “No princípio era a Palavra”.",
          ),
          b(
            "resumo",
            "A luz e a testemunha",
            "O prólogo apresenta João Batista como testemunha da luz — ele não era a luz. E afirma que o Verbo se fez carne e habitou entre nós.",
            "João 1:6-8, 14",
          ),
        ],
        exercises: [
          fill(
            "“No princípio era o",
            "”.",
            ["Verbo", "mar", "templo"],
            0,
            "João 1:1.",
            "João 1:1",
          ),
          mc(
            "Qual livro a abertura de João ecoa?",
            ["Gênesis", "Levítico", "Juízes", "Ester"],
            0,
            "Gênesis 1:1 também começa com “No princípio”.",
            "Gênesis 1:1; João 1:1",
          ),
          tf(
            "Segundo o prólogo, João Batista era a luz.",
            false,
            "Ele veio como testemunha da luz.",
            "João 1:8",
          ),
          match(
            "Associe cada termo ao seu sentido.",
            [
              ["Logos", "Palavra grega traduzida por Verbo"],
              ["Prólogo", "Abertura poética do Evangelho"],
              ["Testemunha", "Papel de João Batista"],
            ],
            "Termos do prólogo.",
            "João 1:1-18",
          ),
          fill(
            "O prólogo afirma que o Verbo se fez",
            "e habitou entre nós.",
            ["carne", "rei", "templo"],
            0,
            "João 1:14.",
            "João 1:14",
          ),
        ],
        takeaways: [
          "O Evangelho de João começa com um poema sobre o Verbo.",
          "“Verbo” traduz Logos, também “Palavra”.",
          "João Batista é testemunha da luz.",
        ],
        reflection: "Que “luz” você gostaria de ver brilhar mais na sua vida?",
      },
      {
        slug: "j3-os-sinais",
        title: "Os sinais",
        objective: "Conhecer os sinais narrados no Evangelho de João e seu propósito.",
        references: ["João 2:11", "João 4:46-54", "João 9:1-7", "João 11:38-44", "João 20:30-31"],
        context: "O Evangelho de João seleciona alguns milagres e os chama de sinais.",
        blocks: [
          b(
            "explicacao",
            "Sete sinais",
            "Muitos leitores contam sete sinais antes da ressurreição: água em vinho, cura do filho de um oficial, cura de um paralítico, multiplicação dos pães, Jesus andando sobre as águas, cura de um cego de nascença e a volta de Lázaro à vida.",
          ),
          b(
            "resumo",
            "O cego de nascença",
            "Jesus faz lama, passa nos olhos de um homem cego de nascença e o manda lavar-se no tanque de Siloé. O homem volta enxergando.",
            "João 9:1-7",
          ),
          b(
            "resumo",
            "Para que vocês creiam",
            "Perto do fim, o Evangelho diz que Jesus fez muitos outros sinais, mas esses foram escritos para que os leitores creiam e tenham vida.",
            "João 20:30-31",
          ),
        ],
        exercises: [
          mc(
            "Qual foi o primeiro sinal em João?",
            ["Água em vinho em Caná", "A volta de Lázaro", "A cura do cego", "A multiplicação dos pães"],
            0,
            "João 2:11.",
            "João 2:11",
          ),
          fill(
            "O cego de nascença foi lavar-se no tanque de",
            ".",
            ["Siloé", "Betesda", "Jordão"],
            0,
            "João 9:7.",
            "João 9:7",
          ),
          tf(
            "O Evangelho diz que os sinais foram escritos para que os leitores creiam.",
            true,
            "João 20:31.",
            "João 20:31",
          ),
          match(
            "Associe cada sinal ao seu capítulo.",
            [
              ["Água em vinho", "João 2"],
              ["Cego de nascença", "João 9"],
              ["Lázaro", "João 11"],
            ],
            "Sinais em João.",
            "João 2; 9; 11",
          ),
          mc(
            "Qual destes NÃO costuma estar entre os sete sinais de João?",
            ["A travessia do mar Vermelho", "A multiplicação dos pães", "A cura do filho do oficial", "A volta de Lázaro"],
            0,
            "A travessia do mar está no Êxodo.",
            "João 2-11",
          ),
        ],
        takeaways: [
          "João chama os milagres de sinais.",
          "Muitos leitores contam sete sinais.",
          "Os sinais foram escritos para que os leitores creiam.",
        ],
        reflection: "O cego passou a ver. O que você gostaria de enxergar com mais clareza?",
      },
      {
        slug: "j3-eu-sou",
        title: "As declarações “Eu sou”",
        objective: "Conhecer as frases “Eu sou” de Jesus no Evangelho de João.",
        references: ["João 6:35", "João 8:12", "João 10:9", "João 10:11", "João 11:25", "João 14:6", "João 15:1"],
        context: "No Evangelho de João, Jesus usa imagens do dia a dia para falar de si mesmo.",
        blocks: [
          b(
            "resumo",
            "Sete imagens",
            "Jesus diz: Eu sou o pão da vida; a luz do mundo; a porta; o bom pastor; a ressurreição e a vida; o caminho, a verdade e a vida; a videira verdadeira.",
            "João 6:35; 8:12; 10:9, 11; 11:25; 14:6; 15:1",
          ),
          b(
            "contexto",
            "Um eco do Êxodo",
            "Muitos leitores percebem nas palavras “Eu sou” um eco do nome revelado a Moisés na sarça: “Eu Sou o que Sou”.",
            "Êxodo 3:14; João 8:58",
          ),
          b(
            "resumo",
            "O bom pastor",
            "Jesus diz que o bom pastor dá a vida pelas ovelhas e que conhece as suas, e elas o conhecem.",
            "João 10:11-14",
          ),
        ],
        exercises: [
          match(
            "Complete as declarações de Jesus.",
            [
              ["Eu sou o pão", "da vida"],
              ["Eu sou a luz", "do mundo"],
              ["Eu sou o bom", "pastor"],
              ["Eu sou a videira", "verdadeira"],
            ],
            "Declarações “Eu sou” no Evangelho de João.",
            "João 6:35; 8:12; 10:11; 15:1",
          ),
          fill(
            "“Eu sou o caminho, a verdade e a",
            "”.",
            ["vida", "luz", "porta"],
            0,
            "João 14:6.",
            "João 14:6",
          ),
          tf(
            "Muitos leitores veem nas palavras “Eu sou” um eco da sarça ardente.",
            true,
            "Êxodo 3:14 e João 8:58.",
            "Êxodo 3:14; João 8:58",
          ),
          mc(
            "Segundo João 10, o que o bom pastor faz pelas ovelhas?",
            ["Dá a vida por elas", "Vende as ovelhas", "Deixa-as sozinhas", "Leva-as ao mercado"],
            0,
            "João 10:11.",
            "João 10:11",
          ),
          mc(
            "Em qual contexto Jesus diz “Eu sou a ressurreição e a vida”?",
            ["Antes de chamar Lázaro do túmulo", "Na tentação no deserto", "Na Porta Formosa", "No batismo"],
            0,
            "João 11:25.",
            "João 11:25",
          ),
        ],
        takeaways: [
          "Jesus usa sete imagens com “Eu sou”.",
          "Elas ecoam o nome revelado a Moisés.",
          "O bom pastor dá a vida pelas ovelhas.",
        ],
        reflection: "Qual dessas imagens fala mais com você hoje?",
      },
      {
        slug: "j3-encontros",
        title: "Encontros: Nicodemos e a samaritana",
        objective: "Conhecer dois encontros marcantes do Evangelho de João.",
        references: ["João 3:1-17", "João 4:1-42"],
        context: "O Evangelho de João tem conversas longas de Jesus com pessoas muito diferentes.",
        blocks: [
          b(
            "resumo",
            "Nicodemos à noite",
            "Nicodemos, um fariseu e líder dos judeus, vai até Jesus de noite. Jesus fala de nascer de novo (ou “do alto”) e diz que Deus amou o mundo de tal maneira que deu o seu Filho.",
            "João 3:1-16",
          ),
          b(
            "resumo",
            "A mulher junto ao poço",
            "Ao meio-dia, junto ao poço de Jacó, Jesus pede água a uma mulher samaritana. Ela se surpreende, porque judeus e samaritanos não se davam. Jesus fala de uma água viva, e ela vai contar à cidade sobre ele.",
            "João 4:5-29",
          ),
          b(
            "explicacao",
            "Dois contrastes",
            "Um homem respeitado, que vem à noite; uma mulher estrangeira, que encontra Jesus em pleno dia. O Evangelho mostra Jesus conversando com os dois.",
          ),
        ],
        exercises: [
          mc(
            "Em que momento Nicodemos vai até Jesus?",
            ["De noite", "Ao meio-dia", "No sábado de manhã", "Durante uma festa"],
            0,
            "João 3:2.",
            "João 3:2",
          ),
          fill(
            "Jesus fala com a samaritana junto ao poço de",
            ".",
            ["Jacó", "Moisés", "Davi"],
            0,
            "João 4:6.",
            "João 4:6",
          ),
          tf(
            "A samaritana se surpreendeu porque judeus e samaritanos não se davam.",
            true,
            "João 4:9.",
            "João 4:9",
          ),
          match(
            "Associe cada personagem ao que Jesus fala.",
            [
              ["Nicodemos", "Nascer de novo (do alto)"],
              ["Samaritana", "Água viva"],
            ],
            "João 3 e 4.",
            "João 3:3; 4:10",
          ),
          mc(
            "O que a samaritana fez depois da conversa?",
            ["Foi contar à cidade sobre Jesus", "Voltou para casa em silêncio", "Pediu dinheiro", "Mudou-se para Jerusalém"],
            0,
            "João 4:28-29.",
            "João 4:28-29",
          ),
        ],
        takeaways: [
          "Nicodemos, um líder, conversa com Jesus à noite.",
          "A samaritana encontra Jesus ao meio-dia junto ao poço.",
          "Jesus conversa com pessoas muito diferentes.",
        ],
        reflection: "Com qual desses dois encontros você se identifica mais?",
      },
    ],
    review: {
      slug: "joao-u3-revisao",
      title: "Revisão: O Evangelho de João",
      intro: "Do “No princípio” às conversas junto ao poço. Vamos relembrar o quarto Evangelho.",
      extra: [
        match(
          "Associe cada trecho ao seu tema.",
          [
            ["João 1", "O Verbo e a luz"],
            ["João 3", "Nicodemos"],
            ["João 4", "A samaritana"],
            ["João 20:30-31", "Propósito dos sinais"],
          ],
          "Partes do Evangelho de João.",
          "João 1; 3; 4; 20",
        ),
        tf(
          "A autoria do Evangelho de João tem uma tradição antiga e também é debatida por estudiosos.",
          true,
          "Irineu atribui a João; estudiosos discutem o papel do discípulo amado e da comunidade.",
          "João 21:24",
        ),
        mc(
          "Qual destas frases é uma declaração “Eu sou” do Evangelho de João?",
          ["“Eu sou a luz do mundo”", "“Eis-me aqui; envia-me”", "“Não tenho prata nem ouro”", "“Que fazes aqui?”"],
          0,
          "João 8:12.",
          "João 8:12",
        ),
      ],
      takeaways: [
        "O Evangelho de João começa com o Verbo e a luz.",
        "Sinais e declarações “Eu sou” revelam quem é Jesus.",
        "Autoria: tradição antiga e debate acadêmico caminham juntos.",
      ],
    },
  },
];
