import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

/**
 * Jornada com Moisés. Compartilha as cinco lições de "Moisés e o Êxodo"
 * da jornada geral (g04-*), mantendo ordem e progresso próprios.
 */
export const moisesUnits: UnitDef[] = [
  {
    slug: "moises-u1-nascimento-e-chamado",
    title: "Nascimento e chamado",
    description: "Do cesto no Nilo ao encontro na sarça e à primeira conversa com o faraó.",
    scene: "river",
    lessons: [
      "g04-bebe-no-nilo",
      {
        slug: "m1-principe-e-fugitivo",
        title: "De príncipe a fugitivo",
        objective: "Entender por que Moisés deixou o Egito e como recomeçou em Midiã.",
        references: ["Êxodo 2:11-25"],
        context:
          "Moisés cresceu como filho adotivo da filha do faraó, mas sabia que pertencia ao povo hebreu. Um dia, isso o leva a agir — e a fugir.",
        blocks: [
          b(
            "resumo",
            "Uma reação violenta",
            "Já adulto, Moisés vê um egípcio espancando um hebreu. Ele mata o egípcio e esconde o corpo na areia. No dia seguinte, tenta separar dois hebreus que brigavam, e um deles pergunta: “Quem te pôs como chefe e juiz sobre nós?”.",
            "Êxodo 2:11-14",
          ),
          b(
            "resumo",
            "Junto ao poço",
            "Com medo do faraó, Moisés foge para Midiã. Junto a um poço, defende as sete filhas de um sacerdote local contra pastores que as expulsavam. Ele é acolhido na casa, casa-se com Zípora e tem um filho, Gérson.",
            "Êxodo 2:15-22",
          ),
          b(
            "resumo",
            "Enquanto isso, no Egito",
            "O texto lembra que os israelitas continuavam gemendo sob a escravidão, e que Deus ouviu o clamor deles e se lembrou da aliança com Abraão, Isaque e Jacó.",
            "Êxodo 2:23-25",
          ),
          b(
            "contexto",
            "Um sogro com dois nomes",
            "O sacerdote de Midiã aparece como Reuel em Êxodo 2 e como Jetro em Êxodo 3. Estudiosos explicam isso de formas diferentes — por exemplo, como um título ou como tradições distintas reunidas no texto.",
            "Êxodo 2:18; 3:1",
          ),
        ],
        exercises: [
          mc(
            "Por que Moisés fugiu do Egito?",
            ["Teve medo do faraó depois de matar um egípcio", "Foi expulso por seus irmãos", "Queria conhecer o mar", "Foi enviado como embaixador"],
            0,
            "Quando o faraó soube do ocorrido, quis matar Moisés, que fugiu.",
            "Êxodo 2:15",
          ),
          fill(
            "Em Midiã, Moisés defendeu as filhas do sacerdote junto a um",
            ".",
            ["poço", "templo", "rio"],
            0,
            "A cena acontece junto a um poço.",
            "Êxodo 2:15-17",
          ),
          match(
            "Associe as pessoas da família de Moisés em Midiã.",
            [
              ["Zípora", "Esposa"],
              ["Gérson", "Filho"],
              ["Reuel / Jetro", "Sogro, sacerdote de Midiã"],
            ],
            "Moisés forma família em Midiã.",
            "Êxodo 2:21-22; 3:1",
          ),
          tf(
            "Enquanto Moisés vivia em Midiã, o texto diz que Deus ouviu o clamor dos israelitas.",
            true,
            "Êxodo 2:23-25 fala desse clamor e da lembrança da aliança.",
            "Êxodo 2:23-25",
          ),
          order(
            "Ordene os acontecimentos.",
            ["Moisés mata um egípcio", "Dois hebreus questionam sua autoridade", "Moisés foge para Midiã", "Casa-se com Zípora"],
            "Êxodo 2:11-22.",
            "Êxodo 2:11-22",
          ),
        ],
        takeaways: [
          "Moisés agiu com violência e precisou fugir do Egito.",
          "Em Midiã, defendeu as filhas de um sacerdote e formou família.",
          "O texto lembra que Deus ouviu o clamor do povo.",
        ],
        reflection: "Moisés recomeçou longe de casa. O que um recomeço pode ensinar?",
      },
      "g04-sarca-ardente",
      {
        slug: "m1-quem-sou-eu",
        title: "“Quem sou eu?”",
        objective: "Conhecer as objeções de Moisés ao chamado e as respostas que recebe.",
        references: ["Êxodo 3:11-12", "Êxodo 4:1-17"],
        context: "Diante da sarça, Moisés não aceita o chamado de imediato. Ele apresenta uma série de dúvidas.",
        blocks: [
          b(
            "resumo",
            "Dúvidas sinceras",
            "Moisés pergunta: “Quem sou eu para ir ao faraó?”. A resposta é: “Eu estarei com você”. Depois, ele teme que o povo não acredite nele.",
            "Êxodo 3:11-12; 4:1",
          ),
          b(
            "resumo",
            "Três sinais",
            "Deus dá sinais a Moisés: o cajado se transforma em serpente e volta a ser cajado; sua mão fica doente e é curada; e a água do Nilo derramada no chão se tornaria sangue.",
            "Êxodo 4:2-9",
          ),
          b(
            "resumo",
            "“Não sou bom com as palavras”",
            "Moisés diz que tem dificuldade para falar. Deus responde que Arão, seu irmão, falaria por ele, e que Moisés levaria o cajado para realizar os sinais.",
            "Êxodo 4:10-17",
          ),
        ],
        exercises: [
          fill(
            "Quando Moisés pergunta “Quem sou eu?”, Deus responde: “Eu estarei",
            "”.",
            ["com você", "longe", "no templo"],
            0,
            "A resposta não fala das capacidades de Moisés, mas da presença de Deus.",
            "Êxodo 3:12",
          ),
          match(
            "Associe cada sinal ao que acontece.",
            [
              ["Cajado", "Vira serpente"],
              ["Mão", "Fica doente e é curada"],
              ["Água do Nilo", "Se tornaria sangue"],
            ],
            "Os três sinais de Êxodo 4.",
            "Êxodo 4:2-9",
          ),
          mc(
            "Quem falaria pelo povo junto com Moisés?",
            ["Arão", "Josué", "Calebe", "Jetro"],
            0,
            "Arão, irmão de Moisés, seria seu porta-voz.",
            "Êxodo 4:14-16",
          ),
          tf(
            "Moisés aceitou o chamado imediatamente, sem nenhuma dúvida.",
            false,
            "Ele apresentou várias objeções.",
            "Êxodo 3:11-4:13",
          ),
          mc(
            "Qual dificuldade Moisés apresenta em Êxodo 4:10?",
            ["Não ser bom com as palavras", "Não saber nadar", "Ter medo de animais", "Não conhecer o caminho"],
            0,
            "Ele diz que é lento para falar.",
            "Êxodo 4:10",
          ),
        ],
        takeaways: [
          "Moisés tem dúvidas sinceras diante do chamado.",
          "Recebe a promessa de presença e três sinais.",
          "Arão é chamado para falar junto com ele.",
        ],
        reflection: "Qual “quem sou eu?” costuma aparecer quando você recebe um desafio?",
      },
      {
        slug: "m1-diante-do-farao",
        title: "Diante do faraó",
        objective: "Conhecer o primeiro encontro de Moisés e Arão com o faraó.",
        references: ["Êxodo 4:27-31", "Êxodo 5:1-23", "Êxodo 6:1-9"],
        context: "Moisés volta ao Egito e reencontra Arão. Juntos, falam ao povo e depois ao faraó.",
        blocks: [
          b(
            "resumo",
            "“Deixa o meu povo ir”",
            "Moisés e Arão pedem ao faraó que deixe o povo ir celebrar uma festa no deserto. O faraó responde que não conhece o Senhor e não deixará Israel sair.",
            "Êxodo 5:1-2",
          ),
          b(
            "resumo",
            "Tijolos sem palha",
            "Em vez de aliviar, o faraó endurece o trabalho: os israelitas teriam de produzir a mesma quantidade de tijolos, mas buscando eles mesmos a palha.",
            "Êxodo 5:6-19",
          ),
          b(
            "resumo",
            "Desânimo e promessa",
            "Os capatazes israelitas reclamam com Moisés, e Moisés reclama com Deus. Deus reafirma que libertaria o povo e o tomaria como seu, mas o povo, desanimado pela dura escravidão, não consegue ouvir.",
            "Êxodo 5:20-6:9",
          ),
        ],
        exercises: [
          mc(
            "Como o faraó responde ao primeiro pedido?",
            ["Diz que não conhece o Senhor e recusa", "Liberta o povo na hora", "Pede três dias para pensar", "Convida Moisés para morar no palácio"],
            0,
            "Êxodo 5:2.",
            "Êxodo 5:2",
          ),
          fill(
            "O faraó mandou que os israelitas fizessem tijolos sem receber",
            ".",
            ["palha", "água", "pedras"],
            0,
            "Eles teriam de buscar a palha sozinhos.",
            "Êxodo 5:7",
          ),
          tf(
            "Depois do primeiro encontro, a situação do povo ficou mais difícil.",
            true,
            "O trabalho foi endurecido.",
            "Êxodo 5:6-9",
          ),
          order(
            "Ordene os acontecimentos.",
            ["Moisés reencontra Arão", "Falam com o faraó", "O trabalho é endurecido", "Deus reafirma a promessa"],
            "Êxodo 4:27-6:8.",
            "Êxodo 4:27-6:8",
          ),
          mc(
            "Por que o povo não conseguiu ouvir a promessa?",
            ["Estava desanimado pela dura escravidão", "Não entendia a língua", "Estava viajando", "Estava em festa"],
            0,
            "Êxodo 6:9.",
            "Êxodo 6:9",
          ),
        ],
        takeaways: [
          "Moisés e Arão pedem ao faraó que deixe o povo ir.",
          "O faraó endurece o trabalho: tijolos sem palha.",
          "Mesmo no desânimo, a promessa de libertação é reafirmada.",
        ],
        reflection: "Às vezes as coisas pioram antes de melhorar. Como lidar com isso sem perder a esperança?",
      },
    ],
    review: {
      slug: "moises-u1-revisao",
      title: "Revisão: Nascimento e chamado",
      intro: "Do Nilo a Midiã e de volta ao Egito. Vamos relembrar o começo da jornada de Moisés.",
      extra: [
        order(
          "Ordene a vida de Moisés até aqui.",
          ["Cesto no Nilo", "Fuga para Midiã", "Sarça ardente", "Encontro com o faraó"],
          "Êxodo 2-5.",
          "Êxodo 2-5",
        ),
        match(
          "Associe cada pessoa a Moisés.",
          [
            ["Arão", "Irmão e porta-voz"],
            ["Zípora", "Esposa"],
            ["Filha do faraó", "Mãe adotiva"],
          ],
          "Pessoas importantes na vida de Moisés.",
          "Êxodo 2; 4",
        ),
        tf(
          "Moisés apresentou dúvidas ao receber o chamado.",
          true,
          "Ele perguntou “Quem sou eu?” e levantou outras objeções.",
          "Êxodo 3:11-4:13",
        ),
      ],
      takeaways: [
        "Moisés foi protegido ao nascer e recomeçou em Midiã.",
        "Na sarça, recebeu um chamado — e teve dúvidas.",
        "O primeiro encontro com o faraó foi difícil.",
      ],
    },
  },
  {
    slug: "moises-u2-exodo",
    title: "O Êxodo",
    description: "A saída do Egito e os primeiros desafios no deserto.",
    scene: "desert",
    lessons: [
      "g04-pragas-e-pascoa",
      "g04-travessia-do-mar",
      {
        slug: "m2-mara-e-elim",
        title: "Águas amargas, águas doces",
        objective: "Conhecer o primeiro desafio no deserto depois da travessia.",
        references: ["Êxodo 15:22-27"],
        context: "Logo depois de cantar a libertação, o povo enfrenta o deserto de Sur — e a sede.",
        blocks: [
          b(
            "resumo",
            "Três dias sem água",
            "O povo caminha três dias pelo deserto sem encontrar água. Em Mara, encontram água, mas ela é amarga, e o povo reclama com Moisés.",
            "Êxodo 15:22-24",
          ),
          b(
            "resumo",
            "Um pedaço de madeira",
            "Moisés clama a Deus, que lhe mostra um pedaço de madeira. Moisés o lança na água, e ela se torna doce.",
            "Êxodo 15:25",
          ),
          b(
            "resumo",
            "Um oásis",
            "Depois, eles chegam a Elim, onde havia doze fontes de água e setenta palmeiras, e acampam ali.",
            "Êxodo 15:27",
          ),
          b(
            "explicacao",
            "O nome Mara",
            "“Mara” significa “amarga”. Muitos nomes de lugares na Bíblia lembram o que aconteceu ali.",
          ),
        ],
        exercises: [
          fill(
            "Em Mara, a água era",
            ".",
            ["amarga", "salgada", "quente"],
            0,
            "Por isso o lugar se chamou Mara, “amarga”.",
            "Êxodo 15:23",
          ),
          mc(
            "O que Moisés lançou na água de Mara?",
            ["Um pedaço de madeira", "Uma pedra", "Sal", "O cajado de Arão"],
            0,
            "Êxodo 15:25.",
            "Êxodo 15:25",
          ),
          match(
            "Associe cada lugar ao que havia nele.",
            [
              ["Mara", "Água amarga"],
              ["Elim", "Doze fontes e setenta palmeiras"],
            ],
            "Dois lugares bem diferentes no mesmo caminho.",
            "Êxodo 15:23-27",
          ),
          tf(
            "O povo ficou três dias sem encontrar água antes de chegar a Mara.",
            true,
            "Êxodo 15:22.",
            "Êxodo 15:22",
          ),
          order(
            "Ordene os acontecimentos.",
            ["Cântico após a travessia", "Três dias sem água", "Água amarga em Mara", "Acampamento em Elim"],
            "Êxodo 15.",
            "Êxodo 15",
          ),
        ],
        takeaways: [
          "Depois da libertação, o deserto traz sede e reclamações.",
          "Em Mara, a água amarga se torna doce.",
          "Em Elim, o povo encontra fontes e palmeiras.",
        ],
        reflection: "Depois de uma grande vitória, vem às vezes um deserto. Já viveu algo assim?",
      },
      {
        slug: "m2-mana",
        title: "Maná: o pão de cada dia",
        objective: "Conhecer o relato do maná e das codornizes no deserto.",
        references: ["Êxodo 16:1-35"],
        context: "No deserto de Sim, o povo sente fome e lembra com saudade da comida do Egito.",
        blocks: [
          b(
            "resumo",
            "Pão do céu",
            "Deus promete pão do céu. À tarde chegam codornizes e, pela manhã, o chão amanhece coberto de algo fino como geada. Os israelitas perguntam: “O que é isso?” — em hebraico, “man hu”, origem do nome maná.",
            "Êxodo 16:12-15, 31",
          ),
          b(
            "resumo",
            "Só o necessário",
            "Cada um deveria recolher o necessário para o dia. Quem guardava para o dia seguinte encontrava o maná estragado. No sexto dia, recolhiam o dobro, para descansar no sábado.",
            "Êxodo 16:16-26",
          ),
          b(
            "resumo",
            "Quarenta anos",
            "O texto diz que os israelitas comeram maná durante os quarenta anos no deserto, até chegarem à terra habitada.",
            "Êxodo 16:35",
          ),
        ],
        exercises: [
          mc(
            "O nome “maná” vem de uma pergunta. Qual?",
            ["“O que é isso?”", "“Onde está a água?”", "“Quem é você?”", "“Quando chegaremos?”"],
            0,
            "“Man hu” significa “o que é isso?”.",
            "Êxodo 16:15",
          ),
          match(
            "Associe cada alimento ao momento em que aparecia.",
            [
              ["Codornizes", "À tarde"],
              ["Maná", "Pela manhã"],
            ],
            "Êxodo 16:13.",
            "Êxodo 16:13-14",
          ),
          tf(
            "Quem guardava maná para o dia seguinte (fora do sexto dia) o encontrava estragado.",
            true,
            "Êxodo 16:20.",
            "Êxodo 16:19-20",
          ),
          fill(
            "No sexto dia, o povo recolhia o",
            "para descansar no sábado.",
            ["dobro", "triplo", "mínimo"],
            0,
            "Êxodo 16:22-26.",
            "Êxodo 16:22",
          ),
          mc(
            "Por quanto tempo, segundo o texto, os israelitas comeram maná?",
            ["Quarenta anos", "Quarenta dias", "Sete anos", "Um ano"],
            0,
            "Êxodo 16:35.",
            "Êxodo 16:35",
          ),
        ],
        takeaways: [
          "No deserto, Deus provê codornizes e maná.",
          "Maná vem da pergunta “o que é isso?”.",
          "O povo aprende a recolher o necessário para cada dia.",
        ],
        reflection: "O que significa para você viver “um dia de cada vez”?",
      },
      {
        slug: "m2-rocha-e-amaleque",
        title: "Água da rocha e braços erguidos",
        objective: "Conhecer os acontecimentos de Refidim.",
        references: ["Êxodo 17:1-16"],
        context: "Em Refidim, o povo enfrenta mais uma vez a falta de água e, logo depois, um ataque.",
        blocks: [
          b(
            "resumo",
            "A rocha",
            "Sem água, o povo discute com Moisés. Deus o orienta a bater na rocha no Horebe com o cajado, e dela sai água. O lugar é chamado Massá e Meribá, nomes ligados a “prova” e “discussão”.",
            "Êxodo 17:1-7",
          ),
          b(
            "resumo",
            "Mãos levantadas",
            "Os amalequitas atacam. Josué lidera a batalha, enquanto Moisés fica no alto do monte com as mãos levantadas. Quando ele cansa, Arão e Hur sustentam seus braços até o pôr do sol.",
            "Êxodo 17:8-13",
          ),
          b(
            "explicacao",
            "Ninguém caminha sozinho",
            "A imagem de Arão e Hur sustentando os braços de Moisés ficou conhecida como símbolo de apoio mútuo. Também é a primeira vez que Josué aparece, ele que depois sucederia Moisés.",
            "Êxodo 17:12",
          ),
        ],
        exercises: [
          mc(
            "O que Moisés faz para que saia água da rocha?",
            ["Bate na rocha com o cajado", "Canta um salmo", "Cava um poço", "Derrama óleo"],
            0,
            "Êxodo 17:6.",
            "Êxodo 17:6",
          ),
          match(
            "Associe cada pessoa ao que fez na batalha.",
            [
              ["Josué", "Liderou o combate"],
              ["Moisés", "Ficou com as mãos levantadas"],
              ["Arão e Hur", "Sustentaram os braços de Moisés"],
            ],
            "Êxodo 17:9-12.",
            "Êxodo 17:9-12",
          ),
          tf(
            "Arão e Hur ajudaram Moisés a manter os braços erguidos até o pôr do sol.",
            true,
            "Êxodo 17:12.",
            "Êxodo 17:12",
          ),
          fill(
            "O lugar da água da rocha foi chamado Massá e",
            ".",
            ["Meribá", "Mara", "Betel"],
            0,
            "Êxodo 17:7.",
            "Êxodo 17:7",
          ),
          mc(
            "Quem aparece pela primeira vez neste relato e depois sucederá Moisés?",
            ["Josué", "Calebe", "Arão", "Jetro"],
            0,
            "Josué lidera a batalha contra Amaleque.",
            "Êxodo 17:9",
          ),
        ],
        takeaways: [
          "Em Refidim, água sai da rocha.",
          "Arão e Hur sustentam os braços de Moisés na batalha.",
          "Josué aparece como líder pela primeira vez.",
        ],
        reflection: "Quem são as pessoas que “sustentam seus braços” quando você cansa?",
      },
    ],
    review: {
      slug: "moises-u2-revisao",
      title: "Revisão: O Êxodo",
      intro: "Do Egito ao deserto! Vamos relembrar a saída e os primeiros desafios.",
      extra: [
        order(
          "Ordene o caminho do povo.",
          ["Páscoa no Egito", "Travessia do mar", "Mara", "Maná no deserto de Sim", "Refidim"],
          "Êxodo 12-17.",
          "Êxodo 12-17",
        ),
        match(
          "Associe cada necessidade à provisão.",
          [
            ["Sede em Mara", "Água amarga que se torna doce"],
            ["Fome no deserto", "Maná e codornizes"],
            ["Sede em Refidim", "Água da rocha"],
          ],
          "Provisões no deserto.",
          "Êxodo 15-17",
        ),
        tf(
          "No deserto, o povo reclamou várias vezes.",
          true,
          "As reclamações aparecem em Mara, no deserto de Sim e em Refidim.",
          "Êxodo 15:24; 16:2; 17:2",
        ),
      ],
      takeaways: [
        "A libertação do Egito é seguida por desafios no deserto.",
        "Água, maná e codornizes marcam a provisão no caminho.",
        "A liderança de Moisés conta com apoio de outros.",
      ],
    },
  },
  {
    slug: "moises-u3-alianca-e-deserto",
    title: "Aliança e deserto",
    description: "O Sinai, o bezerro de ouro, o tabernáculo e o fim da caminhada de Moisés.",
    scene: "mountain",
    lessons: [
      "g04-dez-mandamentos",
      {
        slug: "m3-bezerro-de-ouro",
        title: "O bezerro de ouro",
        objective: "Conhecer a crise do bezerro de ouro e a renovação da aliança.",
        references: ["Êxodo 32:1-20", "Êxodo 32:30-32", "Êxodo 34:1-10, 29"],
        context: "Enquanto Moisés está no monte, o povo, impaciente, pede a Arão um deus que pudessem ver.",
        blocks: [
          b(
            "resumo",
            "Um ídolo de ouro",
            "Arão recolhe brincos de ouro e faz um bezerro. O povo faz festa diante dele. Ao descer do monte e ver a cena, Moisés quebra as tábuas da lei.",
            "Êxodo 32:1-19",
          ),
          b(
            "resumo",
            "Moisés intercede",
            "Moisés pede perdão a Deus pelo povo, chegando a dizer que preferia ser riscado do livro de Deus a ver o povo rejeitado.",
            "Êxodo 32:30-32",
          ),
          b(
            "resumo",
            "Novas tábuas",
            "Deus manda Moisés preparar novas tábuas e se apresenta como compassivo, misericordioso, lento para a ira e cheio de amor fiel. Ao descer, o rosto de Moisés brilhava.",
            "Êxodo 34:1-7, 29",
          ),
        ],
        exercises: [
          mc(
            "Quem fez o bezerro de ouro?",
            ["Arão", "Moisés", "Josué", "Miriã"],
            0,
            "O povo pediu e Arão fez o bezerro.",
            "Êxodo 32:2-4",
          ),
          tf(
            "Ao ver o bezerro, Moisés quebrou as tábuas da lei.",
            true,
            "Êxodo 32:19.",
            "Êxodo 32:19",
          ),
          fill(
            "Em Êxodo 34, Deus se apresenta como compassivo e lento para a",
            ".",
            ["ira", "palavra", "viagem"],
            0,
            "Êxodo 34:6.",
            "Êxodo 34:6",
          ),
          order(
            "Ordene os acontecimentos.",
            ["O povo pede um deus visível", "Arão faz o bezerro", "Moisés quebra as tábuas", "Moisés intercede pelo povo", "Novas tábuas são preparadas"],
            "Êxodo 32-34.",
            "Êxodo 32-34",
          ),
          mc(
            "O que acontecia com o rosto de Moisés ao descer do monte com as novas tábuas?",
            ["Brilhava", "Estava coberto de cinzas", "Estava triste", "Estava pintado"],
            0,
            "Êxodo 34:29.",
            "Êxodo 34:29",
          ),
        ],
        takeaways: [
          "Impaciente, o povo adora um bezerro de ouro.",
          "Moisés quebra as tábuas e intercede pelo povo.",
          "A aliança é renovada com novas tábuas.",
        ],
        reflection: "O que costuma ocupar o lugar central da sua vida quando a espera fica longa?",
      },
      {
        slug: "m3-tabernaculo",
        title: "Uma tenda no meio do povo",
        objective: "Entender o que era o tabernáculo e para que servia.",
        references: ["Êxodo 25:8-9", "Êxodo 25:10-22", "Êxodo 35:30-35", "Êxodo 36:3-7", "Êxodo 40:34-38"],
        context: "No Sinai, Moisés recebe instruções para construir uma tenda especial, que acompanharia o povo pelo deserto.",
        blocks: [
          b(
            "resumo",
            "“Que habite no meio deles”",
            "Deus pede um santuário para habitar no meio do povo. O tabernáculo era uma tenda portátil, montada e desmontada a cada etapa da viagem.",
            "Êxodo 25:8-9",
          ),
          b(
            "resumo",
            "A arca da aliança",
            "Dentro do tabernáculo ficava a arca da aliança, uma caixa de madeira revestida de ouro, onde foram guardadas as tábuas da lei.",
            "Êxodo 25:10-22; 40:20",
          ),
          b(
            "resumo",
            "Artesãos e ofertas",
            "Artesãos como Bezalel e Aoliabe lideraram a construção. O povo trouxe tantas ofertas que foi preciso pedir que parassem de trazer.",
            "Êxodo 35:30-35; 36:5-7",
          ),
          b(
            "resumo",
            "A nuvem",
            "Quando tudo ficou pronto, a nuvem cobriu a tenda. Enquanto a nuvem ficava sobre ela, o povo permanecia; quando se levantava, eles seguiam viagem.",
            "Êxodo 40:34-38",
          ),
        ],
        exercises: [
          mc(
            "O que era o tabernáculo?",
            ["Uma tenda portátil de adoração", "Um palácio de pedra", "Um navio", "Uma torre"],
            0,
            "Era uma tenda que acompanhava o povo pelo deserto.",
            "Êxodo 25:8-9",
          ),
          fill(
            "Dentro da arca da aliança ficavam as",
            "da lei.",
            ["tábuas", "coroas", "moedas"],
            0,
            "Êxodo 40:20.",
            "Êxodo 40:20",
          ),
          tf(
            "O povo trouxe ofertas a mais do que o necessário para a construção.",
            true,
            "Foi preciso pedir que parassem.",
            "Êxodo 36:5-7",
          ),
          match(
            "Associe cada elemento à sua função.",
            [
              ["Tabernáculo", "Lugar de encontro no meio do povo"],
              ["Arca da aliança", "Guardava as tábuas da lei"],
              ["Nuvem", "Indicava quando partir"],
            ],
            "Elementos do tabernáculo.",
            "Êxodo 25; 40",
          ),
          mc(
            "Qual artesão é citado como líder da construção?",
            ["Bezalel", "Barnabé", "Baruc", "Boaz"],
            0,
            "Bezalel e Aoliabe lideraram o trabalho.",
            "Êxodo 35:30-35",
          ),
        ],
        takeaways: [
          "O tabernáculo era uma tenda portátil para o encontro com Deus.",
          "A arca da aliança guardava as tábuas da lei.",
          "A nuvem sobre a tenda indicava quando partir.",
        ],
        reflection: "A ideia de Deus “habitando no meio” do povo diz algo sobre a vida cotidiana?",
      },
      {
        slug: "m3-doze-espias",
        title: "Os doze espias",
        objective: "Conhecer o relato dos espias e o motivo dos quarenta anos no deserto.",
        references: ["Números 13:1-33", "Números 14:1-10, 26-35"],
        context: "Perto de Canaã, Moisés envia doze homens, um de cada tribo, para observar a terra.",
        blocks: [
          b(
            "resumo",
            "Leite e mel",
            "Depois de quarenta dias, os espias voltam com um cacho de uvas tão grande que era carregado numa vara por dois homens. Dizem que a terra “mana leite e mel”.",
            "Números 13:23-27",
          ),
          b(
            "resumo",
            "Medo e confiança",
            "Dez espias dizem que os habitantes eram fortes demais e espalham medo. Josué e Calebe dizem que era possível entrar, confiando em Deus.",
            "Números 13:28-33; 14:6-9",
          ),
          b(
            "resumo",
            "Quarenta anos",
            "O povo se revolta e quer voltar ao Egito. O texto diz que aquela geração ficaria no deserto quarenta anos — um ano para cada dia de observação —, e que Josué e Calebe entrariam na terra.",
            "Números 14:26-35",
          ),
        ],
        exercises: [
          mc(
            "Quantos espias Moisés enviou?",
            ["Doze", "Sete", "Dois", "Quarenta"],
            0,
            "Um de cada tribo.",
            "Números 13:1-16",
          ),
          fill(
            "Os espias disseram que a terra “mana leite e",
            "”.",
            ["mel", "vinho", "azeite"],
            0,
            "Números 13:27.",
            "Números 13:27",
          ),
          match(
            "Associe cada grupo à sua reação.",
            [
              ["Dez espias", "Espalharam medo"],
              ["Josué e Calebe", "Confiaram que era possível entrar"],
            ],
            "Números 13-14.",
            "Números 13:31-14:9",
          ),
          tf(
            "Segundo o texto, os quarenta anos no deserto correspondem aos quarenta dias de observação.",
            true,
            "Um ano para cada dia.",
            "Números 14:34",
          ),
          mc(
            "O que os espias trouxeram como amostra da terra?",
            ["Um cacho de uvas enorme", "Uma estátua", "Um saco de ouro", "Um rolo de pergaminho"],
            0,
            "Números 13:23.",
            "Números 13:23",
          ),
        ],
        takeaways: [
          "Doze espias observam Canaã por quarenta dias.",
          "Dez espalham medo; Josué e Calebe confiam.",
          "A geração que se revoltou permanece quarenta anos no deserto.",
        ],
        reflection: "Diante de algo novo, você costuma enxergar mais os “gigantes” ou as “uvas”?",
      },
      {
        slug: "m3-monte-nebo",
        title: "Do monte Nebo",
        objective: "Conhecer o fim da vida de Moisés e a passagem da liderança a Josué.",
        references: ["Deuteronômio 31:1-8", "Deuteronômio 34:1-12"],
        context: "O livro de Deuteronômio reúne discursos finais de Moisés ao povo, nas planícies de Moabe, antes da entrada em Canaã.",
        blocks: [
          b(
            "resumo",
            "Sê forte e corajoso",
            "Moisés apresenta Josué como seu sucessor diante de todo o Israel e o encoraja a ser forte e corajoso, pois Deus iria à sua frente.",
            "Deuteronômio 31:7-8",
          ),
          b(
            "resumo",
            "Ver a terra de longe",
            "Moisés sobe ao monte Nebo, ao topo do Pisga, e de lá vê a terra prometida. Ele morre em Moabe, aos cento e vinte anos, e o texto diz que ninguém conhece o lugar de sua sepultura.",
            "Deuteronômio 34:1-7",
          ),
          b(
            "resumo",
            "Face a face",
            "O livro termina dizendo que nunca mais surgiu em Israel um profeta como Moisés, a quem o Senhor conhecia face a face.",
            "Deuteronômio 34:10",
          ),
          b(
            "contexto",
            "Quem escreveu o Pentateuco?",
            "A tradição judaica e cristã atribui os cinco primeiros livros a Moisés. Muitos estudiosos entendem que esses livros foram reunidos e editados ao longo de séculos — o próprio relato da morte de Moisés, em Deuteronômio 34, costuma ser citado nessa discussão.",
          ),
        ],
        exercises: [
          mc(
            "Quem sucede Moisés na liderança do povo?",
            ["Josué", "Arão", "Calebe", "Samuel"],
            0,
            "Deuteronômio 31:7.",
            "Deuteronômio 31:7-8",
          ),
          fill(
            "Moisés vê a terra prometida do alto do monte",
            ".",
            ["Nebo", "Sinai", "Carmelo"],
            0,
            "Deuteronômio 34:1.",
            "Deuteronômio 34:1",
          ),
          tf(
            "Segundo Deuteronômio, o lugar da sepultura de Moisés é bem conhecido.",
            false,
            "O texto diz que ninguém conhece o lugar.",
            "Deuteronômio 34:6",
          ),
          mc(
            "Com quantos anos Moisés morre, segundo o texto?",
            ["120", "80", "40", "175"],
            0,
            "Deuteronômio 34:7.",
            "Deuteronômio 34:7",
          ),
          mc(
            "Qual afirmação sobre a autoria do Pentateuco é mais equilibrada?",
            [
              "A tradição atribui a Moisés; muitos estudiosos veem um processo longo de redação",
              "Todos concordam que Moisés escreveu cada palavra",
              "Ninguém nunca associou Moisés ao Pentateuco",
              "Foi escrito por Josué",
            ],
            0,
            "Há a atribuição tradicional e o debate acadêmico.",
            "Deuteronômio 34",
          ),
        ],
        takeaways: [
          "Josué é apresentado como sucessor de Moisés.",
          "Moisés vê a terra do monte Nebo e morre em Moabe.",
          "A autoria do Pentateuco tem uma tradição e um debate acadêmico.",
        ],
        reflection: "Moisés preparou outra pessoa para continuar. Quem você ajuda a crescer?",
      },
    ],
    review: {
      slug: "moises-u3-revisao",
      title: "Revisão: Aliança e deserto",
      intro: "Do Sinai ao monte Nebo. Vamos relembrar a última etapa da jornada de Moisés.",
      extra: [
        order(
          "Ordene os acontecimentos.",
          ["Dez Mandamentos no Sinai", "Bezerro de ouro", "Construção do tabernáculo", "Os doze espias", "Morte de Moisés no Nebo"],
          "Êxodo 20 a Deuteronômio 34.",
          "Êxodo 20 - Deuteronômio 34",
        ),
        match(
          "Associe cada pessoa a um momento.",
          [
            ["Calebe", "Espia que confiou"],
            ["Bezalel", "Artesão do tabernáculo"],
            ["Josué", "Sucessor de Moisés"],
          ],
          "Personagens desta unidade.",
          "Êxodo 35; Números 14; Deuteronômio 31",
        ),
        tf(
          "A aliança foi renovada com novas tábuas depois do bezerro de ouro.",
          true,
          "Êxodo 34.",
          "Êxodo 34:1-10",
        ),
      ],
      takeaways: [
        "A aliança do Sinai é quebrada e renovada.",
        "O tabernáculo acompanha o povo no deserto.",
        "Moisés passa a liderança a Josué antes da entrada na terra.",
      ],
    },
  },
];
