import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

/**
 * Jornada com Paulo. Compartilha "A conversão de Saulo" e "O concílio de
 * Jerusalém" com a jornada geral.
 */
export const pauloUnits: UnitDef[] = [
  {
    slug: "paulo-u1-conversao",
    title: "Conversão",
    description: "Quem era Saulo de Tarso e como sua vida mudou de direção.",
    scene: "road",
    lessons: [
      {
        slug: "pa1-saulo-de-tarso",
        title: "Saulo de Tarso",
        objective: "Conhecer a origem e a formação de Paulo.",
        references: ["Atos 22:3", "Filipenses 3:4-6", "Atos 18:1-3", "Atos 22:25-28"],
        context: "Antes de ser conhecido como apóstolo, Paulo era Saulo, um judeu fervoroso nascido fora da terra de Israel.",
        blocks: [
          b(
            "resumo",
            "Nascido em Tarso",
            "Paulo diz que nasceu em Tarso, na Cilícia (na atual Turquia), e foi educado em Jerusalém, aos pés de Gamaliel, um mestre respeitado da Lei.",
            "Atos 22:3",
          ),
          b(
            "resumo",
            "“Hebreu de hebreus”",
            "Na carta aos Filipenses, ele se apresenta como da tribo de Benjamim, hebreu de hebreus, fariseu quanto à Lei — e conta que perseguia a igreja.",
            "Filipenses 3:5-6",
          ),
          b(
            "contexto",
            "Fazedor de tendas e cidadão romano",
            "Atos conta que Paulo trabalhava fazendo tendas e que era cidadão romano de nascimento — algo que mais tarde fará diferença em sua história.",
            "Atos 18:3; 22:28",
          ),
        ],
        exercises: [
          mc(
            "Em que cidade Paulo nasceu?",
            ["Tarso", "Jerusalém", "Roma", "Damasco"],
            0,
            "Atos 22:3.",
            "Atos 22:3",
          ),
          fill(
            "Paulo foi educado aos pés do mestre",
            ".",
            ["Gamaliel", "Barnabé", "Nicodemos"],
            0,
            "Atos 22:3.",
            "Atos 22:3",
          ),
          match(
            "Associe cada característica de Paulo à sua fonte.",
            [
              ["Tribo de Benjamim, fariseu", "Filipenses 3"],
              ["Fazedor de tendas", "Atos 18"],
              ["Cidadão romano de nascimento", "Atos 22"],
            ],
            "O que os textos dizem sobre Paulo.",
            "Filipenses 3:5; Atos 18:3; 22:28",
          ),
          tf(
            "Antes da conversão, Paulo perseguia a igreja.",
            true,
            "Filipenses 3:6; Gálatas 1:13.",
            "Filipenses 3:6",
          ),
          mc(
            "Qual profissão Atos atribui a Paulo?",
            ["Fazedor de tendas", "Pescador", "Carpinteiro", "Coletor de impostos"],
            0,
            "Atos 18:3.",
            "Atos 18:3",
          ),
        ],
        takeaways: [
          "Paulo nasceu em Tarso e estudou em Jerusalém com Gamaliel.",
          "Era fariseu, da tribo de Benjamim, e perseguia a igreja.",
          "Trabalhava fazendo tendas e era cidadão romano.",
        ],
        reflection: "Que partes da sua história ajudaram a formar quem você é hoje?",
      },
      "g09-conversao-de-saulo",
      {
        slug: "pa1-ananias",
        title: "Ananias e as escamas",
        objective: "Conhecer o papel de Ananias na história de Saulo.",
        references: ["Atos 9:10-19"],
        context: "Em Damasco, um discípulo chamado Ananias recebe uma missão difícil.",
        blocks: [
          b(
            "resumo",
            "Uma missão com medo",
            "Ananias recebe a orientação de ir até Saulo. Ele hesita: tinha ouvido falar de todo o mal que Saulo fizera. A resposta é que Saulo era um instrumento escolhido para levar o nome de Jesus às nações.",
            "Atos 9:10-15",
          ),
          b(
            "resumo",
            "“Irmão Saulo”",
            "Ananias vai, impõe as mãos sobre ele e o chama de “irmão Saulo”. Algo como escamas cai de seus olhos, e Saulo volta a enxergar.",
            "Atos 9:17-18",
          ),
          b(
            "resumo",
            "Batismo e alimento",
            "Saulo é batizado, se alimenta e recupera as forças, passando alguns dias com os discípulos de Damasco.",
            "Atos 9:18-19",
          ),
        ],
        exercises: [
          tf(
            "Ananias hesitou antes de ir ao encontro de Saulo.",
            true,
            "Atos 9:13-14.",
            "Atos 9:13-14",
          ),
          fill(
            "Ananias chamou Saulo de “",
            "Saulo”.",
            ["irmão", "inimigo", "senhor"],
            0,
            "Atos 9:17.",
            "Atos 9:17",
          ),
          mc(
            "O que caiu dos olhos de Saulo?",
            ["Algo como escamas", "Lágrimas de ouro", "Areia", "Um véu de linho"],
            0,
            "Atos 9:18.",
            "Atos 9:18",
          ),
          mc(
            "Como Saulo é descrito na resposta a Ananias?",
            ["Um instrumento escolhido", "Um rei", "Um profeta do Antigo Testamento", "Um sacerdote"],
            0,
            "Atos 9:15.",
            "Atos 9:15",
          ),
          order(
            "Ordene o relato.",
            ["Ananias recebe a missão", "Hesita por medo", "Vai e impõe as mãos", "Saulo volta a enxergar e é batizado"],
            "Atos 9:10-18.",
            "Atos 9:10-18",
          ),
        ],
        takeaways: [
          "Ananias tem medo, mas aceita a missão.",
          "Ele chama o antigo perseguidor de “irmão”.",
          "Saulo volta a enxergar e é batizado.",
        ],
        reflection: "Ananias acolheu alguém que temia. O que isso exigiria de você?",
      },
      {
        slug: "pa1-fuga-num-cesto",
        title: "Fuga pelo muro num cesto",
        objective: "Conhecer os primeiros passos de Saulo como seguidor de Jesus.",
        references: ["Atos 9:19-25", "2 Coríntios 11:32-33", "Gálatas 1:15-18"],
        context: "Depois de ser batizado, Saulo começa a falar de Jesus em Damasco — e isso causa espanto.",
        blocks: [
          b(
            "resumo",
            "O perseguidor anuncia",
            "Saulo passa a pregar nas sinagogas que Jesus é o Filho de Deus. As pessoas se espantam: não era ele quem perseguia os seguidores desse nome?",
            "Atos 9:20-21",
          ),
          b(
            "resumo",
            "Um cesto no muro",
            "Quando planejam matá-lo, os discípulos descem Saulo pelo muro da cidade, à noite, dentro de um cesto. Paulo lembra esse episódio numa de suas cartas.",
            "Atos 9:23-25; 2 Coríntios 11:32-33",
          ),
          b(
            "contexto",
            "Arábia e três anos",
            "Na carta aos Gálatas, Paulo conta que, depois do chamado, foi para a Arábia, voltou a Damasco e só três anos depois subiu a Jerusalém para conhecer Pedro. Atos e Gálatas trazem detalhes diferentes, e estudiosos buscam harmonizá-los.",
            "Gálatas 1:17-18",
          ),
        ],
        exercises: [
          mc(
            "Como Saulo escapou de Damasco?",
            ["Descido pelo muro dentro de um cesto", "Num navio", "Disfarçado de soldado", "Por um túnel"],
            0,
            "Atos 9:25.",
            "Atos 9:25",
          ),
          tf(
            "As pessoas de Damasco se espantaram ao ver o antigo perseguidor anunciar Jesus.",
            true,
            "Atos 9:21.",
            "Atos 9:21",
          ),
          fill(
            "Em Gálatas, Paulo diz que foi para a",
            "antes de voltar a Damasco.",
            ["Arábia", "Grécia", "Espanha"],
            0,
            "Gálatas 1:17.",
            "Gálatas 1:17",
          ),
          mc(
            "Em qual carta Paulo lembra a fuga no cesto?",
            ["2 Coríntios", "Romanos", "Filemom", "Tito"],
            0,
            "2 Coríntios 11:32-33.",
            "2 Coríntios 11:33",
          ),
          match(
            "Associe cada fonte ao que ela destaca.",
            [
              ["Atos 9", "Pregação em Damasco e fuga no cesto"],
              ["Gálatas 1", "Ida à Arábia e encontro com Pedro após três anos"],
            ],
            "Duas fontes sobre o início da trajetória de Paulo.",
            "Atos 9; Gálatas 1",
          ),
        ],
        takeaways: [
          "Saulo começa a anunciar Jesus em Damasco.",
          "Escapa de um plano contra sua vida num cesto pelo muro.",
          "Atos e Gálatas trazem detalhes complementares.",
        ],
        reflection: "Recomeçar pode gerar desconfiança nos outros. Como lidar com isso?",
      },
      {
        slug: "pa1-barnabe-e-antioquia",
        title: "Barnabé e Antioquia",
        objective: "Conhecer o papel de Barnabé e da comunidade de Antioquia na vida de Paulo.",
        references: ["Atos 9:26-28", "Atos 11:19-26", "Atos 13:1-3"],
        context: "Em Jerusalém, os discípulos tinham medo de Saulo. Alguém precisou abrir a porta.",
        blocks: [
          b(
            "resumo",
            "Alguém que acredita",
            "Barnabé leva Saulo até os apóstolos e conta como ele tinha encontrado o Senhor no caminho e falado com coragem em Damasco.",
            "Atos 9:26-27",
          ),
          b(
            "resumo",
            "Em Antioquia",
            "Mais tarde, Barnabé vai a Tarso buscar Saulo e o leva a Antioquia, onde ensinam por um ano. Foi em Antioquia que os discípulos foram chamados de “cristãos” pela primeira vez.",
            "Atos 11:25-26",
          ),
          b(
            "resumo",
            "Enviados",
            "A comunidade de Antioquia, em oração, separa Barnabé e Saulo para uma missão. Eles impõem as mãos sobre os dois e os enviam.",
            "Atos 13:1-3",
          ),
          b(
            "explicacao",
            "Filho da consolação",
            "Barnabé é um apelido que Atos traduz como “filho da consolação” (ou “do encorajamento”).",
            "Atos 4:36",
          ),
        ],
        exercises: [
          mc(
            "Quem apresentou Saulo aos apóstolos em Jerusalém?",
            ["Barnabé", "Pedro", "Ananias", "Estêvão"],
            0,
            "Atos 9:27.",
            "Atos 9:27",
          ),
          fill(
            "Em Antioquia, os discípulos foram chamados de",
            "pela primeira vez.",
            ["cristãos", "nazarenos", "apóstolos"],
            0,
            "Atos 11:26.",
            "Atos 11:26",
          ),
          tf(
            "Barnabé foi até Tarso buscar Saulo.",
            true,
            "Atos 11:25.",
            "Atos 11:25",
          ),
          mc(
            "O que significa o apelido Barnabé, segundo Atos?",
            ["Filho da consolação", "Filho do trovão", "Pedra", "Deus é meu juiz"],
            0,
            "Atos 4:36.",
            "Atos 4:36",
          ),
          order(
            "Ordene a trajetória.",
            ["Barnabé apresenta Saulo aos apóstolos", "Saulo volta a Tarso", "Barnabé o busca e vão a Antioquia", "A comunidade os envia em missão"],
            "Atos 9-13.",
            "Atos 9:27-13:3",
          ),
        ],
        takeaways: [
          "Barnabé confia em Saulo quando outros têm medo.",
          "Em Antioquia, os discípulos são chamados de cristãos.",
          "A comunidade envia Barnabé e Saulo em missão.",
        ],
        reflection: "Quem foi um “Barnabé” para você — alguém que acreditou quando outros duvidavam?",
      },
    ],
    review: {
      slug: "paulo-u1-revisao",
      title: "Revisão: Conversão",
      intro: "De perseguidor a enviado. Vamos relembrar o começo da jornada de Paulo.",
      extra: [
        order(
          "Ordene a trajetória de Saulo.",
          ["Estuda com Gamaliel", "Persegue a igreja", "Encontro no caminho de Damasco", "Fuga no cesto", "Enviado de Antioquia"],
          "Atos 22; 8-9; 13.",
          "Atos 8-13",
        ),
        match(
          "Associe cada pessoa ao seu papel na vida de Saulo.",
          [
            ["Gamaliel", "Mestre da Lei"],
            ["Ananias", "Impôs as mãos e o chamou de irmão"],
            ["Barnabé", "Apresentou-o aos apóstolos"],
          ],
          "Pessoas importantes para Paulo.",
          "Atos 9; 22",
        ),
        tf(
          "Saulo e Paulo são nomes da mesma pessoa.",
          true,
          "Atos 13:9.",
          "Atos 13:9",
        ),
      ],
      takeaways: [
        "Saulo era um fariseu zeloso que perseguia a igreja.",
        "Depois do encontro em Damasco, é acolhido por Ananias e Barnabé.",
        "A comunidade de Antioquia o envia em missão.",
      ],
    },
  },
  {
    slug: "paulo-u2-viagens",
    title: "Viagens",
    description: "Estradas, cidades e navios: as viagens de Paulo pelo Mediterrâneo.",
    scene: "sea",
    lessons: [
      {
        slug: "pa2-primeira-viagem",
        title: "A primeira viagem",
        objective: "Conhecer a primeira viagem missionária de Paulo e Barnabé.",
        references: ["Atos 13:4-14:28"],
        context: "Enviados por Antioquia, Barnabé e Paulo partem levando João Marcos como auxiliar.",
        blocks: [
          b(
            "resumo",
            "Chipre",
            "Eles passam pela ilha de Chipre, terra de Barnabé, e chegam a Pafos. A partir daí, Atos passa a chamar Saulo de Paulo.",
            "Atos 13:4-9",
          ),
          b(
            "resumo",
            "Pelas cidades da Galácia",
            "Seguem para Antioquia da Pisídia, Icônio, Listra e Derbe. Em Listra, depois de uma cura, o povo pensa que são deuses — chama Barnabé de Zeus e Paulo de Hermes —, e eles insistem que são apenas humanos.",
            "Atos 13:14-14:18",
          ),
          b(
            "resumo",
            "Voltar para contar",
            "No fim, voltam a Antioquia e contam à comunidade tudo o que Deus tinha feito e como a porta da fé tinha sido aberta aos gentios.",
            "Atos 14:26-27",
          ),
        ],
        exercises: [
          mc(
            "Qual ilha Paulo e Barnabé visitaram primeiro?",
            ["Chipre", "Malta", "Creta", "Patmos"],
            0,
            "Atos 13:4.",
            "Atos 13:4",
          ),
          match(
            "Associe cada pessoa ao nome que recebeu em Listra.",
            [
              ["Barnabé", "Zeus"],
              ["Paulo", "Hermes"],
            ],
            "Atos 14:12.",
            "Atos 14:12",
          ),
          tf(
            "Paulo e Barnabé aceitaram ser tratados como deuses em Listra.",
            false,
            "Eles insistiram que eram apenas humanos.",
            "Atos 14:14-15",
          ),
          order(
            "Ordene algumas cidades da viagem.",
            ["Pafos (Chipre)", "Antioquia da Pisídia", "Icônio", "Listra"],
            "Atos 13-14.",
            "Atos 13:6-14:8",
          ),
          fill(
            "Ao voltar, contaram como a porta da",
            "tinha sido aberta aos gentios.",
            ["fé", "cidade", "prisão"],
            0,
            "Atos 14:27.",
            "Atos 14:27",
          ),
        ],
        takeaways: [
          "Paulo e Barnabé viajam por Chipre e cidades da Galácia.",
          "Em Listra, recusam ser tratados como deuses.",
          "Voltam a Antioquia contando sobre a fé dos gentios.",
        ],
        reflection: "Voltar e contar o que viveu também faz parte da missão. Com quem você partilha suas descobertas?",
      },
      "g09-concilio-de-jerusalem",
      {
        slug: "pa2-filipos",
        title: "Filipos: Lídia e o carcereiro",
        objective: "Conhecer a chegada da mensagem à Macedônia, na Europa.",
        references: ["Atos 16:9-34", "Filipenses 1:3-5"],
        context: "Numa segunda viagem, agora com Silas, Paulo tem uma visão que o leva à Macedônia.",
        blocks: [
          b(
            "resumo",
            "“Venha para a Macedônia”",
            "À noite, Paulo vê em visão um homem da Macedônia pedindo ajuda. Eles atravessam o mar e chegam a Filipos.",
            "Atos 16:9-12",
          ),
          b(
            "resumo",
            "Lídia",
            "Junto a um rio, encontram mulheres reunidas para orar. Lídia, comerciante de tecido de púrpura, ouve a mensagem, é batizada com sua casa e hospeda os missionários.",
            "Atos 16:13-15",
          ),
          b(
            "resumo",
            "Cânticos à meia-noite",
            "Paulo e Silas são presos. À meia-noite, oram e cantam. Um terremoto abre as portas. O carcereiro, desesperado, pensa em se matar; Paulo grita que todos estão ali. O carcereiro e sua família são batizados.",
            "Atos 16:25-34",
          ),
        ],
        exercises: [
          mc(
            "Quem Paulo viu na visão noturna?",
            ["Um homem da Macedônia pedindo ajuda", "Um anjo com uma espada", "Moisés", "Pedro"],
            0,
            "Atos 16:9.",
            "Atos 16:9",
          ),
          fill(
            "Lídia era comerciante de tecido de",
            ".",
            ["púrpura", "lã", "linho branco"],
            0,
            "Atos 16:14.",
            "Atos 16:14",
          ),
          tf(
            "Na prisão, Paulo e Silas oravam e cantavam à meia-noite.",
            true,
            "Atos 16:25.",
            "Atos 16:25",
          ),
          order(
            "Ordene os acontecimentos em Filipos.",
            ["Visão do macedônio", "Encontro com Lídia junto ao rio", "Prisão de Paulo e Silas", "Batismo do carcereiro"],
            "Atos 16.",
            "Atos 16:9-33",
          ),
          mc(
            "Qual carta Paulo escreveu mais tarde à comunidade dessa cidade?",
            ["Filipenses", "Gálatas", "Romanos", "Colossenses"],
            0,
            "Filipenses 1:1.",
            "Filipenses 1:1",
          ),
        ],
        takeaways: [
          "Uma visão leva Paulo à Macedônia.",
          "Lídia é a primeira pessoa batizada em Filipos, segundo Atos.",
          "Na prisão, Paulo e Silas cantam, e o carcereiro é batizado.",
        ],
        reflection: "Cantar à meia-noite na prisão: o que ajuda você a manter a esperança em momentos difíceis?",
      },
      {
        slug: "pa2-atenas",
        title: "Em Atenas: o deus desconhecido",
        objective: "Conhecer o discurso de Paulo no Areópago.",
        references: ["Atos 17:16-34"],
        context: "Em Atenas, cidade de filósofos, Paulo fica impressionado com a quantidade de altares.",
        blocks: [
          b(
            "resumo",
            "Um altar curioso",
            "Paulo conversa na praça com quem passava, inclusive filósofos. Levado ao Areópago, começa dizendo que tinha visto um altar com a inscrição: “Ao deus desconhecido”.",
            "Atos 17:17-23",
          ),
          b(
            "resumo",
            "Citando poetas",
            "Paulo fala do Deus que fez o mundo e não habita em templos feitos por mãos humanas. Ele cita poetas gregos: “dele também somos geração”.",
            "Atos 17:24-28",
          ),
          b(
            "resumo",
            "Reações diferentes",
            "Quando Paulo fala da ressurreição, alguns zombam, outros dizem que querem ouvir mais, e alguns passam a crer, entre eles Dionísio e uma mulher chamada Dâmaris.",
            "Atos 17:32-34",
          ),
        ],
        exercises: [
          fill(
            "Paulo viu em Atenas um altar com a inscrição: “Ao deus",
            "”.",
            ["desconhecido", "da guerra", "do mar"],
            0,
            "Atos 17:23.",
            "Atos 17:23",
          ),
          mc(
            "Onde Paulo fez seu discurso em Atenas?",
            ["No Areópago", "Na sinagoga de Corinto", "No templo de Jerusalém", "Num navio"],
            0,
            "Atos 17:19-22.",
            "Atos 17:22",
          ),
          tf(
            "No discurso, Paulo cita poetas gregos.",
            true,
            "Atos 17:28.",
            "Atos 17:28",
          ),
          match(
            "Associe as reações ao discurso.",
            [
              ["Alguns", "Zombaram"],
              ["Outros", "Queriam ouvir mais"],
              ["Dionísio e Dâmaris", "Passaram a crer"],
            ],
            "Atos 17:32-34.",
            "Atos 17:32-34",
          ),
          mc(
            "O que a abordagem de Paulo em Atenas mostra?",
            ["Diálogo com a cultura dos ouvintes", "Recusa em conversar", "Uso de milagres apenas", "Silêncio total"],
            0,
            "Paulo parte de algo conhecido pelos atenienses.",
            "Atos 17:22-28",
          ),
        ],
        takeaways: [
          "Em Atenas, Paulo parte do altar “ao deus desconhecido”.",
          "Ele dialoga com a cultura e cita poetas gregos.",
          "As reações ao discurso são variadas.",
        ],
        reflection: "Como você conversa sobre fé com quem pensa diferente?",
      },
      {
        slug: "pa2-naufragio-e-roma",
        title: "Naufrágio e Roma",
        objective: "Conhecer a viagem de Paulo a Roma.",
        references: ["Atos 25:10-12", "Atos 27:13-44", "Atos 28:1-10", "Atos 28:16, 30-31"],
        context: "Preso em Jerusalém e mantido em Cesareia, Paulo apela para ser julgado pelo imperador.",
        blocks: [
          b(
            "resumo",
            "“Apelo para César”",
            "Como cidadão romano, Paulo apela ao imperador, e é enviado de navio para Roma, sob custódia.",
            "Atos 25:11-12",
          ),
          b(
            "resumo",
            "Tempestade",
            "Uma tempestade violenta castiga o navio por muitos dias. Paulo encoraja todos a comer e diz que ninguém perderia a vida. O navio encalha e se despedaça, mas todos chegam à terra.",
            "Atos 27:20-44",
          ),
          b(
            "resumo",
            "Malta e Roma",
            "Eles chegam à ilha de Malta, onde são bem recebidos. Uma víbora se prende à mão de Paulo, mas ele não sofre mal. Em Roma, Paulo fica dois anos numa casa alugada, sob guarda, recebendo a todos e falando com liberdade.",
            "Atos 28:1-6, 30-31",
          ),
        ],
        exercises: [
          mc(
            "Por que Paulo foi enviado a Roma?",
            ["Apelou ao imperador como cidadão romano", "Foi convidado para uma festa", "Fugiu de Jerusalém", "Foi vender tendas"],
            0,
            "Atos 25:11-12.",
            "Atos 25:11-12",
          ),
          fill(
            "Depois do naufrágio, chegaram à ilha de",
            ".",
            ["Malta", "Chipre", "Creta"],
            0,
            "Atos 28:1.",
            "Atos 28:1",
          ),
          tf(
            "Segundo Atos, todos os que estavam no navio chegaram à terra.",
            true,
            "Atos 27:44.",
            "Atos 27:44",
          ),
          order(
            "Ordene a viagem.",
            ["Paulo apela a César", "Tempestade no mar", "Naufrágio", "Chegada a Malta", "Dois anos em Roma"],
            "Atos 25-28.",
            "Atos 25-28",
          ),
          mc(
            "Como termina o livro de Atos?",
            ["Paulo em Roma, anunciando com liberdade", "Paulo voltando a Tarso", "A morte de Paulo", "Paulo em Atenas"],
            0,
            "Atos 28:30-31. A morte de Paulo não é narrada.",
            "Atos 28:30-31",
          ),
        ],
        takeaways: [
          "Paulo apela ao imperador e viaja preso a Roma.",
          "Sobrevive a um naufrágio e chega a Malta.",
          "Atos termina com Paulo em Roma, falando com liberdade.",
        ],
        reflection: "Em meio à tempestade, Paulo encorajou os outros. Quem você pode encorajar hoje?",
      },
    ],
    review: {
      slug: "paulo-u2-revisao",
      title: "Revisão: Viagens",
      intro: "Ilhas, cidades e mares! Vamos relembrar as viagens de Paulo.",
      extra: [
        match(
          "Associe cada lugar ao acontecimento.",
          [
            ["Listra", "Chamados de Zeus e Hermes"],
            ["Filipos", "Lídia e o carcereiro"],
            ["Atenas", "Altar ao deus desconhecido"],
            ["Malta", "A víbora na mão de Paulo"],
          ],
          "Lugares das viagens.",
          "Atos 14; 16; 17; 28",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Primeira viagem", "Concílio de Jerusalém", "Chegada à Macedônia", "Viagem a Roma"],
          "Atos 13-28.",
          "Atos 13-28",
        ),
        tf(
          "O livro de Atos narra a morte de Paulo em Roma.",
          false,
          "Atos termina com Paulo vivo em Roma; sua morte é lembrada pela tradição.",
          "Atos 28:30-31",
        ),
      ],
      takeaways: [
        "Paulo viajou por cidades da Ásia Menor, Grécia e Macedônia.",
        "Dialogou com pessoas muito diferentes.",
        "Atos termina com Paulo em Roma.",
      ],
    },
  },
  {
    slug: "paulo-u3-comunidades-e-cartas",
    title: "Comunidades e cartas",
    description: "Como ler as cartas de Paulo e o que ele escreveu a algumas comunidades.",
    scene: "village",
    lessons: [
      {
        slug: "pa3-cartas-de-paulo",
        title: "Como são as cartas de Paulo?",
        objective: "Conhecer as cartas atribuídas a Paulo e como elas eram escritas.",
        references: ["Romanos 1:1-7", "Romanos 16:22", "1 Tessalonicenses 1:1", "Gálatas 6:11"],
        context: "Paulo acompanhava as comunidades à distância por meio de cartas, que eram lidas em voz alta nas reuniões.",
        blocks: [
          b(
            "explicacao",
            "Treze cartas",
            "O Novo Testamento traz treze cartas que levam o nome de Paulo. Há amplo consenso entre estudiosos de que sete são dele: Romanos, 1 e 2 Coríntios, Gálatas, Filipenses, 1 Tessalonicenses e Filemom. A autoria das outras seis é debatida; a tradição as atribui a Paulo.",
          ),
          b(
            "contexto",
            "Escritas com ajuda",
            "Paulo costumava ditar as cartas. Em Romanos, quem escreveu se apresenta: Tércio. Em Gálatas, Paulo diz que escreve as últimas linhas com sua própria mão, em letras grandes.",
            "Romanos 16:22; Gálatas 6:11",
          ),
          b(
            "explicacao",
            "Uma estrutura parecida",
            "As cartas costumam começar com remetente, destinatários e uma saudação de graça e paz; depois vem uma ação de graças, o corpo da carta e saudações finais. 1 Tessalonicenses é considerada por muitos a carta mais antiga, por volta do ano 50.",
            "1 Tessalonicenses 1:1-2",
          ),
          b(
            "explicacao",
            "E Hebreus?",
            "A carta aos Hebreus não traz o nome do autor. Por muito tempo foi associada a Paulo, mas hoje muitos — incluindo estudiosos de diferentes tradições — consideram seu autor desconhecido.",
          ),
        ],
        exercises: [
          mc(
            "Quantas cartas do Novo Testamento levam o nome de Paulo?",
            ["Treze", "Sete", "Vinte e sete", "Quatro"],
            0,
            "Há treze cartas com o nome de Paulo.",
            "Romanos - Filemom",
          ),
          fill(
            "Em Romanos, quem escreveu a carta para Paulo se chama",
            ".",
            ["Tércio", "Timóteo", "Tito"],
            0,
            "Romanos 16:22.",
            "Romanos 16:22",
          ),
          tf(
            "Todas as treze cartas com o nome de Paulo têm sua autoria aceita sem debate.",
            false,
            "Sete têm amplo consenso; seis são debatidas.",
            "Introdução às cartas de Paulo",
          ),
          match(
            "Associe cada parte típica de uma carta de Paulo.",
            [
              ["Início", "Remetente, destinatários e saudação"],
              ["Ação de graças", "Gratidão pela comunidade"],
              ["Final", "Saudações a pessoas"],
            ],
            "Estrutura comum das cartas.",
            "1 Tessalonicenses 1:1-2; Romanos 16",
          ),
          mc(
            "Qual destas cartas tem amplo consenso de que é de Paulo?",
            ["Gálatas", "Hebreus", "Tiago", "1 Pedro"],
            0,
            "Gálatas está entre as sete cartas não contestadas.",
            "Gálatas 1:1",
          ),
        ],
        takeaways: [
          "Treze cartas levam o nome de Paulo; sete têm autoria amplamente aceita.",
          "Paulo ditava suas cartas, como mostra Romanos 16:22.",
          "As cartas têm uma estrutura parecida.",
        ],
        reflection: "Se você escrevesse uma carta a um grupo querido, o que diria?",
      },
      {
        slug: "pa3-corinto",
        title: "Corinto: um corpo, muitos membros",
        objective: "Conhecer os desafios da comunidade de Corinto e a resposta de Paulo.",
        references: ["1 Coríntios 1:10-13", "1 Coríntios 12:12-27", "Atos 18:1-11"],
        context: "Corinto era uma cidade portuária grande e movimentada. Paulo ficou ali cerca de um ano e meio.",
        blocks: [
          b(
            "resumo",
            "Divisões",
            "Paulo recebe notícias de que a comunidade estava dividida: uns diziam “eu sou de Paulo”, outros “eu sou de Apolo”, “eu sou de Cefas”. Ele pergunta: Cristo está dividido?",
            "1 Coríntios 1:10-13",
          ),
          b(
            "resumo",
            "O corpo",
            "Paulo compara a comunidade a um corpo: muitos membros, cada um com sua função. O olho não pode dizer à mão que não precisa dela. Se um membro sofre, todos sofrem com ele.",
            "1 Coríntios 12:12-26",
          ),
          b(
            "contexto",
            "Áquila e Priscila",
            "Em Corinto, Paulo morou e trabalhou com Áquila e Priscila, um casal que também fazia tendas.",
            "Atos 18:2-3",
          ),
        ],
        exercises: [
          mc(
            "Qual problema Paulo aponta em 1 Coríntios 1?",
            ["Divisões na comunidade", "Falta de dinheiro", "Perseguição romana", "Fome"],
            0,
            "1 Coríntios 1:10-13.",
            "1 Coríntios 1:10-13",
          ),
          fill(
            "Paulo compara a comunidade a um",
            "com muitos membros.",
            ["corpo", "navio", "exército"],
            0,
            "1 Coríntios 12:12.",
            "1 Coríntios 12:12",
          ),
          tf(
            "Segundo Paulo, se um membro sofre, todos sofrem com ele.",
            true,
            "1 Coríntios 12:26.",
            "1 Coríntios 12:26",
          ),
          match(
            "Associe cada nome à sua ligação com Corinto.",
            [
              ["Apolo", "Citado nos grupos divididos"],
              ["Áquila e Priscila", "Casal que fazia tendas com Paulo"],
            ],
            "Pessoas ligadas a Corinto.",
            "1 Coríntios 1:12; Atos 18:2-3",
          ),
          mc(
            "Que outro capítulo famoso de 1 Coríntios vem logo depois da imagem do corpo?",
            ["O capítulo 13, sobre o amor", "O capítulo 1, sobre a criação", "O capítulo 28, sobre Malta", "O capítulo 150"],
            0,
            "1 Coríntios 13.",
            "1 Coríntios 13",
          ),
        ],
        takeaways: [
          "A comunidade de Corinto enfrentava divisões.",
          "Paulo usa a imagem do corpo com muitos membros.",
          "Cada membro importa, e o sofrimento é partilhado.",
        ],
        reflection: "Qual é o seu “membro” no corpo dos grupos de que você participa?",
      },
      {
        slug: "pa3-graca-e-fe",
        title: "Gálatas e Romanos: graça e fé",
        objective: "Conhecer temas centrais de Gálatas e Romanos e as diferentes ênfases das tradições.",
        references: ["Gálatas 2:16", "Gálatas 5:6", "Romanos 1:16-17", "Romanos 5:1", "Gálatas 3:28"],
        context: "Gálatas e Romanos tratam de uma pergunta importante para as primeiras comunidades: como alguém se torna justo diante de Deus?",
        blocks: [
          b(
            "resumo",
            "Justificados pela fé",
            "Paulo escreve que a pessoa é justificada pela fé em Cristo, e não pelas obras da Lei, e que, justificados pela fé, temos paz com Deus.",
            "Gálatas 2:16; Romanos 5:1",
          ),
          b(
            "resumo",
            "Todos um só",
            "Em Gálatas, Paulo diz que não há judeu nem grego, escravo nem livre, homem nem mulher: todos são um em Cristo.",
            "Gálatas 3:28",
          ),
          b(
            "tradicoes",
            "Ênfases diferentes",
            "Esses textos foram centrais na Reforma Protestante, que destacou a salvação “somente pela fé”. A tradição católica destaca também a “fé que age pelo amor” (Gálatas 5:6). Em 1999, católicos e luteranos assinaram uma declaração conjunta reconhecendo um entendimento comum básico sobre esse tema, mantendo algumas diferenças.",
            "Gálatas 5:6",
          ),
        ],
        exercises: [
          fill(
            "Paulo escreve que, justificados pela fé, temos",
            "com Deus.",
            ["paz", "medo", "dívidas"],
            0,
            "Romanos 5:1.",
            "Romanos 5:1",
          ),
          mc(
            "Segundo Gálatas 3:28, o que não faz diferença em Cristo?",
            ["Ser judeu ou grego, escravo ou livre, homem ou mulher", "Ter fé", "Amar o próximo", "Orar"],
            0,
            "Gálatas 3:28.",
            "Gálatas 3:28",
          ),
          tf(
            "Católicos e luteranos assinaram em 1999 uma declaração conjunta sobre a justificação.",
            true,
            "Ela reconhece um entendimento comum básico, mantendo diferenças.",
            "Gálatas 2:16",
          ),
          match(
            "Associe cada expressão à sua ênfase.",
            [
              ["“Somente pela fé”", "Destaque da Reforma Protestante"],
              ["“Fé que age pelo amor”", "Expressão de Gálatas 5:6, destacada pela tradição católica"],
            ],
            "Tradições leem Paulo com ênfases diferentes.",
            "Gálatas 2:16; 5:6",
          ),
          mc(
            "Qual pergunta central Gálatas e Romanos tratam?",
            ["Como alguém se torna justo diante de Deus", "Como construir um templo", "Como navegar até Roma", "Como fazer tendas"],
            0,
            "O tema da justificação é central nessas cartas.",
            "Romanos 1:16-17; Gálatas 2:16",
          ),
        ],
        takeaways: [
          "Paulo fala de ser justificado pela fé em Cristo.",
          "Em Cristo, as divisões sociais não definem ninguém.",
          "Tradições têm ênfases diferentes, e há diálogo entre elas.",
        ],
        reflection: "O que significa para você ser aceito antes de “merecer”?",
      },
      {
        slug: "pa3-filipenses",
        title: "Filipenses: alegria na prisão",
        objective: "Conhecer a carta de Paulo aos Filipenses.",
        references: ["Filipenses 1:3-14", "Filipenses 4:4-13"],
        context: "Paulo escreve aos Filipenses enquanto está preso. Mesmo assim, a palavra “alegria” aparece muitas vezes na carta.",
        blocks: [
          b(
            "resumo",
            "Gratidão",
            "Paulo agradece a Deus toda vez que se lembra dos filipenses, com alegria, pela parceria deles desde o primeiro dia.",
            "Filipenses 1:3-5",
          ),
          b(
            "resumo",
            "A prisão abriu portas",
            "Ele conta que sua prisão acabou ajudando a mensagem a se espalhar, e que outros ganharam coragem para falar.",
            "Filipenses 1:12-14",
          ),
          b(
            "resumo",
            "Aprender a se contentar",
            "Paulo diz: alegrem-se sempre. E conta que aprendeu a viver contente tanto na fartura quanto na necessidade, e que tudo pode naquele que o fortalece.",
            "Filipenses 4:4, 11-13",
          ),
        ],
        exercises: [
          mc(
            "Onde Paulo estava quando escreveu Filipenses?",
            ["Preso", "Num navio", "Em Tarso, com a família", "No templo"],
            0,
            "Filipenses 1:13.",
            "Filipenses 1:13",
          ),
          fill(
            "Paulo escreve: “Alegrem-se",
            "”.",
            ["sempre", "às vezes", "só nas festas"],
            0,
            "Filipenses 4:4.",
            "Filipenses 4:4",
          ),
          tf(
            "Paulo diz que sua prisão ajudou a mensagem a se espalhar.",
            true,
            "Filipenses 1:12-14.",
            "Filipenses 1:12-14",
          ),
          mc(
            "O que Paulo diz ter aprendido em Filipenses 4?",
            ["A viver contente na fartura e na necessidade", "A navegar", "A fazer milagres", "A falar grego"],
            0,
            "Filipenses 4:11-12.",
            "Filipenses 4:11-12",
          ),
          mc(
            "Em qual cidade ficava a comunidade que recebeu essa carta?",
            ["Filipos", "Roma", "Corinto", "Éfeso"],
            0,
            "Filipenses 1:1.",
            "Filipenses 1:1",
          ),
        ],
        takeaways: [
          "Filipenses foi escrita na prisão e fala muito de alegria.",
          "Paulo agradece pela parceria da comunidade.",
          "Ele aprendeu a se contentar em qualquer situação.",
        ],
        reflection: "O que traz alegria a você mesmo em dias difíceis?",
      },
      {
        slug: "pa3-filemom",
        title: "Filemom: uma carta pessoal",
        objective: "Conhecer a carta mais curta de Paulo e o pedido a Filemom.",
        references: ["Filemom 1-25"],
        context: "Filemom é a carta mais curta de Paulo. Ela trata de uma situação delicada envolvendo um escravizado chamado Onésimo.",
        blocks: [
          b(
            "contexto",
            "Escravidão no mundo romano",
            "No Império Romano, a escravidão era comum. A carta não é um tratado sobre o tema, mas trata de uma relação concreta entre duas pessoas.",
          ),
          b(
            "resumo",
            "Onésimo",
            "Onésimo tinha deixado a casa de Filemom e encontrou Paulo, tornando-se cristão. Paulo o envia de volta e pede que Filemom o receba não mais como escravo, mas como irmão amado.",
            "Filemom 10-16",
          ),
          b(
            "resumo",
            "“Ponha na minha conta”",
            "Paulo se oferece para pagar qualquer dívida de Onésimo: “se ele te deve alguma coisa, ponha na minha conta”.",
            "Filemom 18-19",
          ),
        ],
        exercises: [
          mc(
            "Quem era Onésimo?",
            ["Um escravizado ligado à casa de Filemom", "Um rei de Roma", "Um apóstolo", "Um sacerdote de Jerusalém"],
            0,
            "Filemom 10-16.",
            "Filemom 10-16",
          ),
          fill(
            "Paulo pede que Onésimo seja recebido como irmão",
            ".",
            ["amado", "distante", "servo"],
            0,
            "Filemom 16.",
            "Filemom 16",
          ),
          tf(
            "Filemom é a carta mais curta de Paulo.",
            true,
            "Tem apenas um capítulo.",
            "Filemom",
          ),
          mc(
            "O que Paulo oferece em relação a uma possível dívida de Onésimo?",
            ["Pagar por ele", "Esquecer o assunto", "Cobrar de Onésimo", "Pedir ao imperador"],
            0,
            "Filemom 18-19.",
            "Filemom 18-19",
          ),
          order(
            "Ordene o que acontece na história.",
            ["Onésimo deixa a casa de Filemom", "Encontra Paulo", "Paulo o envia de volta com a carta", "Pede que seja recebido como irmão"],
            "Filemom 10-16.",
            "Filemom 10-16",
          ),
        ],
        takeaways: [
          "Filemom é uma carta pessoal e curta.",
          "Paulo pede que Onésimo seja recebido como irmão amado.",
          "Ele se oferece para assumir a dívida de Onésimo.",
        ],
        reflection: "Que relação na sua vida poderia ser vista com novos olhos?",
      },
    ],
    review: {
      slug: "paulo-u3-revisao",
      title: "Revisão: Comunidades e cartas",
      intro: "Cartas que atravessaram os séculos. Vamos relembrar!",
      extra: [
        match(
          "Associe cada carta ao seu tema principal nesta unidade.",
          [
            ["1 Coríntios", "Um corpo, muitos membros"],
            ["Gálatas", "Justificação pela fé"],
            ["Filipenses", "Alegria na prisão"],
            ["Filemom", "Receber Onésimo como irmão"],
          ],
          "Cartas desta unidade.",
          "1 Coríntios; Gálatas; Filipenses; Filemom",
        ),
        mc(
          "Qual destas cartas é considerada por muitos a mais antiga de Paulo?",
          ["1 Tessalonicenses", "Romanos", "Filemom", "2 Timóteo"],
          0,
          "Por volta do ano 50.",
          "1 Tessalonicenses 1:1",
        ),
        tf(
          "Paulo costumava ditar suas cartas a outra pessoa.",
          true,
          "Romanos 16:22 menciona Tércio.",
          "Romanos 16:22",
        ),
      ],
      takeaways: [
        "As cartas de Paulo acompanhavam comunidades à distância.",
        "Unidade, fé, alegria e fraternidade são temas fortes.",
        "Há tradição e debate sobre a autoria de algumas cartas.",
      ],
    },
  },
];
