import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

/**
 * Jornada com Pedro. Compartilha lições da jornada geral (chamado, última
 * ceia, Getsêmani, Pentecostes). As lições p2-restauracao e p3-porta-formosa
 * também são usadas na jornada de João.
 */
export const pedroUnits: UnitDef[] = [
  {
    slug: "pedro-u1-chamado-e-convivencia",
    title: "Chamado e convivência",
    description: "De pescador na Galileia a um dos discípulos mais próximos de Jesus.",
    scene: "sea",
    lessons: [
      "g06-primeiros-discipulos",
      {
        slug: "p1-casa-em-cafarnaum",
        title: "Uma casa em Cafarnaum",
        objective: "Conhecer a vida de Simão Pedro antes e no início da convivência com Jesus.",
        references: ["Marcos 1:29-34", "João 1:40-44", "1 Coríntios 9:5"],
        context: "Simão era pescador, filho de Jonas (ou João), e trabalhava com seu irmão André no mar da Galileia.",
        blocks: [
          b(
            "resumo",
            "De Betsaida a Cafarnaum",
            "O Evangelho de João diz que André e Pedro eram de Betsaida. Marcos mostra Pedro morando em Cafarnaum, numa casa que se tornou ponto de encontro de Jesus com os discípulos.",
            "João 1:44; Marcos 1:29",
          ),
          b(
            "resumo",
            "A sogra de Pedro",
            "A sogra de Simão estava com febre. Jesus a toma pela mão, a febre a deixa e ela passa a servi-los. À tarde, muitas pessoas doentes são trazidas à porta da casa.",
            "Marcos 1:30-34",
          ),
          b(
            "contexto",
            "Um homem com família",
            "Pedro era casado — os Evangelhos falam de sua sogra, e Paulo menciona que Pedro (Cefas) viajava acompanhado da esposa.",
            "Marcos 1:30; 1 Coríntios 9:5",
          ),
        ],
        exercises: [
          mc(
            "Quem era irmão de Simão Pedro?",
            ["André", "Tiago", "João", "Filipe"],
            0,
            "João 1:40.",
            "João 1:40",
          ),
          fill(
            "Na casa de Pedro, Jesus curou a",
            "dele, que estava com febre.",
            ["sogra", "filha", "irmã"],
            0,
            "Marcos 1:30-31.",
            "Marcos 1:30-31",
          ),
          tf(
            "Segundo Paulo, Pedro viajava acompanhado de sua esposa.",
            true,
            "1 Coríntios 9:5.",
            "1 Coríntios 9:5",
          ),
          match(
            "Associe cada cidade ao que os Evangelhos dizem.",
            [
              ["Betsaida", "Cidade de origem de André e Pedro (João)"],
              ["Cafarnaum", "Onde ficava a casa de Pedro (Marcos)"],
            ],
            "Duas cidades à beira do mar da Galileia.",
            "João 1:44; Marcos 1:29",
          ),
          mc(
            "O que a sogra de Pedro fez depois de curada?",
            ["Passou a servi-los", "Foi ao templo", "Viajou para Jerusalém", "Dormiu"],
            0,
            "Marcos 1:31.",
            "Marcos 1:31",
          ),
        ],
        takeaways: [
          "Pedro era pescador, irmão de André.",
          "Sua casa em Cafarnaum recebia Jesus e muitas pessoas.",
          "Pedro era casado, como mostram os Evangelhos e Paulo.",
        ],
        reflection: "Que lugar da sua vida poderia ser um ponto de encontro e cuidado?",
      },
      {
        slug: "p1-sobre-as-aguas",
        title: "Pedro sobre as águas",
        objective: "Conhecer o relato de Pedro andando sobre as águas.",
        references: ["Mateus 14:22-33"],
        context: "Depois da multiplicação dos pães, os discípulos atravessam o lago de barco à noite, com vento contrário.",
        blocks: [
          b(
            "resumo",
            "“Sou eu”",
            "De madrugada, Jesus vai até eles andando sobre o mar. Os discípulos se assustam, pensando ser um fantasma. Jesus diz: “Coragem! Sou eu. Não tenham medo”.",
            "Mateus 14:25-27",
          ),
          b(
            "resumo",
            "“Manda-me ir”",
            "Pedro pede para ir até Jesus sobre as águas. Jesus diz “Venha”, e Pedro anda sobre as águas. Mas, ao reparar no vento, fica com medo e começa a afundar.",
            "Mateus 14:28-30",
          ),
          b(
            "resumo",
            "Uma mão estendida",
            "Pedro grita: “Senhor, salva-me!”. Jesus estende a mão, o segura e pergunta por que ele duvidou. Quando sobem ao barco, o vento cessa.",
            "Mateus 14:30-32",
          ),
        ],
        exercises: [
          mc(
            "O que os discípulos pensaram ao ver Jesus sobre o mar?",
            ["Que era um fantasma", "Que era Moisés", "Que era um barco", "Que era um sonho"],
            0,
            "Mateus 14:26.",
            "Mateus 14:26",
          ),
          fill(
            "Pedro começou a afundar quando reparou no",
            ".",
            ["vento", "barco", "sol"],
            0,
            "Mateus 14:30.",
            "Mateus 14:30",
          ),
          tf(
            "Pedro chegou a andar sobre as águas antes de começar a afundar.",
            true,
            "Mateus 14:29.",
            "Mateus 14:29",
          ),
          order(
            "Ordene o relato.",
            ["Jesus vem andando sobre o mar", "Pedro pede para ir", "Pedro anda e começa a afundar", "Jesus o segura pela mão", "O vento cessa"],
            "Mateus 14:25-32.",
            "Mateus 14:25-32",
          ),
          mc(
            "Em qual Evangelho Pedro anda sobre as águas?",
            ["Mateus", "Lucas", "Atos", "Romanos"],
            0,
            "Só Mateus conta a parte de Pedro andando sobre as águas.",
            "Mateus 14:28-31",
          ),
        ],
        takeaways: [
          "Jesus vem até os discípulos andando sobre o mar.",
          "Pedro anda sobre as águas e afunda ao sentir medo.",
          "Jesus estende a mão e o segura.",
        ],
        reflection: "Que “vento” costuma tirar seu foco?",
      },
      {
        slug: "p1-tu-es-o-cristo",
        title: "“Tu és o Cristo”",
        objective: "Conhecer a confissão de Pedro e o significado de seu nome.",
        references: ["Mateus 16:13-23", "Marcos 8:27-33", "João 1:42"],
        context: "Perto de Cesareia de Filipe, Jesus faz uma pergunta aos discípulos.",
        blocks: [
          b(
            "resumo",
            "“Quem vocês dizem que eu sou?”",
            "Jesus pergunta o que as pessoas diziam sobre ele e, depois, o que os discípulos diziam. Pedro responde: “Tu és o Cristo, o Filho do Deus vivo”.",
            "Mateus 16:13-16",
          ),
          b(
            "explicacao",
            "Pedro, a pedra",
            "Simão recebe o nome Cefas (em aramaico) ou Pedro (em grego), que significam “pedra”. Em Mateus, Jesus diz: “Tu és Pedro, e sobre esta pedra edificarei a minha igreja”.",
            "João 1:42; Mateus 16:18",
          ),
          b(
            "tradicoes",
            "Leituras diferentes",
            "A tradição católica entende que a “pedra” se refere a Pedro e vê aqui a base do papel especial de Pedro e de seus sucessores. Muitas tradições protestantes entendem a “pedra” como a confissão de fé de Pedro ou o próprio Cristo. As duas leituras têm longa história.",
          ),
          b(
            "resumo",
            "Logo depois, uma repreensão",
            "Quando Jesus anuncia que sofreria e morreria, Pedro o repreende. Jesus responde com dureza, dizendo que Pedro pensava como os homens, não como Deus.",
            "Mateus 16:21-23",
          ),
        ],
        exercises: [
          fill(
            "Pedro responde: “Tu és o Cristo, o Filho do Deus",
            "”.",
            ["vivo", "altíssimo", "de Israel"],
            0,
            "Mateus 16:16.",
            "Mateus 16:16",
          ),
          mc(
            "O que significam os nomes Cefas e Pedro?",
            ["Pedra", "Pescador", "Fiel", "Irmão"],
            0,
            "Cefas (aramaico) e Pedro (grego) significam “pedra”.",
            "João 1:42",
          ),
          tf(
            "Todas as tradições cristãs interpretam a “pedra” de Mateus 16:18 da mesma forma.",
            false,
            "Católicos e muitos protestantes leem o texto de formas diferentes.",
            "Mateus 16:18",
          ),
          mc(
            "Perto de qual cidade acontece essa conversa?",
            ["Cesareia de Filipe", "Jerusalém", "Nazaré", "Jericó"],
            0,
            "Mateus 16:13.",
            "Mateus 16:13",
          ),
          order(
            "Ordene a conversa.",
            ["Jesus pergunta o que dizem dele", "Pedro confessa: “Tu és o Cristo”", "Jesus anuncia seu sofrimento", "Pedro o repreende e é corrigido"],
            "Mateus 16:13-23.",
            "Mateus 16:13-23",
          ),
        ],
        takeaways: [
          "Pedro confessa que Jesus é o Cristo.",
          "Cefas e Pedro significam “pedra”.",
          "Tradições leem Mateus 16:18 de formas diferentes.",
        ],
        reflection: "Se Jesus perguntasse a você “quem você diz que eu sou?”, o que responderia hoje?",
      },
      {
        slug: "p1-transfiguracao",
        title: "No alto do monte",
        objective: "Conhecer a transfiguração e a reação de Pedro.",
        references: ["Marcos 9:2-10", "2 Pedro 1:16-18"],
        context: "Seis dias depois da confissão de Pedro, Jesus leva Pedro, Tiago e João a um monte alto.",
        blocks: [
          b(
            "resumo",
            "Roupas brilhantes",
            "Jesus é transfigurado diante deles: suas roupas ficam de um branco brilhante. Elias e Moisés aparecem conversando com ele.",
            "Marcos 9:2-4",
          ),
          b(
            "resumo",
            "Três tendas",
            "Pedro, sem saber o que dizer de tão assustado, propõe fazer três tendas: uma para Jesus, uma para Moisés e uma para Elias.",
            "Marcos 9:5-6",
          ),
          b(
            "resumo",
            "Uma voz na nuvem",
            "Uma nuvem os cobre e uma voz diz: “Este é o meu Filho amado. Ouçam-no!”. De repente, eles não veem mais ninguém, só Jesus.",
            "Marcos 9:7-8",
          ),
        ],
        exercises: [
          mc(
            "Quem apareceu conversando com Jesus no monte?",
            ["Moisés e Elias", "Abraão e Isaque", "Davi e Salomão", "Isaías e Jeremias"],
            0,
            "Marcos 9:4.",
            "Marcos 9:4",
          ),
          fill(
            "Pedro propôs fazer três",
            ".",
            ["tendas", "altares", "barcos"],
            0,
            "Marcos 9:5.",
            "Marcos 9:5",
          ),
          tf(
            "A voz na nuvem disse: “Este é o meu Filho amado. Ouçam-no!”.",
            true,
            "Marcos 9:7.",
            "Marcos 9:7",
          ),
          match(
            "Associe quem esteve no monte com Jesus.",
            [
              ["Pedro", "Propôs as tendas"],
              ["Tiago e João", "Também subiram com Jesus"],
              ["Moisés e Elias", "Apareceram conversando com Jesus"],
            ],
            "Marcos 9:2-5.",
            "Marcos 9:2-5",
          ),
          mc(
            "Qual carta do Novo Testamento lembra esse momento no monte?",
            ["2 Pedro", "Romanos", "Gálatas", "Tiago"],
            0,
            "2 Pedro 1:16-18.",
            "2 Pedro 1:16-18",
          ),
        ],
        takeaways: [
          "Na transfiguração, Jesus aparece com roupas brilhantes.",
          "Moisés e Elias conversam com ele.",
          "Pedro, assustado, propõe três tendas.",
        ],
        reflection: "Pedro queria “guardar” aquele momento. Que momentos você gostaria de guardar?",
      },
    ],
    review: {
      slug: "pedro-u1-revisao",
      title: "Revisão: Chamado e convivência",
      intro: "Do barco à montanha. Vamos relembrar os primeiros passos de Pedro com Jesus.",
      extra: [
        order(
          "Ordene os acontecimentos.",
          ["Chamado à beira do lago", "Cura da sogra em Cafarnaum", "Pedro sobre as águas", "Confissão em Cesareia de Filipe", "Transfiguração"],
          "Marcos 1; Mateus 14; 16; Marcos 9.",
          "Marcos 1 - Marcos 9",
        ),
        match(
          "Associe cada frase a quem a disse.",
          [
            ["“Senhor, salva-me!”", "Pedro sobre as águas"],
            ["“Tu és o Cristo”", "Pedro em Cesareia"],
            ["“Ouçam-no!”", "Voz na nuvem"],
          ],
          "Frases desta unidade.",
          "Mateus 14:30; 16:16; Marcos 9:7",
        ),
        tf(
          "Pedro também teve momentos de medo e de incompreensão.",
          true,
          "Ele afundou com medo e foi corrigido por Jesus.",
          "Mateus 14:30; 16:22-23",
        ),
      ],
      takeaways: [
        "Pedro foi chamado enquanto trabalhava como pescador.",
        "Ele confessa Jesus como o Cristo e recebe o nome “pedra”.",
        "A convivência com Jesus inclui coragem, medo e aprendizado.",
      ],
    },
  },
  {
    slug: "pedro-u2-negacao-e-restauracao",
    title: "Negação e restauração",
    description: "A última ceia, a negação no pátio e o recomeço à beira do lago.",
    scene: "city",
    lessons: [
      "g08-ultima-ceia",
      {
        slug: "p2-previsao-da-negacao",
        title: "“Mesmo que todos…”",
        objective: "Conhecer o aviso de Jesus sobre a negação de Pedro.",
        references: ["Marcos 14:27-31", "Lucas 22:31-34", "João 13:36-38"],
        context: "Depois da ceia, a caminho do monte das Oliveiras, Jesus avisa que os discípulos o abandonariam.",
        blocks: [
          b(
            "resumo",
            "Uma promessa confiante",
            "Pedro afirma que, mesmo que todos abandonassem Jesus, ele não o faria. Jesus responde que, antes de o galo cantar, Pedro o negaria três vezes.",
            "Marcos 14:29-30",
          ),
          b(
            "resumo",
            "“Eu orei por você”",
            "Em Lucas, Jesus diz a Pedro que orou para que sua fé não falhasse e que, quando ele voltasse, fortalecesse os irmãos.",
            "Lucas 22:31-32",
          ),
          b(
            "explicacao",
            "Aviso com cuidado",
            "O aviso de Jesus não vem com rejeição: vem junto com oração e uma missão para depois da queda.",
          ),
        ],
        exercises: [
          fill(
            "Jesus diz que, antes de o",
            "cantar, Pedro o negaria três vezes.",
            ["galo", "sino", "pássaro"],
            0,
            "Marcos 14:30.",
            "Marcos 14:30",
          ),
          tf(
            "Pedro disse que, mesmo que todos abandonassem Jesus, ele não o faria.",
            true,
            "Marcos 14:29.",
            "Marcos 14:29",
          ),
          mc(
            "Em Lucas, o que Jesus diz que fez por Pedro?",
            ["Orou para que sua fé não falhasse", "Escreveu uma carta", "Deu-lhe uma espada", "Mandou-o para casa"],
            0,
            "Lucas 22:32.",
            "Lucas 22:32",
          ),
          mc(
            "Quantas vezes, segundo o aviso, Pedro negaria Jesus?",
            ["Três", "Uma", "Sete", "Duas"],
            0,
            "Marcos 14:30.",
            "Marcos 14:30",
          ),
          mc(
            "Qual missão Jesus dá a Pedro em Lucas 22:32?",
            ["Fortalecer os irmãos depois de voltar", "Construir um templo", "Voltar a pescar", "Ir para Roma imediatamente"],
            0,
            "Lucas 22:32.",
            "Lucas 22:32",
          ),
        ],
        takeaways: [
          "Pedro promete fidelidade com confiança.",
          "Jesus avisa que Pedro o negaria três vezes.",
          "O aviso vem com oração e uma missão para depois.",
        ],
        reflection: "Já prometeu algo com muita certeza e depois falhou? Como foi recomeçar?",
      },
      "g08-getsemani",
      {
        slug: "p2-a-negacao",
        title: "No pátio do sumo sacerdote",
        objective: "Conhecer o relato da negação de Pedro.",
        references: ["Marcos 14:54, 66-72", "Lucas 22:54-62"],
        context: "Depois da prisão de Jesus, Pedro o segue de longe até o pátio da casa do sumo sacerdote.",
        blocks: [
          b(
            "resumo",
            "Junto ao fogo",
            "Pedro se senta com os guardas, aquecendo-se junto ao fogo. Uma criada o reconhece e diz que ele estava com Jesus. Pedro nega.",
            "Marcos 14:54, 66-68",
          ),
          b(
            "resumo",
            "Três vezes",
            "Outras pessoas insistem que ele era um deles — até seu sotaque da Galileia o denunciava. Pedro nega mais duas vezes, chegando a jurar que não conhecia Jesus.",
            "Marcos 14:69-71",
          ),
          b(
            "resumo",
            "Um olhar e um choro",
            "O galo canta. Lucas conta que o Senhor se voltou e olhou para Pedro. Pedro se lembra das palavras de Jesus, sai e chora amargamente.",
            "Lucas 22:60-62",
          ),
        ],
        exercises: [
          mc(
            "Quem reconheceu Pedro primeiro no pátio?",
            ["Uma criada", "O sumo sacerdote", "Judas", "Um soldado romano"],
            0,
            "Marcos 14:66-67.",
            "Marcos 14:66-67",
          ),
          tf(
            "O sotaque da Galileia ajudou as pessoas a reconhecerem Pedro.",
            true,
            "Mateus 26:73 menciona o modo de falar; Marcos diz que ele era galileu.",
            "Marcos 14:70; Mateus 26:73",
          ),
          fill(
            "Depois do canto do galo, Pedro saiu e chorou",
            ".",
            ["amargamente", "de alegria", "em silêncio no templo"],
            0,
            "Lucas 22:62.",
            "Lucas 22:62",
          ),
          order(
            "Ordene o relato.",
            ["Pedro segue Jesus de longe", "Uma criada o reconhece", "Pedro nega três vezes", "O galo canta", "Pedro chora"],
            "Marcos 14:54-72.",
            "Marcos 14:54-72",
          ),
          mc(
            "Qual detalhe Lucas acrescenta ao relato?",
            ["O Senhor se voltou e olhou para Pedro", "Pedro fugiu de barco", "Pedro foi preso", "Pedro cortou a orelha de um servo"],
            0,
            "Lucas 22:61.",
            "Lucas 22:61",
          ),
        ],
        takeaways: [
          "Pedro segue Jesus de longe até o pátio.",
          "Com medo, nega conhecer Jesus três vezes.",
          "Ao ouvir o galo, lembra-se e chora amargamente.",
        ],
        reflection: "O choro de Pedro mostra arrependimento. O que você faz quando percebe que errou?",
      },
      {
        slug: "p2-restauracao",
        title: "À beira do lago: “Tu me amas?”",
        objective: "Conhecer o encontro de Jesus ressuscitado com Pedro e os discípulos em João 21.",
        references: ["João 21:1-19"],
        context: "Depois da ressurreição, alguns discípulos voltam à Galileia. Pedro diz: “Vou pescar”, e outros vão com ele.",
        blocks: [
          b(
            "resumo",
            "Uma pesca conhecida",
            "Eles não pescam nada a noite toda. De manhã, um homem na praia pede que lancem a rede do lado direito, e a rede se enche de peixes. O discípulo a quem Jesus amava diz a Pedro: “É o Senhor!”. Pedro se joga na água.",
            "João 21:3-7",
          ),
          b(
            "resumo",
            "Brasas e pão",
            "Na praia, há brasas com peixe e pão. Jesus os convida a comer. O detalhe das brasas lembra a fogueira do pátio onde Pedro tinha negado Jesus.",
            "João 21:9-13; 18:18",
          ),
          b(
            "resumo",
            "Três perguntas",
            "Jesus pergunta três vezes a Pedro: “Tu me amas?”. Pedro fica triste com a terceira pergunta e responde que Jesus sabe tudo. A cada resposta, Jesus confia a ele uma tarefa: cuidar das suas ovelhas.",
            "João 21:15-17",
          ),
        ],
        exercises: [
          mc(
            "Quem reconhece Jesus primeiro e diz “É o Senhor!”?",
            ["O discípulo a quem Jesus amava", "Pedro", "Tomé", "André"],
            0,
            "João 21:7.",
            "João 21:7",
          ),
          fill(
            "Jesus pergunta três vezes a Pedro: “Tu me",
            "?”",
            ["amas", "ouves", "conheces"],
            0,
            "João 21:15-17.",
            "João 21:15-17",
          ),
          tf(
            "A cada resposta de Pedro, Jesus lhe confia o cuidado de suas ovelhas.",
            true,
            "João 21:15-17.",
            "João 21:15-17",
          ),
          match(
            "Associe cada detalhe ao que lembra.",
            [
              ["Três perguntas", "As três negações"],
              ["Brasas na praia", "A fogueira do pátio"],
              ["Rede cheia", "A pesca abundante do chamado"],
            ],
            "Muitos leitores percebem esses ecos no texto.",
            "João 18:18; 21:9-17; Lucas 5:6",
          ),
          order(
            "Ordene o relato.",
            ["Noite sem pescar nada", "A rede se enche de peixes", "Refeição na praia", "Três perguntas a Pedro"],
            "João 21:3-17.",
            "João 21:3-17",
          ),
        ],
        takeaways: [
          "Jesus ressuscitado se encontra com os discípulos à beira do lago.",
          "As três perguntas a Pedro ecoam as três negações.",
          "Pedro recebe a missão de cuidar das ovelhas.",
        ],
        reflection: "Recomeçar depois de uma falha: o que essa história diz sobre isso?",
      },
    ],
    review: {
      slug: "pedro-u2-revisao",
      title: "Revisão: Negação e restauração",
      intro: "Da noite mais difícil ao recomeço. Vamos relembrar.",
      extra: [
        order(
          "Ordene a trajetória de Pedro nesta unidade.",
          ["Última ceia", "Promessa de fidelidade", "Getsêmani", "Negação no pátio", "Encontro à beira do lago"],
          "Marcos 14 e João 21.",
          "Marcos 14 - João 21",
        ),
        match(
          "Associe cada lugar ao acontecimento.",
          [
            ["Pátio do sumo sacerdote", "Negação"],
            ["Getsêmani", "Discípulos dormindo"],
            ["Praia do lago", "“Tu me amas?”"],
          ],
          "Lugares desta unidade.",
          "Marcos 14; João 21",
        ),
        tf(
          "A história de Pedro mostra que uma falha não precisa ser o fim do caminho.",
          true,
          "Depois da negação, Pedro recebe uma nova missão.",
          "João 21:15-19",
        ),
      ],
      takeaways: [
        "Pedro promete fidelidade e falha na noite da prisão.",
        "Seu choro mostra arrependimento.",
        "Jesus o restaura com perguntas e uma missão.",
      ],
    },
  },
  {
    slug: "pedro-u3-pedro-em-atos",
    title: "Pedro em Atos",
    description: "O pescador que se torna uma voz das primeiras comunidades.",
    scene: "road",
    lessons: [
      "g09-pentecostes",
      {
        slug: "p3-porta-formosa",
        title: "Na Porta Formosa",
        objective: "Conhecer a cura de um homem na entrada do templo por Pedro e João.",
        references: ["Atos 3:1-16"],
        context: "Pedro e João sobem ao templo na hora da oração da tarde.",
        blocks: [
          b(
            "resumo",
            "Um pedido de esmola",
            "Na porta do templo chamada Formosa, um homem que não andava desde o nascimento pede esmola.",
            "Atos 3:1-3",
          ),
          b(
            "resumo",
            "“Não tenho prata nem ouro”",
            "Pedro diz: “Não tenho prata nem ouro, mas o que tenho isso lhe dou: em nome de Jesus Cristo, o Nazareno, ande!”. Ele o pega pela mão, e o homem se levanta, anda e salta, louvando a Deus.",
            "Atos 3:6-8",
          ),
          b(
            "resumo",
            "Não por nosso poder",
            "O povo se espanta, e Pedro explica que aquilo não aconteceu pelo poder ou pela piedade deles, mas pelo nome de Jesus.",
            "Atos 3:12-16",
          ),
        ],
        exercises: [
          mc(
            "Quem estava com Pedro na Porta Formosa?",
            ["João", "Paulo", "Tiago", "Barnabé"],
            0,
            "Atos 3:1.",
            "Atos 3:1",
          ),
          fill(
            "Pedro disse: “Não tenho prata nem",
            "”.",
            ["ouro", "pão", "casa"],
            0,
            "Atos 3:6.",
            "Atos 3:6",
          ),
          tf(
            "O homem curado entrou no templo andando, saltando e louvando a Deus.",
            true,
            "Atos 3:8.",
            "Atos 3:8",
          ),
          mc(
            "Segundo Pedro, por que o homem foi curado?",
            ["Pelo nome de Jesus", "Pelo poder de Pedro", "Pela esmola recebida", "Por um remédio"],
            0,
            "Atos 3:12-16.",
            "Atos 3:16",
          ),
          order(
            "Ordene o relato.",
            ["Pedro e João sobem ao templo", "O homem pede esmola", "Pedro o pega pela mão", "O homem anda e louva a Deus"],
            "Atos 3:1-8.",
            "Atos 3:1-8",
          ),
        ],
        takeaways: [
          "Pedro e João encontram um homem que não andava.",
          "Pedro oferece o que tem: o nome de Jesus.",
          "Ele afirma que a cura não veio de seu próprio poder.",
        ],
        reflection: "“O que tenho, isso lhe dou.” O que você tem para oferecer hoje?",
      },
      {
        slug: "p3-diante-do-conselho",
        title: "Diante do conselho",
        objective: "Conhecer a coragem de Pedro e João diante das autoridades.",
        references: ["Atos 4:1-22"],
        context: "Depois da cura no templo, Pedro e João são presos e levados ao conselho dos líderes.",
        blocks: [
          b(
            "resumo",
            "Gente simples, com coragem",
            "Os líderes ficam admirados com a coragem de Pedro e João, percebendo que eram homens simples, sem estudo formal, e reconhecem que tinham estado com Jesus.",
            "Atos 4:13",
          ),
          b(
            "resumo",
            "“Não podemos deixar de falar”",
            "O conselho ordena que não falem mais em nome de Jesus. Pedro e João respondem que não podem deixar de falar do que viram e ouviram.",
            "Atos 4:18-20",
          ),
          b(
            "contexto",
            "O conselho",
            "O Sinédrio era o principal conselho judaico em Jerusalém, com sacerdotes, anciãos e mestres da Lei.",
            "Atos 4:5-6",
          ),
        ],
        exercises: [
          mc(
            "O que admirou os líderes em Pedro e João?",
            ["A coragem de homens simples", "Suas roupas", "Sua riqueza", "Seu conhecimento de grego"],
            0,
            "Atos 4:13.",
            "Atos 4:13",
          ),
          fill(
            "Pedro e João disseram que não podiam deixar de falar do que tinham visto e",
            ".",
            ["ouvido", "comido", "escrito"],
            0,
            "Atos 4:20.",
            "Atos 4:20",
          ),
          tf(
            "O conselho ordenou que eles não falassem mais em nome de Jesus.",
            true,
            "Atos 4:18.",
            "Atos 4:18",
          ),
          mc(
            "Qual era o principal conselho judaico em Jerusalém?",
            ["Sinédrio", "Senado", "Areópago", "Concílio de Niceia"],
            0,
            "O Sinédrio reunia sacerdotes, anciãos e mestres da Lei.",
            "Atos 4:5-6",
          ),
          order(
            "Ordene os acontecimentos.",
            ["Cura na Porta Formosa", "Pedro e João são presos", "Falam diante do conselho", "São soltos com uma ordem de silêncio"],
            "Atos 3-4.",
            "Atos 3:1-4:21",
          ),
        ],
        takeaways: [
          "Pedro e João são levados ao Sinédrio.",
          "Mesmo sem estudo formal, falam com coragem.",
          "Dizem que não podem deixar de falar do que viram.",
        ],
        reflection: "Que experiência sua você não consegue deixar de contar?",
      },
      {
        slug: "p3-pedro-e-cornelio",
        title: "Pedro e Cornélio",
        objective: "Conhecer como Pedro entendeu que a mensagem era para todos os povos.",
        references: ["Atos 10:1-48", "Atos 11:1-18"],
        context: "Cornélio era um centurião romano em Cesareia, descrito como piedoso e generoso.",
        blocks: [
          b(
            "resumo",
            "Duas visões",
            "Cornélio recebe a orientação de chamar Pedro. Ao mesmo tempo, em Jope, Pedro tem uma visão de um grande lençol com animais considerados impuros e ouve: “Não chame impuro ao que Deus purificou”.",
            "Atos 10:1-16",
          ),
          b(
            "resumo",
            "Na casa de um estrangeiro",
            "Pedro vai à casa de Cornélio e diz que, pela lei, um judeu não costumava entrar na casa de um estrangeiro, mas que Deus lhe mostrou que não deveria chamar ninguém de impuro.",
            "Atos 10:24-29",
          ),
          b(
            "resumo",
            "Deus não faz distinção",
            "Pedro afirma que Deus não trata as pessoas com parcialidade. Enquanto ele fala, o Espírito vem sobre os ouvintes, e eles são batizados.",
            "Atos 10:34-48",
          ),
        ],
        exercises: [
          mc(
            "Quem era Cornélio?",
            ["Um centurião romano", "Um sacerdote judeu", "Um pescador", "Um rei da Babilônia"],
            0,
            "Atos 10:1.",
            "Atos 10:1",
          ),
          fill(
            "Pedro ouve: “Não chame",
            "ao que Deus purificou”.",
            ["impuro", "pequeno", "estrangeiro"],
            0,
            "Atos 10:15.",
            "Atos 10:15",
          ),
          match(
            "Associe cada cidade ao personagem.",
            [
              ["Jope", "Onde Pedro tem a visão"],
              ["Cesareia", "Onde morava Cornélio"],
            ],
            "Atos 10.",
            "Atos 10:1-9",
          ),
          tf(
            "Pedro concluiu que Deus não trata as pessoas com parcialidade.",
            true,
            "Atos 10:34.",
            "Atos 10:34",
          ),
          order(
            "Ordene o relato.",
            ["Cornélio recebe a orientação", "Pedro tem a visão do lençol", "Pedro vai à casa de Cornélio", "O Espírito vem sobre os ouvintes"],
            "Atos 10.",
            "Atos 10:1-44",
          ),
        ],
        takeaways: [
          "Cornélio, um centurião romano, chama Pedro.",
          "Uma visão leva Pedro a superar barreiras.",
          "Pedro afirma que Deus não faz distinção entre pessoas.",
        ],
        reflection: "Que barreira você gostaria de atravessar para encontrar alguém diferente?",
      },
      {
        slug: "p3-libertado-da-prisao",
        title: "Portas que se abrem",
        objective: "Conhecer a libertação de Pedro da prisão e o que se sabe de seus últimos anos.",
        references: ["Atos 12:1-17", "1 Pedro 1:1", "João 21:18-19"],
        context: "O rei Herodes Agripa I persegue a comunidade em Jerusalém: manda matar Tiago, irmão de João, e prende Pedro.",
        blocks: [
          b(
            "resumo",
            "A comunidade ora",
            "Pedro fica preso, acorrentado entre dois soldados, enquanto a comunidade ora intensamente por ele. Um anjo o acorda, as correntes caem e os portões se abrem.",
            "Atos 12:5-10",
          ),
          b(
            "resumo",
            "Rode e o portão",
            "Pedro vai à casa de Maria, mãe de João Marcos, onde muitos oravam. A empregada Rode reconhece sua voz e, de tanta alegria, esquece de abrir o portão e corre para avisar. Os outros não acreditam.",
            "Atos 12:12-16",
          ),
          b(
            "tradicoes",
            "Depois de Atos",
            "Atos não conta a morte de Pedro. Duas cartas do Novo Testamento levam seu nome (1 e 2 Pedro). Uma antiga tradição cristã diz que Pedro morreu como mártir em Roma, e o Evangelho de João faz uma alusão à sua morte. A autoria das cartas, especialmente de 2 Pedro, é debatida por estudiosos.",
            "João 21:18-19; 1 Pedro 1:1",
          ),
        ],
        exercises: [
          mc(
            "Qual apóstolo foi morto por Herodes antes da prisão de Pedro?",
            ["Tiago, irmão de João", "André", "Paulo", "Estêvão"],
            0,
            "Atos 12:2.",
            "Atos 12:2",
          ),
          fill(
            "A empregada que esqueceu de abrir o portão chamava-se",
            ".",
            ["Rode", "Lídia", "Marta"],
            0,
            "Atos 12:13.",
            "Atos 12:13",
          ),
          tf(
            "Enquanto Pedro estava preso, a comunidade orava por ele.",
            true,
            "Atos 12:5.",
            "Atos 12:5",
          ),
          mc(
            "O livro de Atos conta a morte de Pedro?",
            ["Não; ela é lembrada pela tradição", "Sim, no capítulo 12", "Sim, no último capítulo", "Sim, em Jerusalém"],
            0,
            "Atos não narra a morte de Pedro.",
            "Atos 12; João 21:18-19",
          ),
          order(
            "Ordene o relato.",
            ["Herodes prende Pedro", "A comunidade ora", "O anjo liberta Pedro", "Rode reconhece sua voz"],
            "Atos 12:3-14.",
            "Atos 12:3-14",
          ),
        ],
        takeaways: [
          "Pedro é libertado da prisão enquanto a comunidade ora.",
          "Rode, de tanta alegria, esquece de abrir o portão.",
          "A morte de Pedro em Roma é lembrada pela tradição, não por Atos.",
        ],
        reflection: "Rode esqueceu o portão de tanta alegria. O que deixa você assim?",
      },
    ],
    review: {
      slug: "pedro-u3-revisao",
      title: "Revisão: Pedro em Atos",
      intro: "Do Pentecostes à prisão em Jerusalém. Vamos relembrar Pedro nas primeiras comunidades.",
      extra: [
        order(
          "Ordene os acontecimentos de Atos.",
          ["Discurso de Pentecostes", "Cura na Porta Formosa", "Diante do conselho", "Visita a Cornélio", "Libertação da prisão"],
          "Atos 2, 3, 4, 10 e 12.",
          "Atos 2-12",
        ),
        match(
          "Associe cada frase ao contexto.",
          [
            ["“Não tenho prata nem ouro”", "Porta Formosa"],
            ["“Deus não faz distinção”", "Casa de Cornélio"],
            ["“Não podemos deixar de falar”", "Diante do conselho"],
          ],
          "Frases marcantes de Pedro em Atos.",
          "Atos 3:6; 4:20; 10:34",
        ),
        tf(
          "Pedro, que tinha negado Jesus, aparece em Atos falando com coragem.",
          true,
          "Atos mostra a transformação de Pedro.",
          "Atos 2-4",
        ),
      ],
      takeaways: [
        "Pedro se torna uma voz corajosa das primeiras comunidades.",
        "Ele aprende que a mensagem é para todos os povos.",
        "Sua história mostra transformação depois da falha.",
      ],
    },
  },
];
