// Gera capturas de tela das principais telas (SHOTS=1 npx playwright test screens).
import { test } from '@playwright/test';
import { answer, playLesson } from './helpers.js';

test.skip(!process.env.SHOTS, 'defina SHOTS=1 para gerar capturas');

test('capturas', async ({ page }) => {
  const shot = (n) => page.screenshot({ path: `tests/e2e/shots/${n}.png`, fullPage: true });
  await page.goto('/bem-vindo');
  await shot('01-boas-vindas');
  await page.getByRole('button', { name: 'Começar' }).click();
  await page.getByLabel('Como você gostaria de ser chamado?').fill('Ana');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('radio', { name: 'Estou começando' }).click();
  await shot('02-onboarding');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('radio', { name: 'Criar uma rotina de estudo' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('link', { name: 'Experimentar a primeira lição' }).click();
  await shot('03-licao-intro');
  await page.getByRole('button', { name: 'Começar' }).click();
  await shot('04-bloco');
  for (let i = 0; i < 5; i++) await page.getByRole('button', { name: 'Continuar' }).click();
  await shot('05-bloco-interpretacao');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.locator('main').getByRole('button', { name: /Do latim/ }).click();
  await page.getByRole('button', { name: 'Verificar' }).click();
  await shot('06-feedback-erro');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await answer(page);
  await answer(page);
  await answer(page);
  await page.locator('main select').first().selectOption({ index: 1 });
  await shot('07-associacao');
  await page.goBack();
  await page.goto('/experimentar');
  await playLesson(page, { wrong: [0] });
  await shot('08-concluida');
  await page.getByRole('link', { name: 'Criar conta e salvar progresso' }).click();
  await page.getByLabel('E-mail').fill('ana@example.com');
  await page.getByLabel('Senha').fill('senha-segura');
  await page.getByRole('button', { name: 'Criar conta' }).last().click();
  await page.getByRole('heading', { name: 'Ana' }).waitFor();
  await shot('09-inicio');
  await page.getByRole('navigation').getByRole('link', { name: 'Jornada' }).click();
  await page.getByRole('heading', { name: 'Jornada' }).waitFor();
  await shot('10-jornada');
  await page.getByRole('link', { name: /Lição 2/ }).click();
  await page.getByRole('button', { name: 'Começar' }).click();
  while (!(await page.getByRole('button', { name: 'Verificar' }).isVisible())) await page.getByRole('button', { name: 'Continuar' }).click();
  await answer(page);
  await answer(page);
  await shot('11-completar');
  await page.goto('/revisao');
  await page.getByRole('heading', { name: 'Vamos lembrar?' }).waitFor();
  await shot('12-revisao');
  await page.goto('/caderno');
  await page.getByRole('tab', { name: 'Reflexões' }).waitFor();
  await shot('13-caderno');
  await page.goto('/perfil');
  await page.getByRole('heading', { name: 'Conquistas' }).waitFor();
  await shot('14-perfil');
});
