# Gateway mínimo: imita as rotas do Supabase (/auth/v1 e /rest/v1).
events {}
http {
  client_max_body_size 5m;
  server {
    listen 8000;
    location /auth/v1/ {
      proxy_pass http://auth:9999/;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto http;
    }
    location /rest/v1/ {
      proxy_pass http://rest:3000/;
      proxy_set_header Host $http_host;
    }
  }
}
