import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const u03: UnitDef = {
  slug: "geral-u03-abraao",
  title: "Abraão e sua família",
  description: "Promessas, esperas e reencontros na família de Abraão, Isaque, Jacó e José.",
  scene: "desert",
  lessons: [
    {
      slug: "g03-chamado-de-abrao",
      title: "O chamado de Abrão",
      objective: "Conhecer o chamado de Abrão e as promessas que ele recebe.",
      references: ["Gênesis 12:1-9"],
      context:
        "Com Abrão (mais tarde chamado Abraão), Gênesis passa a acompanhar uma família. Ele é lembrado por judeus, cristãos e muçulmanos como uma figura de fé.",
      blocks: [
        b(
          "resumo",
          "“Sai da tua terra”",
          "Deus pede a Abrão que deixe sua terra e a casa de seu pai e vá para uma terra que lhe seria mostrada. Deus promete fazer dele uma grande nação e que, por meio dele, todas as famílias da terra seriam abençoadas.",
          "Gênesis 12:1-3",
        ),
        b(
          "resumo",
          "A partida",
          "Abrão parte de Harã com sua esposa Sarai e seu sobrinho Ló, rumo à terra de Canaã. Ele tinha setenta e cinco anos.",
          "Gênesis 12:4-5",
        ),
        b(
          "contexto",
          "Um pastor nômade",
          "Abrão vivia como muitos pastores da época: em tendas, mudando de lugar com seus rebanhos. Ao longo do caminho, ele ergue altares para lembrar seus encontros com Deus.",
          "Gênesis 12:7-8",
        ),
      ],
      exercises: [
        mc(
          "De qual cidade Abrão parte, segundo Gênesis 12?",
          ["Harã", "Jerusalém", "Babilônia", "Nínive"],
          0,
          "Gênesis 12:4 diz que Abrão saiu de Harã.",
          "Gênesis 12:4",
        ),
        tf(
          "Deus promete que, por meio de Abrão, todas as famílias da terra seriam abençoadas.",
          true,
          "Essa promessa aparece em Gênesis 12:3.",
          "Gênesis 12:3",
        ),
        match(
          "Associe cada pessoa à sua relação com Abrão.",
          [
            ["Sarai", "Esposa"],
            ["Ló", "Sobrinho"],
          ],
          "Sarai era esposa de Abrão e Ló, seu sobrinho.",
          "Gênesis 12:5",
        ),
        fill(
          "Quando partiu, Abrão tinha",
          "anos.",
          ["75", "40", "100"],
          0,
          "Gênesis 12:4 informa que ele tinha 75 anos.",
          "Gênesis 12:4",
        ),
        mc(
          "Para qual terra Abrão segue?",
          ["Canaã", "Egito", "Grécia", "Pérsia"],
          0,
          "Abrão e sua família vão para a terra de Canaã.",
          "Gênesis 12:5",
        ),
      ],
      takeaways: [
        "Deus chama Abrão a deixar sua terra e promete bênção.",
        "Abrão parte de Harã com Sarai e Ló rumo a Canaã.",
        "Abraão é uma figura importante para judeus, cristãos e muçulmanos.",
      ],
      reflection: "Já precisou começar algo sem saber exatamente onde ia chegar? Como foi?",
    },
    {
      slug: "g03-promessa-e-espera",
      title: "Promessa e espera: Isaque",
      objective: "Acompanhar a longa espera de Abraão e Sara pelo filho prometido.",
      references: ["Gênesis 15:1-6", "Gênesis 17:1-5, 15-19", "Gênesis 18:1-15", "Gênesis 21:1-7"],
      context: "A promessa de uma grande descendência esbarra num problema: Abrão e Sarai não tinham filhos e já eram idosos.",
      blocks: [
        b(
          "resumo",
          "Conte as estrelas",
          "Deus leva Abrão para fora e diz que sua descendência seria tão numerosa quanto as estrelas do céu. O texto diz que Abrão creu, e isso lhe foi considerado como justiça.",
          "Gênesis 15:5-6",
        ),
        b(
          "resumo",
          "Novos nomes",
          "Mais tarde, Deus muda o nome de Abrão para Abraão e o de Sarai para Sara, reafirmando a promessa de um filho.",
          "Gênesis 17:5, 15-16",
        ),
        b(
          "resumo",
          "Visitantes e um riso",
          "Três visitantes chegam à tenda de Abraão, perto dos carvalhos de Manre, e anunciam que Sara teria um filho. Sara ri ao ouvir. Quando o menino nasce, recebe o nome de Isaque, que lembra “riso”.",
          "Gênesis 18:1-15; 21:1-7",
        ),
      ],
      exercises: [
        fill(
          "Deus diz que a descendência de Abrão seria numerosa como as",
          "do céu.",
          ["estrelas", "nuvens", "aves"],
          0,
          "Em Gênesis 15:5, Deus pede que Abrão conte as estrelas.",
          "Gênesis 15:5",
        ),
        match(
          "Associe os nomes antigos aos novos.",
          [
            ["Abrão", "Abraão"],
            ["Sarai", "Sara"],
          ],
          "Os nomes mudam em Gênesis 17, junto com a reafirmação da promessa.",
          "Gênesis 17:5, 15",
        ),
        tf(
          "Sara riu quando ouviu que teria um filho.",
          true,
          "Gênesis 18:12 conta que Sara riu consigo mesma.",
          "Gênesis 18:12",
        ),
        mc(
          "O nome Isaque está ligado a qual ideia?",
          ["Riso", "Força", "Paz", "Luz"],
          0,
          "O nome Isaque lembra “riso”, e o texto brinca com isso em Gênesis 21:6.",
          "Gênesis 21:3-6",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Promessa das estrelas", "Mudança dos nomes", "Visita dos três em Manre", "Nascimento de Isaque"],
          "Gênesis 15, 17, 18 e 21.",
          "Gênesis 15-21",
        ),
      ],
      takeaways: [
        "A promessa de descendência é comparada às estrelas.",
        "Abrão e Sarai recebem os nomes Abraão e Sara.",
        "Isaque nasce depois de longa espera; o nome lembra “riso”.",
      ],
      reflection: "Como você costuma viver as esperas da vida?",
    },
    {
      slug: "g03-esau-e-jaco",
      title: "Esaú e Jacó",
      objective: "Conhecer os gêmeos filhos de Isaque e a disputa pela bênção.",
      references: ["Gênesis 25:19-34", "Gênesis 27:1-40"],
      context: "Isaque se casa com Rebeca. Eles têm gêmeos muito diferentes, e a relação entre os irmãos é marcada por rivalidade.",
      blocks: [
        b(
          "resumo",
          "Dois irmãos diferentes",
          "Esaú, o primeiro a nascer, era caçador e homem do campo. Jacó era mais tranquilo e ficava nas tendas. Certo dia, Esaú chega faminto e troca seu direito de primogenitura por um prato de comida preparado por Jacó.",
          "Gênesis 25:24-34",
        ),
        b(
          "resumo",
          "A bênção",
          "Já idoso e com a vista fraca, Isaque quer abençoar Esaú. Rebeca orienta Jacó a se passar pelo irmão, e Jacó recebe a bênção. Esaú fica furioso, e Jacó precisa fugir.",
          "Gênesis 27:1-45",
        ),
        b(
          "explicacao",
          "Personagens reais, com falhas",
          "A Bíblia não esconde as falhas de seus personagens. A história mostra engano e conflito dentro de uma família — e, mais tarde, um reencontro entre os irmãos.",
          "Gênesis 33:1-4",
        ),
      ],
      exercises: [
        match(
          "Associe cada irmão à sua descrição.",
          [
            ["Esaú", "Caçador, homem do campo"],
            ["Jacó", "Tranquilo, ficava nas tendas"],
          ],
          "Gênesis 25:27 descreve os dois irmãos assim.",
          "Gênesis 25:27",
        ),
        mc(
          "Quem era a mãe de Esaú e Jacó?",
          ["Rebeca", "Sara", "Raquel", "Lia"],
          0,
          "Rebeca foi esposa de Isaque e mãe dos gêmeos.",
          "Gênesis 25:20-26",
        ),
        fill(
          "Esaú trocou seu direito de primogenitura por um prato de",
          ".",
          ["comida", "ouro", "frutas raras"],
          0,
          "O texto fala de pão e de um ensopado de lentilhas.",
          "Gênesis 25:29-34",
        ),
        tf(
          "Jacó recebeu a bênção de Isaque se passando por Esaú.",
          true,
          "Orientado por Rebeca, Jacó se passou pelo irmão.",
          "Gênesis 27:18-29",
        ),
        mc(
          "Mais tarde, como os irmãos se encontram?",
          ["Esaú abraça Jacó num reencontro", "Nunca mais se veem", "Esaú vira rei do Egito", "Jacó foge para o mar"],
          0,
          "Gênesis 33 conta o reencontro em que Esaú corre e abraça Jacó.",
          "Gênesis 33:4",
        ),
      ],
      takeaways: [
        "Esaú e Jacó eram gêmeos muito diferentes.",
        "Jacó obtém a primogenitura e a bênção de forma questionável.",
        "A história termina, mais adiante, com um reencontro.",
      ],
      reflection: "Existe alguma relação na sua vida que precisa de um reencontro?",
    },
    {
      slug: "g03-jaco-israel",
      title: "Jacó: uma escada e um novo nome",
      objective: "Conhecer dois encontros marcantes de Jacó com Deus.",
      references: ["Gênesis 28:10-22", "Gênesis 32:22-30"],
      context: "Fugindo do irmão, Jacó passa por experiências que mudam sua vida — e até seu nome.",
      blocks: [
        b(
          "resumo",
          "A escada em Betel",
          "Jacó dorme ao ar livre usando uma pedra como travesseiro e sonha com uma escada que ia da terra ao céu, com anjos subindo e descendo. Ao acordar, chama o lugar de Betel, que quer dizer “casa de Deus”.",
          "Gênesis 28:11-19",
        ),
        b(
          "resumo",
          "A luta no vau de Jaboque",
          "Anos depois, voltando para casa, Jacó passa a noite lutando com um homem misterioso até o amanhecer. Ele recebe um novo nome: Israel.",
          "Gênesis 32:22-28",
        ),
        b(
          "contexto",
          "Um nome que vira povo",
          "Os doze filhos de Jacó dão origem às doze tribos. Por isso, o povo passa a ser chamado de “Israel”, o novo nome de Jacó.",
          "Gênesis 35:22-26",
        ),
      ],
      exercises: [
        mc(
          "Com o que Jacó sonha em Betel?",
          ["Uma escada entre a terra e o céu", "Sete vacas magras", "Uma estátua de ouro", "Uma arca no mar"],
          0,
          "No sonho, anjos sobem e descem por uma escada.",
          "Gênesis 28:12",
        ),
        fill(
          "Betel quer dizer “casa de",
          "”.",
          ["Deus", "pão", "pedra"],
          0,
          "Jacó chama o lugar de Betel, “casa de Deus”.",
          "Gênesis 28:17-19",
        ),
        tf(
          "Depois da luta noturna, Jacó recebe o nome de Israel.",
          true,
          "Gênesis 32:28 registra o novo nome.",
          "Gênesis 32:28",
        ),
        mc(
          "Quantos filhos de Jacó dão origem às tribos de Israel?",
          ["Doze", "Sete", "Dez", "Quarenta"],
          0,
          "Os doze filhos de Jacó estão ligados às doze tribos.",
          "Gênesis 35:22-26",
        ),
        order(
          "Ordene a trajetória de Jacó.",
          ["Recebe a bênção de Isaque", "Sonha com a escada em Betel", "Luta durante a noite", "Recebe o nome Israel"],
          "Gênesis 27, 28 e 32.",
          "Gênesis 27-32",
        ),
      ],
      takeaways: [
        "Em Betel, Jacó sonha com uma escada entre terra e céu.",
        "Depois de uma luta noturna, Jacó recebe o nome Israel.",
        "Seus doze filhos estão na origem das tribos de Israel.",
      ],
      reflection: "Algum momento difícil já mudou o jeito como você se vê?",
    },
    {
      slug: "g03-jose-no-egito",
      title: "José no Egito",
      objective: "Acompanhar a história de José, da venda pelos irmãos ao reencontro.",
      references: ["Gênesis 37", "Gênesis 39-41", "Gênesis 45:1-15", "Gênesis 50:15-21"],
      context: "José, um dos filhos de Jacó, é protagonista de uma das narrativas mais longas de Gênesis.",
      blocks: [
        b(
          "resumo",
          "Vendido pelos irmãos",
          "José era o filho preferido de Jacó e ganhou dele uma túnica especial. Com inveja, seus irmãos o vendem a mercadores, que o levam ao Egito.",
          "Gênesis 37:3-28",
        ),
        b(
          "resumo",
          "Da prisão ao palácio",
          "No Egito, José é acusado injustamente e preso. Lá interpreta sonhos e, mais tarde, explica os sonhos do faraó: sete anos de fartura seguidos de sete anos de fome. O faraó o coloca para administrar o país.",
          "Gênesis 39-41",
        ),
        b(
          "resumo",
          "O reencontro",
          "Durante a fome, os irmãos vão ao Egito comprar alimento e não reconhecem José. Ele acaba revelando quem é, chora e os perdoa. Mais tarde, diz que o que eles planejaram para o mal, Deus transformou em bem.",
          "Gênesis 45:1-15; 50:19-21",
        ),
      ],
      exercises: [
        mc(
          "Por que os irmãos de José tinham inveja dele?",
          ["Ele era o preferido do pai", "Ele era o mais velho", "Ele era rei", "Ele tinha muitos rebanhos"],
          0,
          "Jacó amava José mais que os outros e lhe deu uma túnica especial.",
          "Gênesis 37:3-4",
        ),
        order(
          "Ordene a história de José.",
          ["É vendido pelos irmãos", "É preso no Egito", "Interpreta os sonhos do faraó", "Reencontra e perdoa os irmãos"],
          "Gênesis 37, 39, 41 e 45.",
          "Gênesis 37-45",
        ),
        fill(
          "Os sonhos do faraó anunciavam sete anos de fartura e sete anos de",
          ".",
          ["fome", "guerra", "chuva"],
          0,
          "José explica que viriam anos de fartura e depois de fome.",
          "Gênesis 41:29-30",
        ),
        tf(
          "Quando José revela quem é, ele se vinga dos irmãos.",
          false,
          "José chora, se revela e os perdoa.",
          "Gênesis 45:1-15",
        ),
        mc(
          "Para onde José foi levado depois de vendido?",
          ["Egito", "Babilônia", "Roma", "Canaã"],
          0,
          "Os mercadores levaram José ao Egito.",
          "Gênesis 37:28",
        ),
      ],
      takeaways: [
        "José foi vendido pelos irmãos e levado ao Egito.",
        "Ele interpreta os sonhos do faraó e administra o país.",
        "A história termina com perdão e reconciliação.",
      ],
      reflection: "Perdoar não é fingir que nada aconteceu. O que a história de José ensina sobre isso?",
    },
  ],
  review: {
    slug: "g03-revisao",
    title: "Revisão: Abraão e sua família",
    intro: "Quatro gerações em uma unidade! Vamos relembrar Abraão, Isaque, Jacó e José.",
    extra: [
      order(
        "Ordene as gerações da família.",
        ["Abraão", "Isaque", "Jacó", "José"],
        "Abraão é pai de Isaque, que é pai de Jacó, que é pai de José.",
        "Gênesis 12-50",
      ),
      match(
        "Associe cada personagem a um acontecimento.",
        [
          ["Abraão", "Chamado a sair de Harã"],
          ["Jacó", "Sonho com a escada"],
          ["José", "Interpreta sonhos do faraó"],
          ["Sara", "Ri ao ouvir a promessa"],
        ],
        "Cada personagem tem um momento marcante.",
        "Gênesis 12; 18; 28; 41",
      ),
      tf(
        "Israel é o novo nome dado a Jacó.",
        true,
        "Depois da luta noturna, Jacó passa a se chamar Israel.",
        "Gênesis 32:28",
      ),
    ],
    takeaways: [
      "A família de Abraão vive entre promessas e esperas.",
      "Os personagens têm falhas reais, e a Bíblia não as esconde.",
      "A história de José termina em perdão e reconciliação.",
    ],
  },
};
