import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const u04: UnitDef = {
  slug: "geral-u04-moises-e-o-exodo",
  title: "Moisés e o Êxodo",
  description: "Do cesto no rio Nilo à aliança no monte Sinai.",
  scene: "desert",
  lessons: [
    {
      slug: "g04-bebe-no-nilo",
      title: "Um bebê no rio Nilo",
      objective: "Conhecer o contexto do Êxodo e o nascimento de Moisés.",
      references: ["Êxodo 1:8-22", "Êxodo 2:1-10"],
      context:
        "Séculos depois de José, os descendentes de Jacó tinham se multiplicado no Egito. Um novo faraó, que não conhecera José, passa a oprimi-los.",
      blocks: [
        b(
          "resumo",
          "Opressão no Egito",
          "O faraó impõe trabalhos forçados aos hebreus e ordena que os meninos recém-nascidos sejam lançados no rio Nilo. As parteiras Sifrá e Puá se recusam a cumprir a ordem.",
          "Êxodo 1:8-22",
        ),
        b(
          "resumo",
          "O cesto",
          "Uma mulher da tribo de Levi esconde seu bebê por três meses. Depois, o coloca num cesto calafetado entre os juncos do Nilo, enquanto a irmã do menino observa de longe.",
          "Êxodo 2:1-4",
        ),
        b(
          "resumo",
          "Tirado das águas",
          "A filha do faraó encontra o cesto e tem compaixão do bebê. A irmã do menino oferece uma ama hebreia — a própria mãe dele. A princesa o adota e lhe dá o nome de Moisés, explicando que o tirou das águas.",
          "Êxodo 2:5-10",
        ),
      ],
      exercises: [
        match(
          "Associe cada pessoa ao que fez.",
          [
            ["Sifrá e Puá", "Parteiras que não obedeceram ao faraó"],
            ["A filha do faraó", "Encontrou e adotou o bebê"],
            ["A irmã de Moisés", "Observou o cesto de longe"],
          ],
          "Várias mulheres protegem a vida do menino no relato.",
          "Êxodo 1:15-21; 2:4-10",
        ),
        mc(
          "Por que a mãe de Moisés coloca o bebê num cesto?",
          [
            "Para protegê-lo da ordem do faraó",
            "Para mandá-lo ao Egito",
            "Porque ele estava doente",
            "Para que ele aprendesse a nadar",
          ],
          0,
          "O faraó tinha ordenado que os meninos hebreus fossem lançados no Nilo.",
          "Êxodo 1:22; 2:3",
        ),
        tf(
          "Moisés foi amamentado pela própria mãe, a pedido da filha do faraó.",
          true,
          "A irmã de Moisés indicou uma ama hebreia: a mãe do bebê.",
          "Êxodo 2:7-9",
        ),
        fill(
          "O nome Moisés é explicado no texto porque ele foi tirado das",
          ".",
          ["águas", "pedras", "areias"],
          0,
          "A filha do faraó diz que o tirou das águas.",
          "Êxodo 2:10",
        ),
        order(
          "Ordene os acontecimentos.",
          ["O faraó oprime os hebreus", "A mãe esconde o bebê", "O cesto é colocado no Nilo", "A filha do faraó adota Moisés"],
          "Êxodo 1-2 conta essa sequência.",
          "Êxodo 1:8-2:10",
        ),
      ],
      takeaways: [
        "Os hebreus eram oprimidos no Egito.",
        "Mulheres corajosas protegem a vida de Moisés.",
        "A filha do faraó adota o menino e lhe dá o nome Moisés.",
      ],
      reflection: "Quem foram as pessoas que, como essas mulheres, cuidaram de você?",
    },
    {
      slug: "g04-sarca-ardente",
      title: "A sarça ardente",
      objective: "Conhecer o chamado de Moisés no monte Horebe.",
      references: ["Êxodo 2:11-15", "Êxodo 3:1-15"],
      context:
        "Adulto, Moisés foge do Egito depois de matar um egípcio que agredia um hebreu. Ele vai para Midiã, onde se torna pastor.",
      blocks: [
        b(
          "resumo",
          "Uma sarça que não se consome",
          "Pastoreando o rebanho de seu sogro Jetro, Moisés chega ao Horebe, o monte de Deus. Vê uma sarça em chamas que não se consumia. Ao se aproximar, ouve Deus chamá-lo e pedir que tire as sandálias, pois o lugar era santo.",
          "Êxodo 3:1-5",
        ),
        b(
          "resumo",
          "“Eu vi a aflição do meu povo”",
          "Deus diz que viu o sofrimento dos israelitas no Egito e que envia Moisés ao faraó para tirar o povo de lá.",
          "Êxodo 3:7-10",
        ),
        b(
          "resumo",
          "O nome",
          "Moisés pergunta qual nome deveria dizer ao povo. Deus responde: “Eu Sou o que Sou”. Esse trecho é ligado ao nome divino escrito com as letras hebraicas YHWH, que muitas Bíblias traduzem por “Senhor”.",
          "Êxodo 3:13-15",
        ),
      ],
      exercises: [
        mc(
          "O que chama a atenção de Moisés no monte?",
          ["Uma sarça que queimava sem se consumir", "Uma nuvem de gafanhotos", "Uma estrela brilhante", "Um rio vermelho"],
          0,
          "A sarça ardia, mas não se consumia.",
          "Êxodo 3:2-3",
        ),
        fill(
          "Deus pede que Moisés tire as",
          ", pois o lugar era santo.",
          ["sandálias", "roupas", "pedras"],
          0,
          "Tirar as sandálias era sinal de respeito diante do sagrado.",
          "Êxodo 3:5",
        ),
        tf(
          "Moisés estava cuidando do rebanho de seu sogro, Jetro.",
          true,
          "Êxodo 3:1 diz que Moisés pastoreava o rebanho de Jetro.",
          "Êxodo 3:1",
        ),
        mc(
          "Para onde Moisés tinha fugido antes do chamado?",
          ["Midiã", "Babilônia", "Grécia", "Roma"],
          0,
          "Moisés fugiu do faraó e foi viver em Midiã.",
          "Êxodo 2:15",
        ),
        mc(
          "Qual resposta Deus dá quando Moisés pergunta seu nome?",
          ["“Eu Sou o que Sou”", "“O Deus dos exércitos”", "“O Pastor de Israel”", "“O Altíssimo”"],
          0,
          "Êxodo 3:14 traz a resposta “Eu Sou o que Sou”.",
          "Êxodo 3:14",
        ),
      ],
      takeaways: [
        "Moisés é chamado diante de uma sarça que não se consumia.",
        "Deus diz ter visto o sofrimento do povo e envia Moisés.",
        "A resposta “Eu Sou o que Sou” está ligada ao nome divino YHWH.",
      ],
      reflection: "Moisés recebeu um chamado num dia comum de trabalho. O que isso sugere sobre os dias comuns?",
    },
    {
      slug: "g04-pragas-e-pascoa",
      title: "As pragas e a Páscoa",
      objective: "Entender o confronto com o faraó e a origem da Páscoa.",
      references: ["Êxodo 7-11", "Êxodo 12:1-42"],
      context: "Moisés e seu irmão Arão pedem ao faraó que deixe o povo partir. O faraó se recusa várias vezes.",
      blocks: [
        b(
          "resumo",
          "Dez pragas",
          "O livro do Êxodo narra dez pragas sobre o Egito — entre elas, as águas que viram sangue, as rãs, os gafanhotos e as trevas. A cada praga, o faraó endurece o coração e não deixa o povo sair.",
          "Êxodo 7-10",
        ),
        b(
          "resumo",
          "A noite da Páscoa",
          "Antes da última praga, as famílias israelitas preparam um cordeiro, marcam os batentes das portas com seu sangue e comem com pão sem fermento, prontas para partir. Naquela noite morrem os primogênitos do Egito, e o faraó finalmente deixa o povo sair.",
          "Êxodo 12:1-32",
        ),
        b(
          "contexto",
          "Uma festa para lembrar",
          "A Páscoa (Pessach, em hebraico) passou a ser celebrada todos os anos pelo povo judeu como memória da libertação. No cristianismo, a Páscoa ganhou também o sentido da morte e ressurreição de Jesus, que aconteceram na época dessa festa.",
          "Êxodo 12:14; Marcos 14:12",
        ),
      ],
      exercises: [
        match(
          "Associe as pessoas a seus papéis.",
          [
            ["Moisés", "Líder enviado por Deus"],
            ["Arão", "Irmão que fala junto com Moisés"],
            ["Faraó", "Rei do Egito que resiste"],
          ],
          "Moisés e Arão se apresentam ao faraó juntos.",
          "Êxodo 5:1; 7:1-2",
        ),
        mc(
          "Quantas pragas o livro do Êxodo narra?",
          ["Dez", "Sete", "Doze", "Três"],
          0,
          "São dez pragas, de Êxodo 7 a 12.",
          "Êxodo 7-12",
        ),
        fill(
          "Na noite da Páscoa, comia-se o cordeiro com pão sem",
          ".",
          ["fermento", "sal", "trigo"],
          0,
          "O pão sem fermento lembra a pressa da partida.",
          "Êxodo 12:8, 39",
        ),
        tf(
          "No cristianismo, a Páscoa também lembra a morte e a ressurreição de Jesus.",
          true,
          "Jesus morreu e ressuscitou na época da festa da Páscoa.",
          "Marcos 14:12; 16:1-6",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Moisés e Arão vão ao faraó", "As pragas atingem o Egito", "As famílias celebram a Páscoa", "O povo sai do Egito"],
          "Êxodo 5-12.",
          "Êxodo 5-12",
        ),
      ],
      takeaways: [
        "Moisés e Arão pedem ao faraó a libertação do povo.",
        "As dez pragas culminam na noite da Páscoa.",
        "A Páscoa é memória da libertação; para cristãos, também da ressurreição.",
      ],
      reflection: "Que acontecimento da sua vida você gostaria de lembrar todo ano?",
    },
    {
      slug: "g04-travessia-do-mar",
      title: "A travessia do mar",
      objective: "Conhecer o relato da passagem pelo mar e o cântico de libertação.",
      references: ["Êxodo 13:17-22", "Êxodo 14", "Êxodo 15:1-21"],
      context: "O povo sai do Egito, mas o faraó muda de ideia e manda seu exército atrás deles.",
      blocks: [
        b(
          "resumo",
          "Nuvem e fogo",
          "Deus guia o povo com uma coluna de nuvem durante o dia e uma coluna de fogo durante a noite.",
          "Êxodo 13:21-22",
        ),
        b(
          "resumo",
          "Um caminho no meio do mar",
          "Encurralado entre o mar e o exército egípcio, o povo tem medo. Moisés estende a mão sobre o mar, um forte vento sopra a noite toda e as águas se abrem. Os israelitas atravessam em terra seca; depois, as águas voltam sobre os carros egípcios.",
          "Êxodo 14:10-28",
        ),
        b(
          "resumo",
          "Cânticos",
          "Do outro lado, Moisés e o povo cantam a Deus. Miriã, a profetisa, irmã de Arão, pega um tamborim e lidera as mulheres em dança e canto.",
          "Êxodo 15:1-21",
        ),
      ],
      exercises: [
        match(
          "Associe cada sinal ao momento do dia.",
          [
            ["Coluna de nuvem", "Durante o dia"],
            ["Coluna de fogo", "Durante a noite"],
          ],
          "As colunas guiavam o povo no deserto.",
          "Êxodo 13:21",
        ),
        mc(
          "O que Moisés faz antes de as águas se abrirem?",
          ["Estende a mão sobre o mar", "Bate numa rocha", "Sobe ao monte", "Toca uma trombeta"],
          0,
          "Moisés estende a mão sobre o mar, e um vento forte sopra.",
          "Êxodo 14:21",
        ),
        tf(
          "Os israelitas atravessaram o mar em terra seca.",
          true,
          "O texto afirma que eles passaram em terra seca.",
          "Êxodo 14:22",
        ),
        fill(
          "Miriã pegou um",
          "e liderou as mulheres em canto e dança.",
          ["tamborim", "cajado", "rolo"],
          0,
          "Miriã celebra com tamborim depois da travessia.",
          "Êxodo 15:20",
        ),
        order(
          "Ordene os acontecimentos.",
          ["O faraó persegue o povo", "Moisés estende a mão sobre o mar", "O povo atravessa", "Moisés e Miriã cantam"],
          "Êxodo 14-15.",
          "Êxodo 14-15",
        ),
      ],
      takeaways: [
        "Deus guia o povo com colunas de nuvem e de fogo.",
        "O povo atravessa o mar em terra seca.",
        "A libertação é celebrada com cânticos de Moisés e Miriã.",
      ],
      reflection: "Qual foi um momento em que você sentiu que o caminho se abriu?",
    },
    {
      slug: "g04-dez-mandamentos",
      title: "Os Dez Mandamentos",
      objective: "Conhecer a aliança no Sinai e os Dez Mandamentos.",
      references: ["Êxodo 19:1-8", "Êxodo 20:1-17", "Deuteronômio 5:6-21"],
      context: "Três meses depois de sair do Egito, o povo acampa diante do monte Sinai.",
      blocks: [
        b(
          "resumo",
          "Uma aliança",
          "No Sinai, Deus lembra que tirou o povo do Egito e propõe uma aliança: Israel seria um povo dedicado a Ele. O povo responde que fará tudo o que o Senhor disse.",
          "Êxodo 19:3-8",
        ),
        b(
          "resumo",
          "As “dez palavras”",
          "Deus dá os mandamentos, que falam de adorar só a Deus, não fazer ídolos, respeitar o nome de Deus, guardar o dia de descanso, honrar pai e mãe, e não matar, não cometer adultério, não furtar, não dar falso testemunho e não cobiçar.",
          "Êxodo 20:1-17",
        ),
        b(
          "tradicoes",
          "A numeração muda",
          "O texto não numera os mandamentos. Por isso, tradições dividem de formas diferentes: a tradição católica (e a luterana) une a proibição de ídolos ao primeiro mandamento e divide o “não cobiçar” em dois; muitas tradições protestantes contam “não farás imagens” como segundo mandamento. O conteúdo é o mesmo.",
        ),
      ],
      exercises: [
        mc(
          "Em qual monte o povo recebe os mandamentos?",
          ["Sinai", "Carmelo", "Ararate", "Sião"],
          0,
          "Os mandamentos são dados no monte Sinai (também chamado Horebe).",
          "Êxodo 19:20; 20:1",
        ),
        tf(
          "Todas as tradições cristãs numeram os Dez Mandamentos exatamente da mesma forma.",
          false,
          "A divisão muda entre tradições; o conteúdo é o mesmo.",
          "Êxodo 20:1-17",
        ),
        fill(
          "Um dos mandamentos pede: “Honra teu pai e tua",
          "”.",
          ["mãe", "casa", "terra"],
          0,
          "Honrar pai e mãe está em Êxodo 20:12.",
          "Êxodo 20:12",
        ),
        mc(
          "Qual destes NÃO está entre os Dez Mandamentos?",
          ["Construir um templo em Jerusalém", "Não furtar", "Guardar o dia de descanso", "Não dar falso testemunho"],
          0,
          "Construir um templo não faz parte dos Dez Mandamentos.",
          "Êxodo 20:1-17",
        ),
        match(
          "Associe cada termo ao seu significado.",
          [
            ["Aliança", "Compromisso entre Deus e o povo"],
            ["Sinai", "Monte onde a aliança é feita"],
            ["Decálogo", "Outro nome para os Dez Mandamentos"],
          ],
          "“Decálogo” vem do grego e significa “dez palavras”.",
          "Êxodo 19-20",
        ),
      ],
      takeaways: [
        "No Sinai, Deus faz uma aliança com o povo libertado.",
        "Os Dez Mandamentos falam da relação com Deus e com o próximo.",
        "Tradições numeram os mandamentos de formas diferentes.",
      ],
      reflection: "Qual desses mandamentos você acha mais atual para os dias de hoje?",
    },
  ],
  review: {
    slug: "g04-revisao",
    title: "Revisão: Moisés e o Êxodo",
    intro: "Do Nilo ao Sinai! Vamos relembrar a grande história da libertação.",
    extra: [
      order(
        "Ordene a trajetória de Moisés.",
        ["Cesto no Nilo", "Sarça ardente", "Pragas e Páscoa", "Travessia do mar", "Mandamentos no Sinai"],
        "Êxodo 2, 3, 7-12, 14 e 20.",
        "Êxodo 2-20",
      ),
      match(
        "Associe cada pessoa a um momento.",
        [
          ["Miriã", "Canta com tamborim"],
          ["Jetro", "Sogro de Moisés"],
          ["Arão", "Vai com Moisés ao faraó"],
        ],
        "Personagens que acompanham Moisés.",
        "Êxodo 3:1; 5:1; 15:20",
      ),
      tf(
        "A Páscoa judaica lembra a libertação do Egito.",
        true,
        "A festa foi instituída como memória da saída do Egito.",
        "Êxodo 12:14",
      ),
    ],
    takeaways: [
      "Moisés é protegido, chamado e enviado para libertar o povo.",
      "A Páscoa e a travessia do mar marcam a libertação.",
      "No Sinai, a aliança é selada com os mandamentos.",
    ],
  },
};
