import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const u07: UnitDef = {
  slug: "geral-u07-parabolas",
  title: "Parábolas e ensinamentos",
  description: "Histórias curtas e ensinamentos de Jesus que atravessaram os séculos.",
  scene: "garden",
  lessons: [
    {
      slug: "g07-semeador",
      title: "O que é uma parábola? O semeador",
      objective: "Entender o que são parábolas a partir da parábola do semeador.",
      references: ["Mateus 13:1-23", "Marcos 4:1-20"],
      context:
        "Jesus ensinava muitas vezes com parábolas: histórias curtas, tiradas do dia a dia, que fazem pensar. A palavra vem do grego e sugere “colocar lado a lado”, comparar.",
      blocks: [
        b(
          "resumo",
          "Sementes em quatro terrenos",
          "Um semeador espalha sementes. Algumas caem à beira do caminho e as aves comem; outras em terreno com pedras e secam; outras entre espinhos e são sufocadas; outras em terra boa e produzem muito fruto.",
          "Mateus 13:3-8",
        ),
        b(
          "resumo",
          "A explicação",
          "Os Evangelhos trazem uma explicação: a semente é a palavra, e os terrenos representam formas diferentes de recebê-la — de quem não compreende a quem ouve, entende e dá fruto.",
          "Mateus 13:18-23",
        ),
        b(
          "explicacao",
          "Por que histórias?",
          "Parábolas convidam quem ouve a se encontrar na história. Elas não são fábulas com animais falantes; usam cenas comuns — sementes, moedas, festas, ovelhas — para falar do Reino de Deus.",
        ),
      ],
      exercises: [
        mc(
          "O que é uma parábola?",
          [
            "Uma história curta do cotidiano usada para ensinar",
            "Uma lei do Antigo Testamento",
            "Uma oração em forma de poema",
            "Uma carta de um apóstolo",
          ],
          0,
          "Parábolas usam cenas comuns para fazer pensar.",
          "Mateus 13:3",
        ),
        match(
          "Associe cada terreno ao que acontece com a semente.",
          [
            ["Beira do caminho", "As aves comem"],
            ["Terreno com pedras", "A planta seca"],
            ["Entre espinhos", "É sufocada"],
            ["Terra boa", "Produz muito fruto"],
          ],
          "Cada terreno tem um resultado diferente.",
          "Mateus 13:4-8",
        ),
        fill(
          "Na explicação da parábola, a semente representa a",
          ".",
          ["palavra", "chuva", "colheita"],
          0,
          "A semente é a palavra do Reino.",
          "Mateus 13:19",
        ),
        tf(
          "Parábolas costumam usar cenas comuns do dia a dia.",
          true,
          "Sementes, moedas, festas e ovelhas aparecem nas parábolas.",
          "Mateus 13; Lucas 15",
        ),
        order(
          "Ordene os terrenos como aparecem no relato.",
          ["Beira do caminho", "Terreno com pedras", "Entre espinhos", "Terra boa"],
          "Essa é a ordem da parábola em Mateus.",
          "Mateus 13:4-8",
        ),
      ],
      takeaways: [
        "Parábolas são histórias curtas que comparam e fazem pensar.",
        "No semeador, os terrenos mostram formas de receber a palavra.",
        "As parábolas usam cenas do cotidiano.",
      ],
      reflection: "Hoje, seu coração está mais parecido com qual terreno?",
    },
    {
      slug: "g07-bom-samaritano",
      title: "O bom samaritano",
      objective: "Conhecer a parábola do bom samaritano e a pergunta “quem é o meu próximo?”.",
      references: ["Lucas 10:25-37"],
      context: "Um especialista na Lei pergunta a Jesus o que fazer para herdar a vida eterna. A conversa chega a uma pergunta: “Quem é o meu próximo?”.",
      blocks: [
        b(
          "resumo",
          "No caminho de Jericó",
          "Um homem que descia de Jerusalém para Jericó é assaltado e deixado quase morto. Um sacerdote passa e segue adiante; um levita faz o mesmo. Um samaritano o vê, tem compaixão, cuida de suas feridas e paga uma hospedaria para ele.",
          "Lucas 10:30-35",
        ),
        b(
          "contexto",
          "Por que um samaritano?",
          "Judeus e samaritanos tinham uma longa rivalidade religiosa e histórica. Colocar um samaritano como exemplo era surpreendente para quem ouvia.",
          "João 4:9",
        ),
        b(
          "resumo",
          "A pergunta invertida",
          "No fim, Jesus pergunta: qual dos três foi o próximo do homem ferido? A resposta é “aquele que teve misericórdia”. E Jesus diz: “Vai e faze tu o mesmo”.",
          "Lucas 10:36-37",
        ),
      ],
      exercises: [
        order(
          "Ordene quem passou pelo homem ferido.",
          ["O sacerdote", "O levita", "O samaritano"],
          "O sacerdote e o levita passam adiante; o samaritano para e cuida.",
          "Lucas 10:31-33",
        ),
        mc(
          "Qual era o caminho onde o homem foi assaltado?",
          ["De Jerusalém para Jericó", "De Belém para Nazaré", "Do Egito para Canaã", "De Roma para Atenas"],
          0,
          "Ele descia de Jerusalém para Jericó.",
          "Lucas 10:30",
        ),
        tf(
          "Para quem ouvia Jesus, era esperado que um samaritano fosse o herói da história.",
          false,
          "A rivalidade entre judeus e samaritanos tornava a escolha surpreendente.",
          "Lucas 10:33; João 4:9",
        ),
        fill(
          "O próximo do homem ferido foi “aquele que teve",
          "”.",
          ["misericórdia", "pressa", "medo"],
          0,
          "A resposta do especialista na Lei está em Lucas 10:37.",
          "Lucas 10:37",
        ),
        mc(
          "Qual pergunta motivou a parábola?",
          ["“Quem é o meu próximo?”", "“Quantas vezes devo perdoar?”", "“Quem é o maior?”", "“Onde está meu irmão?”"],
          0,
          "O especialista na Lei pergunta quem é o seu próximo.",
          "Lucas 10:29",
        ),
      ],
      takeaways: [
        "Um samaritano cuida do homem ferido quando outros passam adiante.",
        "A escolha do samaritano surpreendia os ouvintes.",
        "A pergunta muda: não “quem é meu próximo?”, mas “de quem eu me faço próximo?”.",
      ],
      reflection: "Quem está “à beira do seu caminho” e talvez precise de cuidado?",
    },
    {
      slug: "g07-filho-prodigo",
      title: "O filho que voltou para casa",
      objective: "Conhecer a parábola do filho pródigo e seus três personagens.",
      references: ["Lucas 15:1-3", "Lucas 15:11-32"],
      context:
        "Lucas 15 reúne três parábolas sobre algo perdido e encontrado: uma ovelha, uma moeda e um filho. Elas respondem a críticas de que Jesus acolhia pessoas mal vistas.",
      blocks: [
        b(
          "resumo",
          "O filho mais novo",
          "Um filho pede ao pai sua parte da herança, vai para longe e gasta tudo. Passando fome, trabalhando cuidando de porcos, ele decide voltar e pedir para ser tratado como empregado.",
          "Lucas 15:11-19",
        ),
        b(
          "resumo",
          "O pai que corre",
          "Ainda de longe, o pai o vê, tem compaixão, corre, o abraça e o beija. Ele manda trazer roupa, anel e sandálias e prepara uma festa.",
          "Lucas 15:20-24",
        ),
        b(
          "resumo",
          "O filho mais velho",
          "O irmão mais velho fica irritado e não quer entrar na festa. O pai sai para conversar com ele e diz que era preciso celebrar, porque o irmão estava perdido e foi encontrado.",
          "Lucas 15:25-32",
        ),
      ],
      exercises: [
        match(
          "Associe cada parábola de Lucas 15 ao que foi perdido.",
          [
            ["Primeira parábola", "Uma ovelha"],
            ["Segunda parábola", "Uma moeda"],
            ["Terceira parábola", "Um filho"],
          ],
          "Lucas 15 traz três histórias de perdido e encontrado.",
          "Lucas 15:4-32",
        ),
        mc(
          "O que o pai faz ao ver o filho voltando?",
          ["Corre, abraça e o beija", "Fecha a porta", "Pede que ele trabalhe como empregado", "Manda o irmão mais velho recebê-lo"],
          0,
          "O pai tem compaixão e corre ao encontro do filho.",
          "Lucas 15:20",
        ),
        tf(
          "O filho mais velho entra feliz na festa logo no início.",
          false,
          "Ele fica irritado e não quer entrar; o pai sai para conversar com ele.",
          "Lucas 15:28",
        ),
        order(
          "Ordene a parábola.",
          ["O filho pede a herança", "Gasta tudo longe de casa", "Decide voltar", "O pai faz uma festa"],
          "Lucas 15:12-24.",
          "Lucas 15:11-24",
        ),
        fill(
          "O pai diz que o filho estava perdido e foi",
          ".",
          ["encontrado", "castigado", "esquecido"],
          0,
          "A frase aparece em Lucas 15:24 e 32.",
          "Lucas 15:24, 32",
        ),
      ],
      takeaways: [
        "Lucas 15 tem três parábolas de perdido e encontrado.",
        "O pai acolhe o filho com festa antes de qualquer cobrança.",
        "O irmão mais velho também é convidado a entrar na alegria.",
      ],
      reflection: "Com qual personagem você se identifica hoje: o filho mais novo, o mais velho ou o pai?",
    },
    {
      slug: "g07-bem-aventurancas",
      title: "As bem-aventuranças",
      objective: "Conhecer o início do Sermão do Monte.",
      references: ["Mateus 5:1-12", "Lucas 6:20-23"],
      context:
        "Mateus reúne ensinamentos de Jesus em um grande discurso, conhecido como Sermão do Monte (capítulos 5 a 7). Ele começa com as bem-aventuranças.",
      blocks: [
        b(
          "resumo",
          "“Felizes os…”",
          "Jesus chama de felizes (ou bem-aventurados) os pobres em espírito, os que choram, os mansos, os que têm fome e sede de justiça, os misericordiosos, os puros de coração, os que promovem a paz e os perseguidos por causa da justiça.",
          "Mateus 5:3-10",
        ),
        b(
          "explicacao",
          "Uma felicidade inesperada",
          "As bem-aventuranças surpreendem porque chamam de felizes pessoas que o mundo costuma ver como fracas. Cada uma vem acompanhada de uma promessa.",
        ),
        b(
          "contexto",
          "Mateus e Lucas",
          "Lucas tem uma versão mais curta, num lugar plano (por isso chamada às vezes de Sermão da Planície), e acrescenta também alguns “ais”.",
          "Lucas 6:17-26",
        ),
      ],
      exercises: [
        mc(
          "Em qual Evangelho está o Sermão do Monte com as bem-aventuranças?",
          ["Mateus", "Marcos", "João", "Atos"],
          0,
          "O Sermão do Monte está em Mateus 5-7.",
          "Mateus 5:1-12",
        ),
        fill(
          "“Felizes os que promovem a",
          ", pois serão chamados filhos de Deus.”",
          ["paz", "festa", "riqueza"],
          0,
          "Essa bem-aventurança está em Mateus 5:9.",
          "Mateus 5:9",
        ),
        match(
          "Associe cada grupo à promessa em Mateus 5.",
          [
            ["Os que choram", "Serão consolados"],
            ["Os mansos", "Herdarão a terra"],
            ["Os misericordiosos", "Alcançarão misericórdia"],
          ],
          "Cada bem-aventurança traz uma promessa.",
          "Mateus 5:4-7",
        ),
        tf(
          "Lucas também tem uma versão das bem-aventuranças.",
          true,
          "Lucas 6:20-23 traz uma versão mais curta.",
          "Lucas 6:20-23",
        ),
        mc(
          "Por que as bem-aventuranças surpreendem?",
          [
            "Chamam de felizes pessoas vistas como fracas",
            "Falam apenas de riquezas",
            "Proíbem a alegria",
            "São regras para sacerdotes",
          ],
          0,
          "Elas invertem a ideia comum de quem é feliz.",
          "Mateus 5:3-10",
        ),
      ],
      takeaways: [
        "O Sermão do Monte começa com as bem-aventuranças.",
        "Elas chamam de felizes pessoas que o mundo vê como fracas.",
        "Lucas traz uma versão mais curta.",
      ],
      reflection: "Qual bem-aventurança mais toca você hoje?",
    },
    {
      slug: "g07-pai-nosso",
      title: "O Pai-Nosso",
      objective: "Conhecer a oração ensinada por Jesus e suas versões.",
      references: ["Mateus 6:5-15", "Lucas 11:1-4"],
      context: "Os discípulos pedem a Jesus que os ensine a orar. A oração que ele ensina se tornou a mais conhecida do cristianismo.",
      blocks: [
        b(
          "resumo",
          "Orar sem exibição",
          "No Sermão do Monte, Jesus orienta a não orar para ser visto pelos outros nem com muitas palavras repetidas, porque o Pai sabe do que precisamos.",
          "Mateus 6:5-8",
        ),
        b(
          "resumo",
          "Os pedidos",
          "A oração se dirige a Deus como Pai, pede que seu nome seja santificado, que venha o seu Reino e se faça a sua vontade; depois pede o pão de cada dia, o perdão — assim como perdoamos — e proteção diante da tentação e do mal.",
          "Mateus 6:9-13",
        ),
        b(
          "tradicoes",
          "“Pois teu é o Reino…”",
          "Muitas tradições protestantes terminam com “pois teu é o Reino, o poder e a glória para sempre”. Essa frase não está nos manuscritos mais antigos de Mateus. Na missa católica, uma frase parecida é dita depois de uma oração intermediária. Lucas traz uma versão mais curta.",
          "Mateus 6:13; Lucas 11:2-4",
        ),
      ],
      exercises: [
        mc(
          "Como a oração ensinada por Jesus começa se dirigindo a Deus?",
          ["Como Pai", "Como Rei dos exércitos", "Como Juiz", "Como Criador do céu"],
          0,
          "A oração começa com “Pai nosso”.",
          "Mateus 6:9",
        ),
        fill(
          "Na oração, pede-se o",
          "de cada dia.",
          ["pão", "vinho", "trabalho"],
          0,
          "“O pão nosso de cada dia” está em Mateus 6:11.",
          "Mateus 6:11",
        ),
        tf(
          "A frase final “pois teu é o Reino, o poder e a glória” aparece em todos os manuscritos antigos de Mateus.",
          false,
          "Ela não está nos manuscritos mais antigos; é usada por muitas tradições como louvor final.",
          "Mateus 6:13",
        ),
        match(
          "Associe cada Evangelho à sua versão do Pai-Nosso.",
          [
            ["Mateus", "Versão mais longa, no Sermão do Monte"],
            ["Lucas", "Versão mais curta, após um pedido dos discípulos"],
          ],
          "As duas versões aparecem em contextos diferentes.",
          "Mateus 6:9-13; Lucas 11:1-4",
        ),
        mc(
          "O que Jesus orienta sobre a oração em Mateus 6?",
          [
            "Não orar para ser visto pelos outros",
            "Orar só no templo",
            "Orar apenas em voz alta",
            "Repetir muitas palavras",
          ],
          0,
          "Jesus critica a oração feita para exibição.",
          "Mateus 6:5-8",
        ),
      ],
      takeaways: [
        "O Pai-Nosso foi ensinado por Jesus aos discípulos.",
        "Ela reúne louvor e pedidos: Reino, pão, perdão e proteção.",
        "Tradições terminam a oração de formas diferentes.",
      ],
      reflection: "Qual pedido do Pai-Nosso faz mais sentido para você hoje?",
    },
  ],
  review: {
    slug: "g07-revisao",
    title: "Revisão: Parábolas e ensinamentos",
    intro: "Sementes, caminhos, festas e orações: vamos relembrar os ensinamentos desta unidade.",
    extra: [
      match(
        "Associe cada ensinamento a uma frase-chave.",
        [
          ["Bom samaritano", "Teve misericórdia"],
          ["Filho pródigo", "Estava perdido e foi encontrado"],
          ["Semeador", "Terra boa dá fruto"],
          ["Pai-Nosso", "Pão de cada dia"],
        ],
        "Cada ensinamento tem uma ideia central.",
        "Lucas 10; Lucas 15; Mateus 13; Mateus 6",
      ),
      mc(
        "Onde estão o Sermão do Monte e o Pai-Nosso mais longo?",
        ["Mateus 5-7", "Lucas 15", "João 1", "Marcos 4"],
        0,
        "Mateus 5-7 reúne o Sermão do Monte, incluindo o Pai-Nosso.",
        "Mateus 5-7",
      ),
      tf(
        "As três parábolas de Lucas 15 falam de algo perdido e encontrado.",
        true,
        "Ovelha, moeda e filho.",
        "Lucas 15",
      ),
    ],
    takeaways: [
      "Parábolas ensinam com histórias do cotidiano.",
      "Compaixão e acolhida estão no centro dessas histórias.",
      "As bem-aventuranças e o Pai-Nosso resumem o jeito de viver ensinado por Jesus.",
    ],
  },
};
