import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const u08: UnitDef = {
  slug: "geral-u08-morte-e-ressurreicao",
  title: "Morte e ressurreição de Jesus",
  description: "A última semana de Jesus em Jerusalém, a cruz e o túmulo vazio.",
  scene: "city",
  lessons: [
    {
      slug: "g08-entrada-em-jerusalem",
      title: "A entrada em Jerusalém",
      objective: "Conhecer a chegada de Jesus a Jerusalém antes da Páscoa.",
      references: ["Marcos 11:1-11", "João 12:12-16", "Marcos 11:15-18"],
      context:
        "Os quatro Evangelhos dedicam muito espaço à última semana de Jesus. Ela começa com sua chegada a Jerusalém, perto da festa da Páscoa.",
      blocks: [
        b(
          "resumo",
          "Montado num jumentinho",
          "Jesus entra em Jerusalém montado num jumentinho. A multidão estende mantos e ramos pelo caminho e grita “Hosana!”, saudando aquele que vem em nome do Senhor.",
          "Marcos 11:7-10",
        ),
        b(
          "contexto",
          "Um gesto cheio de sentido",
          "O Evangelho de João liga a cena a uma passagem do profeta Zacarias, que fala de um rei humilde montado num jumentinho. Os cristãos lembram esse dia no Domingo de Ramos.",
          "João 12:14-15; Zacarias 9:9",
        ),
        b(
          "resumo",
          "No templo",
          "Marcos conta que, em seguida, Jesus expulsa do templo os que vendiam e compravam, dizendo que a casa de Deus deveria ser casa de oração. As autoridades passam a procurar um jeito de prendê-lo.",
          "Marcos 11:15-18",
        ),
      ],
      exercises: [
        mc(
          "Montado em que animal Jesus entra em Jerusalém?",
          ["Um jumentinho", "Um cavalo", "Um camelo", "Um boi"],
          0,
          "Os Evangelhos falam de um jumentinho.",
          "Marcos 11:7",
        ),
        fill(
          "A multidão grita: “",
          "! Bendito o que vem em nome do Senhor!”",
          ["Hosana", "Aleluia", "Amém"],
          0,
          "“Hosana” é uma aclamação que aparece em Marcos 11:9.",
          "Marcos 11:9",
        ),
        tf(
          "Os cristãos lembram a entrada em Jerusalém no Domingo de Ramos.",
          true,
          "O nome vem dos ramos estendidos pelo caminho.",
          "João 12:13",
        ),
        mc(
          "Qual profeta João relaciona com a cena do jumentinho?",
          ["Zacarias", "Jonas", "Elias", "Daniel"],
          0,
          "João cita uma passagem de Zacarias 9:9.",
          "João 12:15",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Jesus se aproxima de Jerusalém", "A multidão estende mantos e ramos", "Jesus vai ao templo", "As autoridades buscam prendê-lo"],
          "Marcos 11.",
          "Marcos 11:1-18",
        ),
      ],
      takeaways: [
        "Jesus entra em Jerusalém num jumentinho, aclamado com “Hosana”.",
        "A cena é lembrada no Domingo de Ramos.",
        "Sua ação no templo aumenta a oposição das autoridades.",
      ],
      reflection: "Um rei num jumentinho: o que essa imagem diz sobre poder?",
    },
    {
      slug: "g08-ultima-ceia",
      title: "A última ceia",
      objective: "Conhecer a última refeição de Jesus com os discípulos.",
      references: ["Marcos 14:12-25", "João 13:1-17", "1 Coríntios 11:23-26"],
      context: "Na época da Páscoa, Jesus reúne os Doze para uma refeição. É uma noite de despedida.",
      blocks: [
        b(
          "resumo",
          "Pão e cálice",
          "Durante a refeição, Jesus toma o pão, dá graças, parte e entrega aos discípulos, dizendo que aquilo é o seu corpo. Depois, toma o cálice e diz que é o seu sangue da aliança.",
          "Marcos 14:22-24",
        ),
        b(
          "resumo",
          "O lava-pés",
          "O Evangelho de João conta que Jesus lavou os pés dos discípulos — tarefa de servo — e pediu que eles fizessem o mesmo uns pelos outros.",
          "João 13:4-15",
        ),
        b(
          "tradicoes",
          "Uma ceia lembrada até hoje",
          "Os cristãos celebram essa ceia com nomes diferentes: Eucaristia, Missa, Santa Ceia, Ceia do Senhor ou Comunhão. As tradições têm entendimentos diferentes sobre o sentido do pão e do vinho, e esse tema é tratado com respeito por cada uma.",
        ),
        b(
          "resumo",
          "Um anúncio difícil",
          "Durante a ceia, Jesus anuncia que um dos Doze o entregaria.",
          "Marcos 14:18-21",
        ),
      ],
      exercises: [
        mc(
          "Qual gesto de serviço o Evangelho de João destaca na última ceia?",
          ["Jesus lava os pés dos discípulos", "Jesus distribui ouro", "Jesus constrói uma mesa", "Jesus prepara peixes"],
          0,
          "O lava-pés está em João 13.",
          "João 13:4-15",
        ),
        tf(
          "Todas as tradições cristãs entendem o pão e o vinho da ceia exatamente da mesma forma.",
          false,
          "Há entendimentos diferentes entre as tradições.",
          "Marcos 14:22-24; 1 Coríntios 11:23-26",
        ),
        match(
          "Associe cada elemento ao que Jesus diz sobre ele.",
          [
            ["Pão", "“Isto é o meu corpo”"],
            ["Cálice", "“Sangue da aliança”"],
          ],
          "Palavras de Jesus na ceia, segundo Marcos.",
          "Marcos 14:22-24",
        ),
        fill(
          "A última ceia aconteceu na época da festa da",
          ".",
          ["Páscoa", "colheita", "Purim"],
          0,
          "Os Evangelhos situam a ceia perto da Páscoa.",
          "Marcos 14:12",
        ),
        mc(
          "Qual destes é um nome usado por cristãos para celebrar a ceia?",
          ["Eucaristia", "Pentecostes", "Advento", "Êxodo"],
          0,
          "Eucaristia, Santa Ceia, Ceia do Senhor e Comunhão são nomes usados.",
          "Tradição cristã",
        ),
      ],
      takeaways: [
        "Na última ceia, Jesus parte o pão e partilha o cálice.",
        "No Evangelho de João, ele lava os pés dos discípulos.",
        "Cristãos celebram essa ceia com nomes e entendimentos diferentes.",
      ],
      reflection: "Lavar os pés era tarefa de servo. Que gesto simples de serviço você pode fazer?",
    },
    {
      slug: "g08-getsemani",
      title: "Getsêmani e a prisão",
      objective: "Conhecer a oração de Jesus no Getsêmani e sua prisão.",
      references: ["Marcos 14:26-52", "Lucas 22:39-53", "João 18:1-11"],
      context: "Depois da ceia, Jesus vai com os discípulos ao monte das Oliveiras, a um lugar chamado Getsêmani.",
      blocks: [
        b(
          "resumo",
          "Angústia e oração",
          "Jesus leva consigo Pedro, Tiago e João e diz que está profundamente triste. Ele ora pedindo que, se possível, aquele cálice fosse afastado — mas que se fizesse a vontade do Pai.",
          "Marcos 14:32-36",
        ),
        b(
          "resumo",
          "Discípulos com sono",
          "Ao voltar, Jesus encontra os discípulos dormindo e pede que vigiem e orem. Isso acontece três vezes.",
          "Marcos 14:37-41",
        ),
        b(
          "resumo",
          "A prisão",
          "Judas chega com um grupo armado e identifica Jesus com um beijo. Um dos discípulos fere o servo do sumo sacerdote com uma espada. Jesus é preso, e os discípulos fogem.",
          "Marcos 14:43-50",
        ),
      ],
      exercises: [
        mc(
          "Quais discípulos Jesus levou mais perto para orar no Getsêmani?",
          ["Pedro, Tiago e João", "André, Filipe e Tomé", "Mateus, Judas e Simão", "Todos os doze"],
          0,
          "Jesus levou Pedro, Tiago e João.",
          "Marcos 14:33",
        ),
        fill(
          "Jesus ora: “Não o que eu quero, mas o que tu",
          "”.",
          ["queres", "dizes", "fazes"],
          0,
          "Jesus entrega a situação à vontade do Pai.",
          "Marcos 14:36",
        ),
        tf(
          "Os discípulos ficaram acordados orando a noite toda.",
          false,
          "Jesus os encontrou dormindo três vezes.",
          "Marcos 14:37-41",
        ),
        mc(
          "Como Judas identifica Jesus?",
          ["Com um beijo", "Apontando com uma tocha", "Chamando seu nome", "Entregando uma carta"],
          0,
          "O beijo era o sinal combinado.",
          "Marcos 14:44-45",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Ceia com os discípulos", "Oração no Getsêmani", "Chegada de Judas", "Prisão de Jesus"],
          "Marcos 14.",
          "Marcos 14:22-46",
        ),
      ],
      takeaways: [
        "No Getsêmani, Jesus ora com angústia e confiança.",
        "Os discípulos não conseguem vigiar.",
        "Judas entrega Jesus, que é preso; os discípulos fogem.",
      ],
      reflection: "Jesus foi honesto sobre sua angústia ao orar. Você se permite ser honesto assim?",
    },
    {
      slug: "g08-crucificacao",
      title: "A crucificação",
      objective: "Conhecer os relatos da crucificação de Jesus.",
      references: ["Marcos 15:1-41", "Lucas 23:26-49", "João 19:16-30"],
      context:
        "Jesus é levado ao conselho religioso e depois a Pôncio Pilatos, governador romano da Judeia. A crucificação era uma punição romana usada contra rebeldes e escravos.",
      blocks: [
        b(
          "resumo",
          "Diante de Pilatos",
          "Pilatos interroga Jesus. A multidão pede a libertação de outro preso, Barrabás, e a crucificação de Jesus. Pilatos entrega Jesus para ser crucificado.",
          "Marcos 15:1-15",
        ),
        b(
          "resumo",
          "No Gólgota",
          "Simão de Cirene é obrigado a carregar a cruz. Jesus é crucificado num lugar chamado Gólgota, entre dois homens. Uma inscrição dizia o motivo da condenação: “o rei dos judeus”.",
          "Marcos 15:21-27",
        ),
        b(
          "resumo",
          "Palavras na cruz",
          "Cada Evangelho registra palavras diferentes de Jesus na cruz. Lucas, por exemplo, traz um pedido de perdão por aqueles que o crucificavam; João traz “Está consumado”. Mulheres que o seguiam observavam, algumas de longe.",
          "Lucas 23:34; João 19:30; Marcos 15:40-41",
        ),
      ],
      exercises: [
        mc(
          "Quem era o governador romano que entregou Jesus para ser crucificado?",
          ["Pôncio Pilatos", "Herodes, o Grande", "César Augusto", "Caifás"],
          0,
          "Pilatos era o governador romano da Judeia.",
          "Marcos 15:1-15",
        ),
        fill(
          "Quem foi obrigado a carregar a cruz foi Simão de",
          ".",
          ["Cirene", "Nazaré", "Betsaida"],
          0,
          "Simão de Cirene foi forçado a carregar a cruz.",
          "Marcos 15:21",
        ),
        tf(
          "Os quatro Evangelhos registram exatamente as mesmas palavras de Jesus na cruz.",
          false,
          "Cada Evangelho registra palavras diferentes.",
          "Marcos 15; Lucas 23; João 19",
        ),
        match(
          "Associe cada nome ao seu papel.",
          [
            ["Barrabás", "Preso libertado no lugar de Jesus"],
            ["Gólgota", "Lugar da crucificação"],
            ["Simão de Cirene", "Carregou a cruz"],
          ],
          "Personagens e lugares do relato da Paixão.",
          "Marcos 15:7-22",
        ),
        mc(
          "Que palavras de Jesus na cruz o Evangelho de João registra?",
          ["“Está consumado”", "“Levanta-te e anda”", "“Eu sou o pão da vida”", "“Sigam-me”"],
          0,
          "João 19:30 registra “Está consumado”.",
          "João 19:30",
        ),
      ],
      takeaways: [
        "Jesus foi condenado por Pilatos e crucificado no Gólgota.",
        "A crucificação era uma punição romana.",
        "Cada Evangelho registra palavras diferentes de Jesus na cruz.",
      ],
      reflection: "Em Lucas, Jesus pede perdão por quem o feria. Como você reage a isso?",
    },
    {
      slug: "g08-ressurreicao",
      title: "O túmulo vazio",
      objective: "Conhecer os relatos da ressurreição de Jesus.",
      references: ["Marcos 16:1-8", "João 20:1-18", "Lucas 24:13-35", "1 Coríntios 15:3-8"],
      context:
        "Jesus é sepultado num túmulo cavado na rocha. No primeiro dia da semana, mulheres que o seguiam vão até lá. A ressurreição é o centro da fé cristã.",
      blocks: [
        b(
          "resumo",
          "As mulheres no túmulo",
          "Maria Madalena e outras mulheres vão ao túmulo com perfumes e encontram a pedra removida. Recebem o anúncio de que Jesus ressuscitou.",
          "Marcos 16:1-7",
        ),
        b(
          "resumo",
          "“Maria!”",
          "No Evangelho de João, Maria Madalena chora perto do túmulo e pensa estar falando com o jardineiro. Quando Jesus a chama pelo nome, ela o reconhece e vai anunciar aos discípulos.",
          "João 20:11-18",
        ),
        b(
          "resumo",
          "No caminho de Emaús",
          "Dois discípulos caminham para Emaús, tristes. Jesus se junta a eles sem ser reconhecido e explica as Escrituras. Eles o reconhecem quando ele parte o pão.",
          "Lucas 24:13-35",
        ),
      ],
      exercises: [
        mc(
          "Quem foi a primeira pessoa a encontrar Jesus ressuscitado, segundo João?",
          ["Maria Madalena", "Pedro", "Pilatos", "Tomé"],
          0,
          "Em João 20, Jesus aparece a Maria Madalena.",
          "João 20:14-16",
        ),
        tf(
          "Os discípulos de Emaús reconheceram Jesus quando ele partiu o pão.",
          true,
          "Lucas 24:30-31 narra o reconhecimento.",
          "Lucas 24:30-31",
        ),
        fill(
          "Maria Madalena pensou que Jesus fosse o",
          ".",
          ["jardineiro", "pescador", "soldado"],
          0,
          "Ela o reconheceu quando ele a chamou pelo nome.",
          "João 20:15-16",
        ),
        mc(
          "Em que dia as mulheres foram ao túmulo?",
          ["No primeiro dia da semana", "No sábado à noite", "Uma semana depois", "No dia da crucificação"],
          0,
          "Os Evangelhos falam do primeiro dia da semana — o domingo.",
          "Marcos 16:2",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Jesus é sepultado", "As mulheres encontram o túmulo aberto", "Jesus aparece a Maria Madalena", "Os discípulos de Emaús o reconhecem"],
          "Marcos 15-16; João 20; Lucas 24.",
          "Marcos 15:46-Lucas 24:35",
        ),
      ],
      takeaways: [
        "No primeiro dia da semana, as mulheres encontram o túmulo vazio.",
        "Maria Madalena reconhece Jesus quando ele a chama pelo nome.",
        "Em Emaús, os discípulos o reconhecem ao partir o pão.",
      ],
      reflection: "Os discípulos de Emaús caminhavam tristes. O que costuma devolver sua esperança?",
    },
  ],
  review: {
    slug: "g08-revisao",
    title: "Revisão: Morte e ressurreição",
    intro: "A semana mais importante dos Evangelhos. Vamos relembrar com calma.",
    extra: [
      order(
        "Ordene a última semana de Jesus.",
        ["Entrada em Jerusalém", "Última ceia", "Getsêmani", "Crucificação", "Túmulo vazio"],
        "Essa é a sequência dos relatos da Paixão e Ressurreição.",
        "Marcos 11-16",
      ),
      match(
        "Associe cada lugar ao acontecimento.",
        [
          ["Getsêmani", "Oração e prisão"],
          ["Gólgota", "Crucificação"],
          ["Emaús", "Reconhecimento ao partir o pão"],
        ],
        "Lugares marcantes desta unidade.",
        "Marcos 14-15; Lucas 24",
      ),
      tf(
        "Mulheres que seguiam Jesus foram as primeiras a encontrar o túmulo vazio.",
        true,
        "Os Evangelhos dão destaque às mulheres no túmulo.",
        "Marcos 16:1-8",
      ),
    ],
    takeaways: [
      "A última semana vai da entrada em Jerusalém à cruz.",
      "A ceia, o Getsêmani e a prisão revelam entrega e fragilidade.",
      "O túmulo vazio e os encontros com o Ressuscitado são o centro da fé cristã.",
    ],
  },
};
