import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const u09: UnitDef = {
  slug: "geral-u09-igreja-primitiva",
  title: "A igreja primitiva",
  description: "Os primeiros passos das comunidades cristãs, segundo o livro de Atos.",
  scene: "road",
  lessons: [
    {
      slug: "g09-pentecostes",
      title: "Ascensão e Pentecostes",
      objective: "Conhecer o início do livro de Atos e o dia de Pentecostes.",
      references: ["Atos 1:1-11", "Atos 2:1-41"],
      context:
        "O livro de Atos dos Apóstolos é a continuação do Evangelho de Lucas — os dois são dedicados a um certo Teófilo. Atos conta como o movimento de Jesus se espalhou.",
      blocks: [
        b(
          "resumo",
          "A ascensão",
          "Jesus diz aos discípulos que receberiam a força do Espírito Santo e seriam suas testemunhas em Jerusalém, na Judeia, em Samaria e até os confins da terra. Depois, é elevado ao céu diante deles.",
          "Atos 1:8-9",
        ),
        b(
          "resumo",
          "Vento e línguas de fogo",
          "No dia de Pentecostes, os discípulos estavam reunidos. Veio um som como de vento forte, e apareceram línguas como de fogo sobre cada um. Eles começaram a falar em outras línguas, e pessoas de muitos lugares os entendiam em seu próprio idioma.",
          "Atos 2:1-11",
        ),
        b(
          "resumo",
          "O discurso de Pedro",
          "Pedro explica o que estava acontecendo e anuncia Jesus ressuscitado. Atos conta que cerca de três mil pessoas foram batizadas naquele dia.",
          "Atos 2:14-41",
        ),
        b(
          "contexto",
          "O que era Pentecostes?",
          "Pentecostes (“quinquagésimo”, em grego) era uma festa judaica celebrada cinquenta dias depois da Páscoa, ligada à colheita. Para os cristãos, passou a lembrar a vinda do Espírito Santo.",
        ),
      ],
      exercises: [
        mc(
          "Qual livro é a continuação do Evangelho de Lucas?",
          ["Atos dos Apóstolos", "Romanos", "João", "Apocalipse"],
          0,
          "Lucas e Atos são dedicados a Teófilo e formam uma obra em duas partes.",
          "Lucas 1:1-4; Atos 1:1",
        ),
        order(
          "Ordene os lugares do testemunho, segundo Atos 1:8.",
          ["Jerusalém", "Judeia", "Samaria", "Confins da terra"],
          "A missão se espalha de Jerusalém para o mundo.",
          "Atos 1:8",
        ),
        fill(
          "No Pentecostes, apareceram línguas como de",
          "sobre os discípulos.",
          ["fogo", "água", "luz de estrelas"],
          0,
          "Atos 2:3 fala de línguas como de fogo.",
          "Atos 2:3",
        ),
        tf(
          "Pentecostes já era uma festa judaica antes desse acontecimento.",
          true,
          "Era a festa celebrada cinquenta dias depois da Páscoa.",
          "Atos 2:1",
        ),
        mc(
          "Quem faz o discurso no dia de Pentecostes?",
          ["Pedro", "Paulo", "Estêvão", "Tiago"],
          0,
          "Pedro se levanta e fala à multidão.",
          "Atos 2:14",
        ),
      ],
      takeaways: [
        "Atos continua a obra de Lucas.",
        "No Pentecostes, o Espírito vem sobre os discípulos.",
        "Pedro anuncia Jesus ressuscitado e muitos são batizados.",
      ],
      reflection: "Pessoas de muitos lugares entenderam a mesma mensagem. O que ajuda você a se comunicar com quem é diferente?",
    },
    {
      slug: "g09-primeira-comunidade",
      title: "A vida da primeira comunidade",
      objective: "Conhecer como viviam os primeiros cristãos em Jerusalém.",
      references: ["Atos 2:42-47", "Atos 4:32-37", "Atos 6:1-7"],
      context: "Atos descreve a vida dos primeiros seguidores de Jesus em Jerusalém, com encontros nas casas e no templo.",
      blocks: [
        b(
          "resumo",
          "Quatro marcas",
          "Os primeiros cristãos perseveravam no ensino dos apóstolos, na comunhão, no partir do pão e nas orações. Faziam as refeições com alegria e simplicidade.",
          "Atos 2:42-47",
        ),
        b(
          "resumo",
          "Partilha",
          "Ninguém considerava seus bens só seus; repartiam conforme a necessidade de cada um. Barnabé, por exemplo, vendeu um campo e entregou o dinheiro aos apóstolos.",
          "Atos 4:32-37",
        ),
        b(
          "resumo",
          "Problemas reais",
          "A comunidade também teve conflitos: viúvas de língua grega estavam sendo esquecidas na distribuição diária de alimentos. Os apóstolos pediram que fossem escolhidos sete homens para cuidar desse serviço, entre eles Estêvão.",
          "Atos 6:1-6",
        ),
      ],
      exercises: [
        match(
          "Complete as expressões sobre a primeira comunidade.",
          [
            ["Ensino", "dos apóstolos"],
            ["Partir", "do pão"],
            ["Partilha", "conforme a necessidade"],
            ["Refeições", "com alegria e simplicidade"],
          ],
          "Atos 2 e 4 descrevem essas práticas.",
          "Atos 2:42-46; 4:35",
        ),
        mc(
          "Quem vendeu um campo e entregou o dinheiro aos apóstolos?",
          ["Barnabé", "Pedro", "Saulo", "Filipe"],
          0,
          "Barnabé é citado como exemplo de partilha.",
          "Atos 4:36-37",
        ),
        tf(
          "Segundo Atos, a primeira comunidade não teve nenhum conflito.",
          false,
          "Houve problema com a distribuição às viúvas de língua grega.",
          "Atos 6:1",
        ),
        fill(
          "Para cuidar da distribuição, foram escolhidos",
          "homens.",
          ["sete", "doze", "três"],
          0,
          "Atos 6:3 fala de sete homens.",
          "Atos 6:3-5",
        ),
        mc(
          "Onde os primeiros cristãos se reuniam?",
          ["Nas casas e no templo", "Somente no deserto", "Em navios", "No palácio de Herodes"],
          0,
          "Atos 2:46 menciona o templo e as casas.",
          "Atos 2:46",
        ),
      ],
      takeaways: [
        "A comunidade vivia ensino, comunhão, partir do pão e oração.",
        "Havia partilha de bens conforme a necessidade.",
        "Conflitos foram enfrentados com organização e escuta.",
      ],
      reflection: "Qual dessas marcas da primeira comunidade faz falta nos grupos que você conhece?",
    },
    {
      slug: "g09-estevao",
      title: "Estêvão e a dispersão",
      objective: "Conhecer Estêvão e como a mensagem saiu de Jerusalém.",
      references: ["Atos 6:8-15", "Atos 7:54-60", "Atos 8:1-8, 26-39"],
      context: "Estêvão, um dos sete escolhidos para servir, também anunciava Jesus com coragem.",
      blocks: [
        b(
          "resumo",
          "O primeiro mártir",
          "Estêvão é levado ao conselho e faz um longo discurso. Ele é apedrejado e, enquanto morre, pede que Deus não leve em conta aquele pecado. Por isso é lembrado como o primeiro mártir cristão.",
          "Atos 7:54-60",
        ),
        b(
          "resumo",
          "Um jovem chamado Saulo",
          "As testemunhas deixam suas roupas aos pés de um jovem chamado Saulo, que aprovava a morte de Estêvão. Depois, começa uma perseguição e muitos fiéis se espalham pela Judeia e Samaria.",
          "Atos 7:58; 8:1-3",
        ),
        b(
          "resumo",
          "Filipe na estrada",
          "Filipe anuncia Jesus em Samaria. Depois, na estrada para Gaza, encontra um oficial etíope que lia o profeta Isaías. Filipe explica o texto e o batiza.",
          "Atos 8:5-8, 26-38",
        ),
      ],
      exercises: [
        mc(
          "Por que Estêvão é lembrado de forma especial?",
          ["Como o primeiro mártir cristão", "Como o primeiro rei", "Como autor de um Evangelho", "Como o construtor do templo"],
          0,
          "Estêvão foi o primeiro a morrer por causa de sua fé, segundo Atos.",
          "Atos 7:59-60",
        ),
        tf(
          "Saulo aprovava a morte de Estêvão.",
          true,
          "Atos 8:1 diz que Saulo consentia na morte de Estêvão.",
          "Atos 8:1",
        ),
        fill(
          "O oficial etíope estava lendo o livro do profeta",
          ".",
          ["Isaías", "Jonas", "Daniel"],
          0,
          "Ele lia Isaías quando Filipe se aproximou.",
          "Atos 8:28-32",
        ),
        mc(
          "Para onde os fiéis se espalharam por causa da perseguição?",
          ["Judeia e Samaria", "Egito e Babilônia", "Roma e Grécia", "Pérsia e Índia"],
          0,
          "Atos 8:1 cita a Judeia e Samaria.",
          "Atos 8:1",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Estêvão é escolhido para servir", "Estêvão é apedrejado", "Perseguição e dispersão", "Filipe batiza o oficial etíope"],
          "Atos 6-8.",
          "Atos 6:5-8:38",
        ),
      ],
      takeaways: [
        "Estêvão é lembrado como o primeiro mártir cristão.",
        "A perseguição espalhou os fiéis para a Judeia e Samaria.",
        "Filipe leva a mensagem a Samaria e a um oficial etíope.",
      ],
      reflection: "Estêvão perdoou quem o feria. Que situação pede perdão de você?",
    },
    {
      slug: "g09-conversao-de-saulo",
      title: "A conversão de Saulo",
      objective: "Conhecer o encontro de Saulo com Jesus no caminho de Damasco.",
      references: ["Atos 9:1-19", "Gálatas 1:13-17"],
      context: "Saulo, que perseguia os seguidores de Jesus, vai a Damasco com cartas que o autorizavam a prendê-los.",
      blocks: [
        b(
          "resumo",
          "Uma luz no caminho",
          "Perto de Damasco, uma luz do céu envolve Saulo. Ele cai por terra e ouve uma voz: “Saulo, Saulo, por que me persegues?”. A voz diz: “Eu sou Jesus, a quem tu persegues”.",
          "Atos 9:3-5",
        ),
        b(
          "resumo",
          "Três dias sem ver",
          "Saulo se levanta sem enxergar e é levado pela mão até Damasco. Fica três dias sem ver, sem comer e sem beber.",
          "Atos 9:8-9",
        ),
        b(
          "explicacao",
          "Saulo e Paulo",
          "Saulo é um nome hebraico; Paulo, um nome latino. Atos passa a usar “Paulo” a partir do capítulo 13. Não se trata de um nome trocado na conversão: ele era conhecido pelos dois.",
          "Atos 13:9",
        ),
      ],
      exercises: [
        mc(
          "Para qual cidade Saulo estava indo?",
          ["Damasco", "Roma", "Antioquia", "Atenas"],
          0,
          "Saulo ia a Damasco para prender seguidores de Jesus.",
          "Atos 9:2-3",
        ),
        fill(
          "A voz pergunta: “Saulo, Saulo, por que me",
          "?”",
          ["persegues", "esqueces", "chamas"],
          0,
          "A pergunta está em Atos 9:4.",
          "Atos 9:4",
        ),
        tf(
          "Depois do encontro, Saulo ficou três dias sem enxergar.",
          true,
          "Atos 9:9 diz que ele ficou três dias sem ver.",
          "Atos 9:9",
        ),
        mc(
          "O que é correto sobre os nomes Saulo e Paulo?",
          [
            "Ele era conhecido pelos dois nomes, hebraico e latino",
            "Jesus trocou o nome dele no caminho",
            "Eram duas pessoas diferentes",
            "Paulo era seu apelido de infância",
          ],
          0,
          "Atos 13:9 diz “Saulo, também chamado Paulo”.",
          "Atos 13:9",
        ),
        order(
          "Ordene os acontecimentos.",
          ["Saulo pede cartas para prender os fiéis", "Uma luz o envolve no caminho", "Fica três dias sem ver", "Volta a enxergar e é batizado"],
          "Atos 9:1-18.",
          "Atos 9:1-18",
        ),
      ],
      takeaways: [
        "Saulo perseguia os seguidores de Jesus.",
        "No caminho de Damasco, ele encontra Jesus e fica três dias sem ver.",
        "Saulo e Paulo são dois nomes da mesma pessoa.",
      ],
      reflection: "Saulo mudou de direção completamente. Que mudança de rota você admira em alguém?",
    },
    {
      slug: "g09-concilio-de-jerusalem",
      title: "O concílio de Jerusalém",
      objective: "Entender a primeira grande discussão das comunidades cristãs.",
      references: ["Atos 15:1-35", "Gálatas 2:1-10"],
      context:
        "Com a chegada de muitos não judeus (gentios) à fé, surge uma pergunta: eles precisavam seguir toda a Lei de Moisés, incluindo a circuncisão?",
      blocks: [
        b(
          "resumo",
          "Uma discussão séria",
          "Alguns diziam que os gentios precisavam ser circuncidados. Paulo e Barnabé discordaram, e a questão foi levada aos apóstolos e anciãos em Jerusalém.",
          "Atos 15:1-6",
        ),
        b(
          "resumo",
          "Vozes no concílio",
          "Pedro lembra que Deus tinha acolhido gentios. Paulo e Barnabé contam o que viram em suas viagens. Tiago propõe não impor um fardo aos gentios, pedindo apenas alguns cuidados.",
          "Atos 15:7-21",
        ),
        b(
          "resumo",
          "Uma carta de alegria",
          "A decisão é enviada por carta às comunidades, que ficam alegres e encorajadas.",
          "Atos 15:22-31",
        ),
      ],
      exercises: [
        mc(
          "Qual era a principal questão do concílio?",
          [
            "Se os gentios precisavam ser circuncidados e seguir toda a Lei",
            "Quem seria o novo rei",
            "Onde construir um novo templo",
            "Qual língua usar nas orações",
          ],
          0,
          "A discussão era sobre os gentios e a Lei de Moisés.",
          "Atos 15:1, 5",
        ),
        match(
          "Associe cada pessoa à sua participação no concílio.",
          [
            ["Pedro", "Lembra que Deus acolheu gentios"],
            ["Paulo e Barnabé", "Contam o que viram nas viagens"],
            ["Tiago", "Propõe não impor um fardo"],
          ],
          "Diferentes vozes contribuem para a decisão.",
          "Atos 15:7-21",
        ),
        fill(
          "Os cristãos de origem não judaica são chamados de",
          ".",
          ["gentios", "levitas", "fariseus"],
          0,
          "“Gentios” se refere aos não judeus.",
          "Atos 15:3",
        ),
        tf(
          "A decisão foi comunicada às comunidades por meio de uma carta.",
          true,
          "Atos 15:23-29 traz a carta.",
          "Atos 15:23-31",
        ),
        mc(
          "Em que cidade aconteceu esse encontro?",
          ["Jerusalém", "Antioquia", "Roma", "Corinto"],
          0,
          "Por isso é chamado de concílio de Jerusalém.",
          "Atos 15:2-4",
        ),
      ],
      takeaways: [
        "A chegada dos gentios levantou questões sobre a Lei.",
        "Pedro, Paulo, Barnabé e Tiago participaram da discussão.",
        "A decisão foi acolhida com alegria pelas comunidades.",
      ],
      reflection: "Como o seu grupo costuma resolver discordâncias importantes?",
    },
  ],
  review: {
    slug: "g09-revisao",
    title: "Revisão: A igreja primitiva",
    intro: "De Jerusalém para o mundo! Vamos relembrar os primeiros passos das comunidades.",
    extra: [
      order(
        "Ordene os acontecimentos de Atos.",
        ["Pentecostes", "Escolha dos sete", "Morte de Estêvão", "Conversão de Saulo", "Concílio de Jerusalém"],
        "Atos 2, 6, 7, 9 e 15.",
        "Atos 2-15",
      ),
      match(
        "Associe cada pessoa a um momento.",
        [
          ["Estêvão", "Primeiro mártir"],
          ["Filipe", "Batiza o oficial etíope"],
          ["Barnabé", "Vende um campo e partilha"],
        ],
        "Personagens de Atos.",
        "Atos 4; 7; 8",
      ),
      tf(
        "Lucas e Atos formam uma obra em duas partes dedicada a Teófilo.",
        true,
        "Os dois livros começam se dirigindo a Teófilo.",
        "Lucas 1:3; Atos 1:1",
      ),
    ],
    takeaways: [
      "Atos conta a expansão da mensagem de Jerusalém para o mundo.",
      "A comunidade vivia partilha, oração e também enfrentava conflitos.",
      "Saulo, o perseguidor, se torna Paulo, o apóstolo.",
    ],
  },
};
