import { b, fill, match, mc, order, tf, type UnitDef } from "../schema";

export const u10: UnitDef = {
  slug: "geral-u10-fe-no-cotidiano",
  title: "Fé na vida cotidiana",
  description: "O que os textos bíblicos dizem sobre amor, perdão, oração, generosidade e esperança.",
  scene: "village",
  lessons: [
    {
      slug: "g10-amor-ao-proximo",
      title: "O maior mandamento",
      objective: "Conhecer como Jesus resume a Lei e como Paulo descreve o amor.",
      references: ["Mateus 22:34-40", "Levítico 19:18", "1 Coríntios 13:1-7"],
      context:
        "Nesta unidade, olhamos para textos que falam do dia a dia. Aqui você conhece o que os textos dizem; como aplicar é uma reflexão pessoal, no seu tempo.",
      blocks: [
        b(
          "resumo",
          "Dois mandamentos",
          "Perguntado sobre o maior mandamento, Jesus responde com dois: amar a Deus de todo o coração, alma e entendimento, e amar o próximo como a si mesmo. Ele diz que toda a Lei e os Profetas dependem desses dois.",
          "Mateus 22:37-40",
        ),
        b(
          "contexto",
          "Uma citação antiga",
          "O “amar o próximo como a si mesmo” já estava no livro de Levítico. Jesus junta esse mandamento ao de amar a Deus, que está em Deuteronômio.",
          "Levítico 19:18; Deuteronômio 6:5",
        ),
        b(
          "resumo",
          "Como é o amor",
          "Em sua carta aos coríntios, Paulo diz que, sem amor, até grandes dons não valem nada. Ele descreve o amor como paciente, bondoso, sem inveja e sem orgulho, que não guarda rancor.",
          "1 Coríntios 13:1-7",
        ),
      ],
      exercises: [
        match(
          "Associe cada mandamento ao livro onde já aparecia.",
          [
            ["Amar a Deus de todo o coração", "Deuteronômio"],
            ["Amar o próximo como a si mesmo", "Levítico"],
          ],
          "Jesus une dois mandamentos da Lei de Moisés.",
          "Deuteronômio 6:5; Levítico 19:18",
        ),
        fill(
          "Jesus diz que toda a Lei e os",
          "dependem desses dois mandamentos.",
          ["Profetas", "Reis", "Salmos"],
          0,
          "Mateus 22:40.",
          "Mateus 22:40",
        ),
        mc(
          "Qual destas características NÃO está na descrição do amor em 1 Coríntios 13?",
          ["Ser orgulhoso", "Ser paciente", "Ser bondoso", "Não guardar rancor"],
          0,
          "Paulo diz que o amor não é orgulhoso.",
          "1 Coríntios 13:4-5",
        ),
        tf(
          "O mandamento de amar o próximo apareceu pela primeira vez no Novo Testamento.",
          false,
          "Ele já estava em Levítico 19:18.",
          "Levítico 19:18",
        ),
        mc(
          "A quem Paulo escreve a descrição do amor?",
          ["Aos coríntios", "Aos romanos", "A Timóteo", "Aos filipenses"],
          0,
          "Está em 1 Coríntios 13.",
          "1 Coríntios 13",
        ),
      ],
      takeaways: [
        "Jesus resume a Lei em amar a Deus e ao próximo.",
        "Os dois mandamentos já estavam na Lei de Moisés.",
        "Paulo descreve o amor como paciente e bondoso.",
      ],
      reflection: "Qual característica do amor em 1 Coríntios 13 você gostaria de viver mais?",
    },
    {
      slug: "g10-perdao",
      title: "Perdão",
      objective: "Conhecer o ensino de Jesus sobre perdoar.",
      references: ["Mateus 18:21-35", "Colossenses 3:13"],
      context: "Perdoar é um dos temas mais difíceis e mais presentes nos Evangelhos.",
      blocks: [
        b(
          "resumo",
          "Quantas vezes?",
          "Pedro pergunta a Jesus se deveria perdoar até sete vezes. Jesus responde: não sete, mas setenta vezes sete (algumas traduções trazem “setenta e sete vezes”) — nos dois casos, a ideia é perdoar sem fazer conta.",
          "Mateus 18:21-22",
        ),
        b(
          "resumo",
          "O servo que não perdoou",
          "Jesus conta de um servo que teve uma dívida enorme perdoada pelo rei, mas depois não perdoou um colega que lhe devia muito pouco. O rei fica indignado com a falta de compaixão.",
          "Mateus 18:23-35",
        ),
        b(
          "explicacao",
          "Perdão não é ignorar a dor",
          "Perdoar não significa dizer que o mal não importou nem permanecer em situações de abuso. Muitas tradições cristãs entendem o perdão como um caminho, às vezes longo, que também pode envolver buscar justiça e proteção.",
        ),
      ],
      exercises: [
        fill(
          "Jesus diz que é preciso perdoar não sete, mas setenta vezes",
          ".",
          ["sete", "dez", "três"],
          0,
          "A resposta indica um perdão sem contagem.",
          "Mateus 18:22",
        ),
        mc(
          "Quem pergunta a Jesus quantas vezes deve perdoar?",
          ["Pedro", "João", "Judas", "Tomé"],
          0,
          "É Pedro quem faz a pergunta.",
          "Mateus 18:21",
        ),
        tf(
          "Na parábola, o servo perdoado também perdoou seu colega.",
          false,
          "Ele não perdoou o colega, e o rei ficou indignado.",
          "Mateus 18:28-34",
        ),
        match(
          "Associe as dívidas da parábola.",
          [
            ["Dívida do servo com o rei", "Enorme"],
            ["Dívida do colega com o servo", "Pequena"],
          ],
          "O contraste entre as dívidas é o centro da parábola.",
          "Mateus 18:24, 28",
        ),
        mc(
          "Qual destas afirmações combina com a explicação desta lição?",
          [
            "Perdoar não exige permanecer em situações de abuso",
            "Perdoar significa fingir que nada aconteceu",
            "Só se deve perdoar sete vezes",
            "Perdão é sempre imediato e fácil",
          ],
          0,
          "Perdão pode ser um caminho e não anula a busca de proteção e justiça.",
          "Mateus 18:21-35",
        ),
      ],
      takeaways: [
        "Jesus fala de um perdão sem contagem: “setenta vezes sete”.",
        "A parábola do servo mostra a importância da compaixão.",
        "Perdoar não é ignorar a dor nem permanecer em abuso.",
      ],
      reflection: "Existe algo que você gostaria de começar a perdoar, no seu tempo?",
    },
    {
      slug: "g10-oracao",
      title: "Oração no dia a dia",
      objective: "Conhecer alguns ensinamentos bíblicos sobre oração.",
      references: ["Mateus 6:5-8", "Filipenses 4:6-7", "Salmos 62:8", "1 Tessalonicenses 5:16-18"],
      context: "A Bíblia mostra pessoas orando de muitos jeitos: em silêncio, cantando, chorando, agradecendo ou pedindo ajuda.",
      blocks: [
        b(
          "resumo",
          "No quarto, em segredo",
          "Jesus orienta a orar em particular, com sinceridade, e não para ser visto pelos outros.",
          "Mateus 6:6",
        ),
        b(
          "resumo",
          "Sem ansiedade, com gratidão",
          "Paulo encoraja a apresentar a Deus todos os pedidos, com gratidão, e fala de uma paz que guarda o coração e a mente.",
          "Filipenses 4:6-7",
        ),
        b(
          "resumo",
          "Abrir o coração",
          "Um salmo convida a derramar o coração diante de Deus em todo tempo. Em outra carta, Paulo fala de orar sem cessar e agradecer em tudo.",
          "Salmos 62:8; 1 Tessalonicenses 5:17-18",
        ),
      ],
      exercises: [
        mc(
          "Segundo Mateus 6, onde Jesus sugere orar?",
          ["No quarto, em particular", "Somente em praça pública", "Apenas no templo", "Só em grupo"],
          0,
          "Jesus fala de entrar no quarto e orar em secreto.",
          "Mateus 6:6",
        ),
        fill(
          "Paulo encoraja a apresentar os pedidos a Deus com",
          ".",
          ["gratidão", "pressa", "medo"],
          0,
          "Filipenses 4:6 menciona ação de graças.",
          "Filipenses 4:6",
        ),
        tf(
          "Na Bíblia, há orações de tristeza e queixa, não só de alegria.",
          true,
          "Muitos salmos expressam dor e queixa.",
          "Salmos 13; 62:8",
        ),
        match(
          "Associe cada texto ao ensinamento.",
          [
            ["Mateus 6:6", "Orar em particular"],
            ["Filipenses 4:6-7", "Pedidos com gratidão e paz"],
            ["1 Tessalonicenses 5:17", "Orar sem cessar"],
          ],
          "Cada texto destaca um aspecto da oração.",
          "Mateus 6:6; Filipenses 4:6-7; 1 Tessalonicenses 5:17",
        ),
        mc(
          "O Salmo 62 convida a…",
          ["Derramar o coração diante de Deus", "Esconder os sentimentos", "Orar só uma vez por ano", "Falar apenas palavras decoradas"],
          0,
          "Salmos 62:8 fala de derramar o coração.",
          "Salmos 62:8",
        ),
      ],
      takeaways: [
        "Jesus valoriza a oração sincera, sem exibição.",
        "Paulo fala de pedidos com gratidão e de paz no coração.",
        "A Bíblia mostra orações de alegria e também de dor.",
      ],
      reflection: "Se fosse escrever uma oração curta agora, o que diria?",
    },
    {
      slug: "g10-generosidade",
      title: "Generosidade e cuidado",
      objective: "Conhecer textos bíblicos sobre partilha e cuidado com quem precisa.",
      references: ["Mateus 25:31-40", "2 Coríntios 9:6-7", "Tiago 2:14-17"],
      context: "Os textos bíblicos insistem no cuidado com pobres, estrangeiros, doentes e presos.",
      blocks: [
        b(
          "resumo",
          "“A mim o fizestes”",
          "Em Mateus 25, Jesus fala de dar comida a quem tem fome, água a quem tem sede, acolher o estrangeiro, vestir quem está sem roupa, visitar doentes e presos — e diz que o que foi feito ao menor dos irmãos foi feito a ele.",
          "Mateus 25:35-40",
        ),
        b(
          "resumo",
          "Com alegria",
          "Paulo diz que cada um dê conforme decidiu no coração, não com tristeza nem por obrigação, pois Deus ama quem dá com alegria.",
          "2 Coríntios 9:7",
        ),
        b(
          "resumo",
          "Fé com obras",
          "Tiago pergunta de que adianta dizer a alguém sem roupa e sem comida “vá em paz” sem ajudá-lo. Para ele, a fé sem obras é morta.",
          "Tiago 2:15-17",
        ),
      ],
      exercises: [
        mc(
          "Em Mateus 25, o que foi feito “ao menor dos irmãos” foi feito a quem?",
          ["A Jesus", "Ao rei Herodes", "Aos sacerdotes", "A ninguém"],
          0,
          "Jesus se identifica com os mais necessitados.",
          "Mateus 25:40",
        ),
        fill(
          "Deus ama quem dá com",
          ".",
          ["alegria", "tristeza", "obrigação"],
          0,
          "2 Coríntios 9:7.",
          "2 Coríntios 9:7",
        ),
        tf(
          "Tiago diz que a fé sem obras é morta.",
          true,
          "Tiago 2:17.",
          "Tiago 2:17",
        ),
        match(
          "Associe cada necessidade à ação citada em Mateus 25.",
          [
            ["Fome", "Dar de comer"],
            ["Estrangeiro", "Acolher"],
            ["Doença", "Visitar"],
          ],
          "Ações de cuidado listadas por Jesus.",
          "Mateus 25:35-36",
        ),
        mc(
          "Qual carta fala que cada um dê “conforme decidiu no coração”?",
          ["2 Coríntios", "Tiago", "Gálatas", "1 Pedro"],
          0,
          "2 Coríntios 9:7.",
          "2 Coríntios 9:7",
        ),
      ],
      takeaways: [
        "Em Mateus 25, cuidar dos necessitados é cuidar do próprio Jesus.",
        "Paulo fala de dar com alegria, não por obrigação.",
        "Tiago liga a fé a ações concretas.",
      ],
      reflection: "Qual gesto concreto de cuidado cabe na sua semana?",
    },
    {
      slug: "g10-esperanca",
      title: "Esperança em tempos difíceis",
      objective: "Conhecer textos bíblicos de consolo e esperança.",
      references: ["Salmos 23", "Romanos 8:35-39", "Apocalipse 21:3-4"],
      context: "A Bíblia não ignora o sofrimento. Muitos textos foram escritos em meio a crises e falam de esperança.",
      blocks: [
        b(
          "resumo",
          "No vale escuro",
          "O Salmo 23 fala de atravessar o vale da sombra da morte sem medo, porque Deus está junto, como um pastor.",
          "Salmos 23:4",
        ),
        b(
          "resumo",
          "Nada pode separar",
          "Paulo pergunta o que poderia separar as pessoas do amor de Cristo — tribulação, angústia, perseguição, fome — e afirma que nada, nem a morte nem a vida, pode separá-las do amor de Deus.",
          "Romanos 8:35-39",
        ),
        b(
          "resumo",
          "Toda lágrima",
          "No fim da Bíblia, o Apocalipse traz a imagem de Deus habitando com as pessoas e enxugando toda lágrima, sem morte nem dor.",
          "Apocalipse 21:3-4",
        ),
        b(
          "explicacao",
          "Esperança não é negar a dor",
          "Esses textos não pedem que ninguém finja estar bem. Eles falam de companhia e esperança no meio da dificuldade. Se você estiver passando por um momento muito difícil, procurar ajuda de pessoas de confiança e de profissionais também é cuidado.",
        ),
      ],
      exercises: [
        mc(
          "No Salmo 23, por que o salmista não tem medo no vale escuro?",
          ["Porque Deus está com ele", "Porque o vale é iluminado", "Porque está armado", "Porque o vale é curto"],
          0,
          "Salmos 23:4.",
          "Salmos 23:4",
        ),
        tf(
          "Em Romanos 8, Paulo diz que a morte pode separar as pessoas do amor de Deus.",
          false,
          "Paulo afirma que nada, nem a morte, pode separar do amor de Deus.",
          "Romanos 8:38-39",
        ),
        fill(
          "No Apocalipse, Deus enxuga toda",
          ".",
          ["lágrima", "estrada", "dívida"],
          0,
          "Apocalipse 21:4.",
          "Apocalipse 21:4",
        ),
        order(
          "Ordene os livros como aparecem na Bíblia.",
          ["Salmos", "Romanos", "Apocalipse"],
          "Salmos está no Antigo Testamento; Romanos e Apocalipse no Novo, com Apocalipse por último.",
          "Salmos; Romanos; Apocalipse",
        ),
        mc(
          "Qual atitude a lição propõe diante de momentos muito difíceis?",
          [
            "Buscar companhia, pessoas de confiança e ajuda profissional",
            "Fingir que está tudo bem",
            "Esconder o que sente",
            "Enfrentar tudo sozinho",
          ],
          0,
          "Esperança caminha junto com cuidado e apoio.",
          "Salmos 23; Romanos 8",
        ),
      ],
      takeaways: [
        "O Salmo 23 fala de companhia no vale escuro.",
        "Paulo afirma que nada separa do amor de Deus.",
        "O Apocalipse termina com a imagem de um mundo sem lágrimas.",
      ],
      reflection: "Qual texto desta lição você gostaria de guardar para um dia difícil?",
    },
  ],
  review: {
    slug: "g10-revisao",
    title: "Revisão: Fé na vida cotidiana",
    intro: "Última revisão da jornada geral! Vamos relembrar textos sobre amor, perdão, oração, partilha e esperança.",
    extra: [
      match(
        "Associe cada tema a um texto.",
        [
          ["Amor", "1 Coríntios 13"],
          ["Perdão", "Mateus 18"],
          ["Partilha", "Mateus 25"],
          ["Esperança", "Romanos 8"],
        ],
        "Cada tema desta unidade tem textos de referência.",
        "1 Coríntios 13; Mateus 18; 25; Romanos 8",
      ),
      mc(
        "Como Jesus resume a Lei?",
        ["Amar a Deus e ao próximo", "Guardar o sábado e jejuar", "Construir o templo", "Oferecer sacrifícios"],
        0,
        "Mateus 22:37-40.",
        "Mateus 22:37-40",
      ),
      tf(
        "Segundo Tiago, a fé verdadeira se mostra também em ações.",
        true,
        "Tiago 2:17.",
        "Tiago 2:14-17",
      ),
    ],
    takeaways: [
      "Amor a Deus e ao próximo resume a Lei.",
      "Perdão, oração e generosidade aparecem como caminhos de vida.",
      "Os textos bíblicos falam de esperança sem negar a dor.",
    ],
  },
};
